// A te 280+ szavas személyes szótárad (biztonságosan a fájlba mentve)
const SAMPLE_WORDS = [
  {en: "traces", hu: "nyomok", tags: ["nyomozás", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "potions", hu: "bájitalok / főzetek", tags: ["fantázia", "ételek"], diff: "B2", syn: "", sentence: ""},
  {en: "beyonder", hu: "túlontúli személy", tags: ["fantázia", "mitológia"], diff: "C2", syn: "", sentence: ""},
  {en: "sequences", hu: "szekvenciák", tags: ["tudomány", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "pathway", hu: "ösvény / út", tags: ["földrajz", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "deity", hu: "istenség", tags: ["vallás", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "divinity", hu: "isteni mivolt", tags: ["vallás", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "void", hu: "üresség", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "chaos", hu: "káosz", tags: ["veszély", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "supreme", hu: "legfőbb", tags: ["politika", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "corruption", hu: "romlás / korrupció", tags: ["politika", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "filth", hu: "mocsok / szenny", tags: ["mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "futile", hu: "hiábavaló", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "faint", hu: "halovány / erőtlen", tags: ["egészség", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "blasphemy", hu: "istenkáromlás", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "shepherd", hu: "pásztor", tags: ["állatok", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "reverently", hu: "áhítattal", tags: ["vallás", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "divine", hu: "isteni", tags: ["vallás", "mitológia"], diff: "B2", syn: "", sentence: ""},
  {en: "descent", hu: "alászállás", tags: ["utazás", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "transmigrated", hu: "átkelt más világba", tags: ["fantázia", "mitológia"], diff: "C2", syn: "", sentence: ""},
  {en: "cerebral hemorrhage", hu: "agyvérzés", tags: ["egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "deceased", hu: "elhunyt", tags: ["egészség", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "heretic", hu: "eretnek", tags: ["vallás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "divination", hu: "jóslás", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "deciphered", hu: "megfejtett", tags: ["tudomány", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "dynasty", hu: "dinasztia", tags: ["történelem", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "ritual", hu: "rituálé", tags: ["vallás", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "occult", hu: "okkult / titkos", tags: ["fantázia", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "crimson", hu: "karmazsinvörös", tags: ["kultúra", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "tarot", hu: "tarot", tags: ["fantázia", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "peer", hu: "bepillantást nyer", tags: ["kommunikáció", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "impersonate", hu: "megszemélyesít", tags: ["kommunikáció", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "tamer", hu: "idomár", tags: ["állatok", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "baboons", hu: "páviánok", tags: ["állatok"], diff: "B1", syn: "", sentence: ""},
  {en: "orthodox", hu: "ortodox / hagyományhű", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "talismans", hu: "talizmánok", tags: ["fantázia", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "celestial", hu: "égi / mennyei", tags: ["vallás", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "worthy", hu: "méltóság", tags: ["politika", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "summoned", hu: "megidézett", tags: ["fantázia", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "realm", hu: "birodalom / szféra", tags: ["fantázia", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "vigilant", hu: "éber", tags: ["nyomozás", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "trifles", hu: "csekélységek", tags: ["mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "inconvenient", hu: "kényelmetlen", tags: ["mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "codename", hu: "fedőnév", tags: ["nyomozás", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "slates", hu: "táblák", tags: ["tárgyak", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "inspector", hu: "felügyelő", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "stalked", hu: "követett / megfigyelt", tags: ["nyomozás", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "inquiry", hu: "nyomozás / érdeklődés", tags: ["nyomozás", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "psychic", hu: "pszichikai / látnoki", tags: ["fantázia", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "verification", hu: "ellenőrzés", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "anomalies", hu: "anomáliák", tags: ["tudomány", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "nighthawk", hu: "Éjszakai Sólyom", tags: ["fantázia", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "lubrication", hu: "síkosítás", tags: ["tudomány", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "projection", hu: "kivetülés", tags: ["tudomány", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "spirits", hu: "szellemek", tags: ["fantázia", "vallás"], diff: "B2", syn: "", sentence: ""},
  {en: "fury", hu: "düh / harag", tags: ["érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "carve", hu: "vés / farag", tags: ["tárgyak", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "dismay", hu: "rémület / csüggedés", tags: ["érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "decay", hu: "bomlás / enyészet", tags: ["természet", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "fragile", hu: "törékeny", tags: ["tárgyak", "egészség"], diff: "B1", syn: "", sentence: ""},
  {en: "vow", hu: "fogad / esküszik", tags: ["vallás", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "camouflage", hu: "álcázás", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "mysticism", hu: "miszticizmus", tags: ["vallás", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "mercenaries", hu: "zsoldosok", tags: ["hadászat", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "civilian staff", hu: "polgári alkalmazottak", tags: ["munka", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "colleagues", hu: "kollégák", tags: ["munka"], diff: "B1", syn: "", sentence: ""},
  {en: "sketching", hu: "vázlatkészítés", tags: ["művészet", "iskola"], diff: "B1", syn: "", sentence: ""},
  {en: "disguises", hu: "álruhák", tags: ["nyomozás", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "pioneers", hu: "úttörők", tags: ["történelem", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "myth", hu: "mítosz", tags: ["mitológia", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "existence", hu: "létezés", tags: ["tudomány", "filosz"], diff: "C1", syn: "", sentence: ""},
  {en: "phoenixes", hu: "főnixek", tags: ["mitológia", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "demonic", hu: "démoni", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "origin", hu: "eredet", tags: ["tudomány", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "concoct", hu: "kotyvaszt / kikever", tags: ["ételek", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "mystical", hu: "misztikus", tags: ["fantázia", "vallás"], diff: "B2", syn: "", sentence: ""},
  {en: "excel at", hu: "kiemelkedik vmiben", tags: ["iskola", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "self-defense", hu: "önvédelem", tags: ["hadászat", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "seer", hu: "látó / jós", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "alchemy", hu: "alkímia", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "proficient", hu: "jártas / képzett", tags: ["munka", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "decipher", hu: "megfejt", tags: ["nyomozás", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "acquired", hu: "megszerzett", tags: ["mindennapi élet", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "fascinating", hu: "lenyűgöző", tags: ["érzelmek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "pathetic", hu: "szánalmas", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "protagonist", hu: "főhős", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "passionate", hu: "szenvedélyes", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "mastering", hu: "elsajátítás", tags: ["iskola", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "digesting", hu: "emésztés", tags: ["egészség", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "symbolic", hu: "szimbolikus", tags: ["kultúra", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "concrete", hu: "konkrét", tags: ["kommunikáció", "tudomány"], diff: "B1", syn: "", sentence: ""},
  {en: "hasty", hu: "elhamarkodott", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "apprentice", hu: "tanonc", tags: ["munka", "iskola"], diff: "B1", syn: "", sentence: ""},
  {en: "marauder", hu: "martalóc", tags: ["hadászat", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "inspired", hu: "inspirált", tags: ["érzelmek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "eager for", hu: "vágyik vmire", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "potion", hu: "főzet", tags: ["fantázia", "ételek"], diff: "B1", syn: "", sentence: ""},
  {en: "ingredients", hu: "összetevők", tags: ["ételek", "fantázia"], diff: "B1", syn: "", sentence: ""},
  {en: "poisoned", hu: "mérgezett", tags: ["egészség", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "hesitate", hu: "habozik", tags: ["pszichológia", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "absorption", hu: "felszívódás", tags: ["tudomány", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "sufficient", hu: "elegendő", tags: ["mindennapi élet", "iskola"], diff: "B1", syn: "", sentence: ""},
  {en: "concentrate", hu: "koncentrál", tags: ["iskola", "pszichológia"], diff: "B1", syn: "", sentence: ""},
  {en: "spirituality", hu: "spiritualitás", tags: ["vallás", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "refrain", hu: "tartózkodik", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "scatter", hu: "szétszór", tags: ["természet", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "promising", hu: "ígéretes", tags: ["munka", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "spiritual vision", hu: "spirituális látás", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "aura", hu: "aura", tags: ["fantázia", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "emblem", hu: "jelkép", tags: ["kultúra", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "ritual magic", hu: "rituális mágia", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "deplete", hu: "kimerít", tags: ["erőforrások", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "hallucinations", hu: "hallucinációk", tags: ["egészség", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "moderation", hu: "mértékletesség", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "pendulum", hu: "inga", tags: ["tárgyak", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "dowsing rod", hu: "varázsvessző", tags: ["fantázia", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "invoices", hu: "számlák", tags: ["gazdaság", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "reimbursement", hu: "költségtérítés", tags: ["gazdaság", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "adaptable", hu: "alkalmazkodóképes", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "meditation", hu: "meditáció", tags: ["egészség", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "peculiarity", hu: "furcsaság", tags: ["pszichológia", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "curiosity", hu: "kíváncsiság", tags: ["pszichológia", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "inquire", hu: "érdeklődik", tags: ["kommunikáció", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "existences", hu: "létezők", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "poverty", hu: "szegénység", tags: ["gazdaság", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "prosperity", hu: "jólét", tags: ["gazdaság", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "whereabouts", hu: "hollét", tags: ["nyomozás", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "tycoon", hu: "iparmágnás", tags: ["gazdaság", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "kidnapped", hu: "elrabolt", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "forte", hu: "erősség", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "hostage", hu: "túsz", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "flourish", hu: "díszítés", tags: ["kultúra", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "gamblers", hu: "szerencsejátékosok", tags: ["mindennapi élet", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "contamination", hu: "szennyeződés", tags: ["egészség", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "cooperation", hu: "együttműködés", tags: ["munka", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "attracts", hu: "vonz", tags: ["pszichológia", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "likewise", hu: "hasonlóképpen", tags: ["kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "thrilled", hu: "izgatott", tags: ["érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "lease", hu: "bérleti szerződés", tags: ["gazdaság", "otthon"], diff: "B2", syn: "", sentence: ""},
  {en: "expired", hu: "lejárt", tags: ["mindennapi élet", "gazdaság"], diff: "B1", syn: "", sentence: ""},
  {en: "stingy", hu: "fukar", tags: ["pszichológia", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "intelligence", hu: "intelligencia", tags: ["pszichológia", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "decently", hu: "illendően", tags: ["kultúra", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "costly", hu: "költséges", tags: ["gazdaság", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "celebrate", hu: "ünnepel", tags: ["kultúra", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "interfered", hu: "beavatkozott", tags: ["nyomozás", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "dapper", hu: "csinos / elegáns", tags: ["mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "topaz", hu: "topáz", tags: ["tárgyak", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "amplify", hu: "felerősít", tags: ["tudomány", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "interaction", hu: "interakció", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "capture mission", hu: "elfogó küldetés", tags: ["nyomozás", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "authorized", hu: "engedélyezett", tags: ["politika", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "artifact", hu: "műtárgy", tags: ["tárgyak", "történelem"], diff: "C1", syn: "", sentence: ""},
  {en: "unique", hu: "egyedi", tags: ["mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "immense", hu: "roppant", tags: ["természet", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "destructive", hu: "pusztító", tags: ["veszély", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "gravedigger", hu: "sírásó", tags: ["munka", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "spirit medium", hu: "szellemidéző", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "capabilities", hu: "képességek", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "course of action", hu: "cselekvési terv", tags: ["munka", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "descendant", hu: "leszármazott", tags: ["történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "berserk", hu: "megvadult", tags: ["érzelmek", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "solely", hu: "kizárólag", tags: ["mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "operation", hu: "hadművelet", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "cringe", hu: "kínosan érzi magát", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "puppet", hu: "báb", tags: ["tárgyak", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "luring", hu: "csalogatás", tags: ["veszély", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "disastrous", hu: "katasztrofális", tags: ["veszély", "természet"], diff: "C1", syn: "", sentence: ""},
  {en: "consequences", hu: "következmények", tags: ["mindennapi élet", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "massacring", hu: "mészárló", tags: ["veszély", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "random", hu: "véletlenszerű", tags: ["tudomány", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "spell", hu: "varázslat", tags: ["fantázia"], diff: "B1", syn: "", sentence: ""},
  {en: "hijacks", hu: "eltérít", tags: ["veszély", "közlekedés"], diff: "C1", syn: "", sentence: ""},
  {en: "scenario", hu: "forgatókönyv", tags: ["kultúra", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "aggressive", hu: "agresszív", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "tracking", hu: "nyomkövetés", tags: ["nyomozás", "technológia"], diff: "B2", syn: "", sentence: ""},
  {en: "loyalty", hu: "hűség", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "trolling", hu: "szivatás", tags: ["kommunikáció", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "lurks", hu: "leselkedik", tags: ["veszély", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "alert", hu: "riasztás", tags: ["veszély", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "severely", hu: "súlyosan", tags: ["egészség", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "shun", hu: "elkerül", tags: ["érzelmek", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "wither", hu: "elhervad", tags: ["természet"], diff: "C1", syn: "", sentence: ""},
  {en: "substitutes", hu: "helyettesítők", tags: ["tárgyak", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "external force", hu: "külső erő", tags: ["tudomány", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "immortal", hu: "halhatatlan", tags: ["fantázia", "mitológia"], diff: "B2", syn: "", sentence: ""},
  {en: "celestial", hu: "égi", tags: ["vallás", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "feinting", hu: "cselezés", tags: ["hadászat", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "sincerity", hu: "őszinteség", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "grant", hu: "adományoz", tags: ["politika", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "consciousness", hu: "tudat", tags: ["pszichológia", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "dwell on", hu: "rágódik", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "individuals", hu: "egyének", tags: ["mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "narcissist", hu: "nárcisztikus", tags: ["pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "exceptional", hu: "kivételes", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "averted", hu: "elhárított", tags: ["veszély", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "foiled", hu: "meghiúsított", tags: ["nyomozás", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "scheme", hu: "terv / ármány", tags: ["nyomozás", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "feats", hu: "hőstettek", tags: ["történelem", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "marksmanship", hu: "lövésztudás", tags: ["hadászat", "képesség"], diff: "C2", syn: "", sentence: ""},
  {en: "forbidden", hu: "tiltott", tags: ["veszély", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "caution", hu: "óvatosság", tags: ["veszély", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "mercy", hu: "kegyelem", tags: ["vallás", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "oracle", hu: "orákulum / jós", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "defense", hu: "védekezés", tags: ["hadászat", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "sacrificial lambs", hu: "áldozati bárányok", tags: ["vallás", "állatok"], diff: "C1", syn: "", sentence: ""},
  {en: "betray", hu: "elárul", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "hindrance", hu: "akadály", tags: ["veszély", "mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "forgive", hu: "megbocsát", tags: ["érzelmek", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "advanced", hu: "haladó", tags: ["iskola", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "ritualistic", hu: "rituális / szertartásos", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "incantation", hu: "varázsige", tags: ["fantázia", "kultúra"], diff: "C2", syn: "", sentence: ""},
  {en: "taboo", hu: "tabu / tilalom", tags: ["kultúra", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "abyss", hu: "szakadék / mélység", tags: ["földrajz", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "entity", hu: "lény / entitás", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "grace", hu: "kegy / kegyelem", tags: ["vallás", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "furnish", hu: "ellát / biztosít", tags: ["otthon", "gazdaság"], diff: "C1", syn: "", sentence: ""},
  {en: "reasonable", hu: "ésszerű", tags: ["pszichológia", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "irrefutable", hu: "megcáfolhatatlan", tags: ["kommunikáció", "tudomány"], diff: "C2", syn: "", sentence: ""},
  {en: "earnest", hu: "komoly / őszinte", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "generous", hu: "nagylelkű", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "ignorance", hu: "tudatlanság", tags: ["pszichológia", "iskola"], diff: "C1", syn: "", sentence: ""},
  {en: "motto", hu: "mottó / jelmondat", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "imply", hu: "utal / sejtet", tags: ["kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "receptionist", hu: "recepciós", tags: ["munka", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "inverted", hu: "fordított", tags: ["földrajz", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "herbalist", hu: "gyógynövény-szakértő", tags: ["munka", "természet"], diff: "C1", syn: "", sentence: ""},
  {en: "receipt", hu: "blokk / nyugta", tags: ["gazdaság", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "reimbursement", hu: "költségtérítés", tags: ["gazdaság", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "orthodox", hu: "ortodox / hagyománykövető", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "intuition", hu: "megérzés", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "predicament", hu: "nehéz helyzet", tags: ["veszély", "pszichológia"], diff: "C2", syn: "", sentence: ""},
  {en: "self-suppression", hu: "önelnyomás", tags: ["pszichológia", "érzelmek"], diff: "C2", syn: "", sentence: ""},
  {en: "self-limitation", hu: "önkorlátozás", tags: ["pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "psyche", hu: "psziché / lélek", tags: ["pszichológia", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "godhood", hu: "istenség", tags: ["vallás", "mitológia"], diff: "C2", syn: "", sentence: ""},
  {en: "ascending", hu: "felemelkedés", tags: ["fantázia", "haladó"], diff: "C1", syn: "", sentence: ""},
  {en: "distorted", hu: "eltorzult", tags: ["pszichológia", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "madmen", hu: "őrültek", tags: ["pszichológia", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "catalyst", hu: "katalizátor", tags: ["tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "respectable", hu: "tiszteletreméltó", tags: ["pszichológia", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "amend", hu: "módosít", tags: ["munka", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "offerings", hu: "felajánlások", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "ruler", hu: "uralkodó", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "wields", hu: "visel / forgat", tags: ["hadászat", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "banquet", hu: "bankett", tags: ["ételek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "vivacity", hu: "elevenség", tags: ["pszichológia", "érzelmek"], diff: "C2", syn: "", sentence: ""},
  {en: "obsessed", hu: "megszállott", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "surging", hu: "hullámzó", tags: ["természet", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "amplified", hu: "felerősített", tags: ["tudomány", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "constellation", hu: "csillagkép", tags: ["tudomány", "földrajz"], diff: "B2", syn: "", sentence: ""},
  {en: "pupil-less", hu: "pupilla nélküli", tags: ["egészség", "fantázia"], diff: "C2", syn: "", sentence: ""},
  {en: "concealment", hu: "elrejtés", tags: ["nyomozás", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "contorted", hu: "eltorzult", tags: ["egészség", "érzelmek"], diff: "C2", syn: "", sentence: ""},
  {en: "overlapping", hu: "átfedésben lévő", tags: ["tudomány", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "onlooker", hu: "szemlélő", tags: ["mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "detached", hu: "távolságtartó", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "objectivity", hu: "objektivitás", tags: ["pszichológia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "equivalent", hu: "egyenértékű", tags: ["tudomány", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "symbolism", hu: "szimbolizmus", tags: ["kultúra", "művészet"], diff: "C1", syn: "", sentence: ""},
  {en: "imagery", hu: "képi világ", tags: ["kultúra", "művészet"], diff: "C1", syn: "", sentence: ""},
  {en: "royalty", hu: "királyi család", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "nobility", hu: "nemesség", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "reform", hu: "reform", tags: ["politika", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "ministers", hu: "miniszterek", tags: ["politika", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "plummet", hu: "zuhan", tags: ["közlekedés", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "destabilizing", hu: "destabilizáló", tags: ["politika", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "replacements", hu: "helyettesítők", tags: ["tárgyak", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "down payment", hu: "előleg", tags: ["gazdaság", "mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "assignment", hu: "feladat", tags: ["iskola", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "retrieve", hu: "visszaszerez", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "honorific", hu: "tiszteletet kifejező", tags: ["kultúra", "kommunikáció"], diff: "C2", syn: "", sentence: ""},
  {en: "concealed", hu: "rejtett", tags: ["nyomozás", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "horrific", hu: "borzalmas", tags: ["érzelmek", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "alert", hu: "riaszt", tags: ["veszély", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "preparations", hu: "előkészületek", tags: ["munka", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "dire", hu: "végzetes", tags: ["veszély", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "financial straits", hu: "pénzügyi nehézségek", tags: ["gazdaság", "mindennapi élet"], diff: "C2", syn: "", sentence: ""},
  {en: "occasions", hu: "alkalmak", tags: ["kultúra", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "ironclad", hu: "páncélozott", tags: ["hadászat", "közlekedés"], diff: "C1", syn: "", sentence: ""},
  {en: "voyage", hu: "utazás (hajóval)", tags: ["utazás", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "cannon", hu: "ágyú", tags: ["hadászat", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "verdict", hu: "ítélet", tags: ["nyomozás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "devout", hu: "áhítatos", tags: ["vallás", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "corruption", hu: "korrupció", tags: ["politika", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "internal strife", hu: "belső viszály", tags: ["politika", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "brutal slaughter", hu: "brutális mészárlás", tags: ["veszély", "hadászat"], diff: "C2", syn: "", sentence: ""},
  {en: "avarice", hu: "kapzsiság", tags: ["pszichológia", "gazdaság"], diff: "C2", syn: "", sentence: ""},
  {en: "barbarism", hu: "barbárság", tags: ["történelem", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "rationality", hu: "racionalitás", tags: ["pszichológia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "lanterns", hu: "lámpások", tags: ["tárgyak", "otthon"], diff: "B1", syn: "", sentence: ""},
  {en: "mast", hu: "árbóc", tags: ["tárgyak", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "calamity", hu: "katasztrófa", tags: ["veszély", "természet"], diff: "C2", syn: "", sentence: ""},
  {en: "luminescence", hu: "fénylés", tags: ["természet", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "courageously", hu: "bátran", tags: ["érzelmek", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "exploits", hu: "hőstettek", tags: ["történelem", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "escorting", hu: "kísérő", tags: ["munka", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "infected", hu: "megfertőzött", tags: ["egészség", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "culprit", hu: "tettes", tags: ["nyomozás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "overlooked", hu: "figyelmen kívül hagyott", tags: ["nyomozás", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "convict", hu: "elítél", tags: ["politika", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "conclusive", hu: "meggyőző", tags: ["tudomány", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "joint investigation", hu: "közös nyomozás", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "primordial", hu: "ősi", tags: ["történelem", "tudomány"], diff: "C2", syn: "", sentence: ""},
  {en: "successor", hu: "utód", tags: ["politika", "történelem"], diff: "C1", syn: "", sentence: ""},
  {en: "nurtured", hu: "táplált", tags: ["természet", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "propagated", hu: "terjesztett", tags: ["tudomány", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "assassin", hu: "orgyilkos", tags: ["nyomozás", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "captivating", hu: "magával ragadó", tags: ["érzelmek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "collaborator", hu: "bűntárs", tags: ["nyomozás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "amulets", hu: "amulettek", tags: ["fantázia", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "amateurs", hu: "amatőrök", tags: ["munka", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "trickle", hu: "csordogálás", tags: ["természet", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "dam", hu: "gát", tags: ["tárgyak", "természet"], diff: "B2", syn: "", sentence: ""},
  {en: "perception", hu: "érzékelés", tags: ["pszichológia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "inane babbling", hu: "üres fecsegés", tags: ["kommunikáció", "pszichológia"], diff: "C2", syn: "", sentence: ""},
  {en: "warding off", hu: "elhárítás", tags: ["veszély", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "informant", hu: "besúgó", tags: ["nyomozás", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "sly", hu: "ravasz", tags: ["pszichológia", "állatok"], diff: "B2", syn: "", sentence: ""},
  {en: "to no avail", hu: "hiába", tags: ["érzelmek", "mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "instigator", hu: "felbujtó", tags: ["nyomozás", "politika"], diff: "C2", syn: "", sentence: ""},
  {en: "rousing", hu: "serkentő", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "incite conflict", hu: "konfliktust szít", tags: ["politika", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "befell", hu: "sújtotta", tags: ["történelem", "veszély"], diff: "C2", syn: "", sentence: ""},
  {en: "objectives", hu: "célkitűzések", tags: ["munka", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "premises", hu: "helyiség", tags: ["otthon", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "vacate", hu: "kiürít", tags: ["veszély", "otthon"], diff: "C1", syn: "", sentence: ""},
  {en: "linger", hu: "időzik", tags: ["mindennapi élet", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "fivefold", hu: "ötszörös", tags: ["tudomány", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "laborers", hu: "munkások", tags: ["munka", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "vagrants", hu: "csavargók", tags: ["társadalom", "mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "contemplating", hu: "fontolgat", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "afloat", hu: "felszínen marad", tags: ["közlekedés", "gazdaság"], diff: "C1", syn: "", sentence: ""},
  {en: "conspiring", hu: "összeesküvés", tags: ["politika", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "lifespans", hu: "élettartam", tags: ["egészség", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "forcibly", hu: "erőszakosan", tags: ["veszély", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "usurpation", hu: "bitorlás", tags: ["politika", "történelem"], diff: "C2", syn: "", sentence: ""},
  {en: "consensus", hu: "konszenzus", tags: ["kommunikáció", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "protagonists", hu: "főszereplők", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "intervention", hu: "beavatkozás", tags: ["egészség", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "interpretation", hu: "értelmezés", tags: ["pszichológia", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "plagued", hu: "gyötört", tags: ["egészség", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "nightmares", hu: "rémálmok", tags: ["egészség", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "abandoned", hu: "elhagyatott", tags: ["földrajz", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "wraith", hu: "kísértet", tags: ["fantázia", "veszély"], diff: "C2", syn: "", sentence: ""},
  {en: "disrupt", hu: "megzavar", tags: ["veszély", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "abnormally", hu: "rendellenesen", tags: ["tudomány", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "mutated", hu: "mutálódott", tags: ["tudomány", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "emblem", hu: "jelkép", tags: ["kultúra", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "disperse", hu: "szétoszlik", tags: ["természet", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "requiem", hu: "gyászmise", tags: ["vallás", "kultúra"], diff: "C2", syn: "", sentence: ""},
  {en: "charm", hu: "talizmán", tags: ["fantázia", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "eerie", hu: "hátborzongató", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "attachment", hu: "ragaszkodás", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "centuries", hu: "évszázadok", tags: ["történelem"], diff: "B1", syn: "", sentence: ""},
  {en: "epoch", hu: "korszak", tags: ["történelem", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "baronet", hu: "bárói cím", tags: ["politika", "történelem"], diff: "C2", syn: "", sentence: ""},
  {en: "vanished", hu: "eltűnt", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "resemblance", hu: "hasonlóság", tags: ["pszichológia", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "mild-mannered", hu: "szelíd modorú", tags: ["pszichológia", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "purified", hu: "megtisztított", tags: ["vallás", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "shifts", hu: "műszakok", tags: ["munka"], diff: "B2", syn: "", sentence: ""},
  {en: "archives", hu: "archívum", tags: ["történelem", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "interference", hu: "zavarás", tags: ["kommunikáció", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "manifested", hu: "megnyilvánult", tags: ["tudomány", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "blazing", hu: "lángoló", tags: ["természet", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "shielded", hu: "megvédett", tags: ["hadászat", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "recipe", hu: "recept", tags: ["ételek", "fantázia"], diff: "B1", syn: "", sentence: ""},
  {en: "exploit", hu: "kihasznál", tags: ["munka", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "ordinary", hu: "átlagos", tags: ["mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "resolved", hu: "megoldódott", tags: ["munka", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "cataclysm", hu: "kataklizma", tags: ["veszély", "történelem"], diff: "C2", syn: "", sentence: ""},
  {en: "magnificent", hu: "pompás", tags: ["kultúra", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "throne", hu: "trón", tags: ["politika", "tárgyak"], diff: "B2", syn: "", sentence: ""},
  {en: "spans", hu: "átível", tags: ["földrajz", "történelem"], diff: "C1", syn: "", sentence: ""},
  {en: "ruins", hu: "romok", tags: ["történelem", "földrajz"], diff: "B2", syn: "", sentence: ""},
  {en: "tentatively", hu: "kísérleti jelleggel", tags: ["tudomány", "munka"], diff: "C2", syn: "", sentence: ""},
  {en: "furnishings", hu: "bútorzat", tags: ["otthon", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "preserved", hu: "megőrzött", tags: ["történelem", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "entombment", hu: "sírba helyezés", tags: ["vallás", "kultúra"], diff: "C2", syn: "", sentence: ""},
  {en: "civilization", hu: "civilizáció", tags: ["történelem", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "worshipped", hu: "imádott", tags: ["vallás", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "mysterious", hu: "rejtélyes", tags: ["nyomozás", "fantázia"], diff: "B1", syn: "", sentence: ""},
  {en: "erratic", hu: "kiszámíthatatlan", tags: ["pszichológia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "whiff", hu: "fuvallat", tags: ["természet", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "insight", hu: "bepillantás", tags: ["pszichológia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "implicitly", hu: "burkoltan", tags: ["kommunikáció", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "agitated", hu: "felizgatott", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "steed", hu: "paripa", tags: ["állatok", "utazás"], diff: "C1", syn: "", sentence: ""},
  {en: "foul", hu: "undorító", tags: ["érzelmek", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "humid", hu: "párás", tags: ["természet", "földrajz"], diff: "B2", syn: "", sentence: ""},
  {en: "suppressed", hu: "elnyomott", tags: ["pszichológia", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "sealing", hu: "lezárás", tags: ["fantázia", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "suffering", hu: "szenvedés", tags: ["egészség", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "disaster", hu: "katasztrófa", tags: ["veszély", "természet"], diff: "B1", syn: "", sentence: ""},
  {en: "valiantly", hu: "hősiesen", tags: ["hadászat", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "dubbed", hu: "elnevezett", tags: ["kommunikáció", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "bestow", hu: "adományoz", tags: ["politika", "vallás"], diff: "C2", syn: "", sentence: ""},
  {en: "fief", hu: "hűbérbirtok", tags: ["történelem", "földrajz"], diff: "C2", syn: "", sentence: ""},
  {en: "confer", hu: "ráruház", tags: ["politika", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "departure", hu: "távozás", tags: ["utazás", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "spare", hu: "megkímél", tags: ["érzelmek", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "tenfold", hu: "tízszeres", tags: ["tudomány", "gazdaság"], diff: "C1", syn: "", sentence: ""},
  {en: "bloodline", hu: "vérvonal", tags: ["történelem", "család"], diff: "C1", syn: "", sentence: ""},
  {en: "untraceable", hu: "lenyomozhatatlan", tags: ["nyomozás", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "recovered", hu: "felépült", tags: ["egészség", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "reawaken", hu: "újraébred", tags: ["pszichológia", "természet"], diff: "C1", syn: "", sentence: ""},
  {en: "identification", hu: "azonosító", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "crafted", hu: "megmunkált", tags: ["tárgyak", "művészet"], diff: "B2", syn: "", sentence: ""},
  {en: "feudal lord", hu: "hűbérúr", tags: ["történelem", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "solitude", hu: "magány", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "reincarnations", hu: "reinkarnációk", tags: ["fantázia", "vallás"], diff: "C2", syn: "", sentence: ""},
  {en: "seeped", hu: "beszivárgott", tags: ["természet", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "fleeting", hu: "múló", tags: ["érzelmek", "természet"], diff: "C1", syn: "", sentence: ""},
  {en: "endures", hu: "kitart", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "adrift", hu: "sodródó", tags: ["utazás", "közlekedés"], diff: "C1", syn: "", sentence: ""},
  {en: "shoreline", hu: "partvonal", tags: ["földrajz", "természet"], diff: "B2", syn: "", sentence: ""},
  {en: "heading", hu: "irány", tags: ["közlekedés", "utazás"], diff: "B1", syn: "", sentence: ""},
  {en: "empathize", hu: "együttérez", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "harbor", hu: "menedék", tags: ["érzelmek", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "determined", hu: "elszánt", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "cherish", hu: "dédelget", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "reminisce", hu: "nosztalgiázik", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "coincidences", hu: "véletlenek", tags: ["tudomány", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "clue", hu: "nyom", tags: ["nyomozás"], diff: "B1", syn: "", sentence: ""},
  {en: "engaged", hu: "eljegyzett", tags: ["érzelmek", "család"], diff: "B1", syn: "", sentence: ""},
  {en: "romance", hu: "románc", tags: ["érzelmek", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "demon hunter", hu: "démonvadász", tags: ["fantázia", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "ravishing", hu: "elragadó", tags: ["érzelmek", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "tragic", hu: "tragikus", tags: ["érzelmek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "patrols", hu: "járőrök", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "cemetery", hu: "temető", tags: ["vallás", "földrajz"], diff: "B1", syn: "", sentence: ""},
  {en: "assign", hu: "kijelöl", tags: ["munka", "iskola"], diff: "B1", syn: "", sentence: ""},
  {en: "intertwine", hu: "összefonódik", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "distinguish", hu: "megkülönböztet", tags: ["iskola", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "relieve", hu: "levált", tags: ["munka", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "performance review", hu: "teljesítményértékelés", tags: ["munka", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "cathedral", hu: "katedrális", tags: ["vallás", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "grave", hu: "súlyos", tags: ["veszély", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "watchman", hu: "őr", tags: ["munka", "nyomozás"], diff: "B1", syn: "", sentence: ""},
  {en: "dioceses", hu: "egyházmegyék", tags: ["vallás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "tragedies", hu: "tragédiák", tags: ["kultúra", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "perished", hu: "elpusztult", tags: ["veszély", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "forsake", hu: "elhagy", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "bestowed", hu: "adományozott", tags: ["politika", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "constipation", hu: "székrekedés", tags: ["egészség"], diff: "B1", syn: "", sentence: ""},
  {en: "abnormalities", hu: "rendellenességek", tags: ["egészség", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "recital", hu: "előadás", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "trustworthy", hu: "megbízható", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "companion", hu: "társ", tags: ["érzelmek", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "traits", hu: "jellemvonások", tags: ["pszichológia", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "lure", hu: "csalogat", tags: ["veszély", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "reckless", hu: "meggondolatlan", tags: ["veszély", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "subsequent", hu: "későbbi", tags: ["történelem", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "severed", hu: "elvágott", tags: ["veszély", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "appraised", hu: "felbecsült", tags: ["gazdaság", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "resurgence", hu: "újjáéledés", tags: ["történelem", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "annihilation", hu: "megsemmisülés", tags: ["veszély", "hadászat"], diff: "C2", syn: "", sentence: ""},
  {en: "sacrificial", hu: "áldozati", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "insignificant", hu: "jelentéktelen", tags: ["pszichológia", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "entanglement", hu: "kuszaság", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "naive", hu: "naiv", tags: ["pszichológia", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "principle", hu: "alapelv", tags: ["iskola", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "reigns", hu: "uralkodik", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "degenerate", hu: "elfajult", tags: ["pszichológia", "történelem"], diff: "C1", syn: "", sentence: ""},
  {en: "acolytes", hu: "ministránsok", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "vertical pupil", hu: "függőleges pupilla", tags: ["állatok", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "leads", hu: "nyomok", tags: ["nyomozás"], diff: "B1", syn: "", sentence: ""},
  {en: "advantageous", hu: "előnyös", tags: ["gazdaság", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "trump card", hu: "aduász", tags: ["kultúra", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "exhausted", hu: "kimerült", tags: ["egészség", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "fixated", hu: "megszállott", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "turning point", hu: "fordulópont", tags: ["történelem", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "apologies", hu: "bocsánatkérés", tags: ["kommunikáció", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "locate", hu: "bemér / megtalál", tags: ["nyomozás", "közlekedés"], diff: "B2", syn: "", sentence: ""},
  {en: "obtaining", hu: "megszerzés", tags: ["gazdaság", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "honorable", hu: "tiszteletreméltó", tags: ["kultúra", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "hidden", hu: "rejtett", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "iceberg", hu: "jéghegy", tags: ["természet", "földrajz"], diff: "B1", syn: "", sentence: ""},
  {en: "troublesome", hu: "problémás", tags: ["pszichológia", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "non-consecutive", hu: "nem egymást követő", tags: ["iskola", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "banknotes", hu: "bankjegyek", tags: ["gazdaság", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "mansion", hu: "kastély", tags: ["otthon", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "noble", hu: "nemes", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "recipient", hu: "címzett", tags: ["kommunikáció", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "loaded", hu: "gazdag", tags: ["gazdaság", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "composure", hu: "higgadtság", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "considerable", hu: "jelentős", tags: ["gazdaság", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "influence", hu: "befolyás", tags: ["politika", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "ancient", hu: "ősi", tags: ["történelem", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "sect", hu: "szekta", tags: ["vallás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "ascetic", hu: "aszkéta", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "pryer", hu: "kíváncsiskodó", tags: ["pszichológia", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "sage", hu: "bölcs", tags: ["kultúra", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "personification", hu: "megszemélyesítés", tags: ["kultúra", "művészet"], diff: "C1", syn: "", sentence: ""},
  {en: "numinous", hu: "természetfeletti", tags: ["fantázia", "vallás"], diff: "C2", syn: "", sentence: ""},
  {en: "episcopate", hu: "püspökség", tags: ["vallás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "paranormal", hu: "paranormális", tags: ["fantázia", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "consultant", hu: "tanácsadó", tags: ["munka", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "standard issue", hu: "rendszeresített felszerelés", tags: ["hadászat", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "chipper", hu: "jókedvű", tags: ["érzelmek", "pszichológia"], diff: "B1", syn: "", sentence: ""},
  {en: "casualties", hu: "áldozatok", tags: ["veszély", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "targeted", hu: "célzott", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "mandated", hu: "megbízott", tags: ["politika", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "punishers", hu: "büntetők", tags: ["politika", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "tab", hu: "számla", tags: ["gazdaság", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "choking", hu: "fuldoklás", tags: ["egészség", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "accursed", hu: "átkozott", tags: ["fantázia", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "hauntings", hu: "kísértetjárások", tags: ["fantázia", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "apenty", hu: "bőséggel", tags: ["mindennapi élet", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "preliminary", hu: "előzetes", tags: ["munka", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "investigations", hu: "vizsgálatok", tags: ["nyomozás", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "jurisdiction", hu: "joghatóság", tags: ["politika", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "expel", hu: "kiűz", tags: ["politika", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "jovial", hu: "derűs", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "straight-shooter", hu: "őszinte ember", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "intrusion", hu: "behatolás", tags: ["veszély", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "suspicious", hu: "gyanús", tags: ["nyomozás", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "green", hu: "tapasztalatlan", tags: ["iskola", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "subsidy", hu: "támogatás", tags: ["gazdaság", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "impulsively", hu: "impulzívan", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "contain", hu: "feltartóztat", tags: ["veszély", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "reputation", hu: "hírnév", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "unrealistic", hu: "irreális", tags: ["pszichológia", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "fantasies", hu: "fantáziák", tags: ["fantázia", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "sergeant", hu: "őrmester", tags: ["hadászat", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "overseeing", hu: "felügyelő", tags: ["munka", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "severe", hu: "súlyos", tags: ["egészség", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "exorcism", hu: "ördögűzés", tags: ["vallás", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "politicians", hu: "politikusok", tags: ["politika", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "wet behind the ears", hu: "zöldfülű", tags: ["iskola", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "worth his salt", hu: "ért a dolgához", tags: ["munka", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "assured", hu: "biztosított", tags: ["gazdaság", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "professionals", hu: "szakemberek", tags: ["munka", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "guru", hu: "mester", tags: ["kultúra", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "substance", hu: "lényeg", tags: ["tudomány", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "ado", hu: "felhajtás", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "reinforcements", hu: "erősítés", tags: ["hadászat", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "authentic", hu: "hiteles", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "possessed", hu: "megszállt", tags: ["fantázia", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "activating", hu: "aktiválódik", tags: ["tudomány", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "episode", hu: "epizód", tags: ["kultúra", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "cleansing", hu: "megtisztítás", tags: ["vallás", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "newcomer", hu: "újonc", tags: ["munka", "iskola"], diff: "B1", syn: "", sentence: ""},
  {en: "cosmos", hu: "kozmosz", tags: ["tudomány", "fantázia"], diff: "B2", syn: "", sentence: ""},
  {en: "eternal", hu: "örök", tags: ["vallás", "mitológia"], diff: "B2", syn: "", sentence: ""},
  {en: "eternity", hu: "örökkévalóság", tags: ["vallás", "mitológia"], diff: "B2", syn: "", sentence: ""},
  {en: "empress", hu: "császárnő", tags: ["politika", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "repose", hu: "nyugalom", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "pray", hu: "imádkozik", tags: ["vallás", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "frame of mind", hu: "lelkiállapot", tags: ["pszichológia", "érzelmek"], diff: "C1", syn: "", sentence: ""},
  {en: "urgent", hu: "sürgős", tags: ["veszély", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "dillydallying", hu: "késlekedés", tags: ["pszichológia", "mindennapi élet"], diff: "C1", syn: "", sentence: ""},
  {en: "fiancé", hu: "vőlegény", tags: ["család", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "scam", hu: "átverés", tags: ["nyomozás", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "involvement", hu: "érintettség", tags: ["politika", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "fraud", hu: "csalás", tags: ["nyomozás", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "familiarity", hu: "jártasság", tags: ["iskola", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "downtime", hu: "pihenőidő", tags: ["munka", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "mausoleums", hu: "mauzóleumok", tags: ["vallás", "történelem"], diff: "C1", syn: "", sentence: ""},
  {en: "wary", hu: "óvatos", tags: ["pszichológia", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "theft", hu: "lopás", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "procedure", hu: "eljárás", tags: ["munka", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "domain", hu: "birodalom", tags: ["fantázia", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "inextinguishable", hu: "kiolthatatlan", tags: ["fantázia", "veszély"], diff: "C2", syn: "", sentence: ""},
  {en: "embodiment", hu: "megtestesülés", tags: ["fantázia", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "deeds", hu: "tettek", tags: ["történelem", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "guardian", hu: "őrző", tags: ["fantázia", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "prior", hu: "korábbi", tags: ["kommunikáció", "történelem"], diff: "B1", syn: "", sentence: ""},
  {en: "perimeter", hu: "kerület", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "notify", hu: "értesít", tags: ["kommunikáció", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "encompassed", hu: "magába foglalt", tags: ["tudomány", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "boorish", hu: "faragatlan", tags: ["pszichológia", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "manner", hu: "modor", tags: ["pszichológia", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "emergency", hu: "vészhelyzet", tags: ["veszély", "egészség"], diff: "B1", syn: "", sentence: ""},
  {en: "advancement", hu: "előrehaladás", tags: ["munka", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "doubt", hu: "kétség", tags: ["pszichológia", "érzelmek"], diff: "B1", syn: "", sentence: ""},
  {en: "tribunal", hu: "törvényszék", tags: ["politika", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "displeasing", hu: "kellemetlen", tags: ["érzelmek", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "presume", hu: "feltételez", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "revelation", hu: "kinyilatkoztatás", tags: ["vallás", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "conceal", hu: "elrejt", tags: ["nyomozás", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "deliberately", hu: "szándékosan", tags: ["pszichológia", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "broach", hu: "felhoz (témát)", tags: ["kommunikáció", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "grasped", hu: "megértett", tags: ["iskola", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "stumble on", hu: "rábukkan", tags: ["nyomozás", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "notary", hu: "közjegyző", tags: ["politika", "munka"], diff: "B1", syn: "", sentence: ""},
  {en: "weirdo", hu: "fura alak", tags: ["pszichológia", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "genius", hu: "zseni", tags: ["iskola", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "exceptionally", hu: "kivételesen", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "regard", hu: "tisztelet", tags: ["érzelmek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "representative", hu: "képviselő", tags: ["politika", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "unbelievable", hu: "hihetetlen", tags: ["érzelmek", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "principles", hu: "alapelvek", tags: ["iskola", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "maxim", hu: "vezérelv", tags: ["kultúra", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "namesake", hu: "névrokon", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "deacon", hu: "diakónus", tags: ["vallás", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "authoritative", hu: "tekintélyes", tags: ["politika", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "elite squad", hu: "elit osztag", tags: ["hadászat", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "acknowledgment", hu: "elismerés", tags: ["kommunikáció", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "demigod", hu: "félisten", tags: ["mitológia", "fantázia"], diff: "C1", syn: "", sentence: ""},
  {en: "assessing", hu: "értékelés", tags: ["munka", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "interrogation", hu: "kihallgatás", tags: ["nyomozás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "comrades", hu: "bajtársak", tags: ["hadászat", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "murmurs", hu: "mormogás", tags: ["kommunikáció", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "tempted", hu: "kísértve volt", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "outstandingly", hu: "kiemelkedően", tags: ["munka", "iskola"], diff: "C1", syn: "", sentence: ""},
  {en: "restraints", hu: "korlátozások", tags: ["politika", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "treatment", hu: "kezelés", tags: ["egészség", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "recite", hu: "szaval", tags: ["kultúra", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "oath", hu: "eskü", tags: ["vallás", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "pledge", hu: "fogadalom", tags: ["vallás", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "deem fit", hu: "megfelelőnek ítél", tags: ["kommunikáció", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "brew", hu: "főz (italt)", tags: ["ételek", "fantázia"], diff: "B1", syn: "", sentence: ""},
  {en: "mature", hu: "érett", tags: ["pszichológia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "professional", hu: "profi", tags: ["munka", "gazdaság"], diff: "B2", syn: "", sentence: ""},
  {en: "malice", hu: "rosszindulat", tags: ["érzelmek", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "tainted", hu: "beszennyezett", tags: ["egészség", "veszély"], diff: "C1", syn: "", sentence: ""},
  {en: "agility", hu: "mozgékonyság", tags: ["egészség", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "precognition", hu: "előérzet", tags: ["fantázia", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "locked", hu: "zárolt", tags: ["tárgyak", "nyomozás"], diff: "B1", syn: "", sentence: ""},
  {en: "tarot cards", hu: "tarot kártyák", tags: ["fantázia", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "miss the mark", hu: "célt téveszt", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "regrets", hu: "megbánás", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "palate", hu: "ízlés", tags: ["ételek", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "settled", hu: "elrendeződött", tags: ["érzelmek", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "asceticism", hu: "aszkézis", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "commandments", hu: "parancsolatok", tags: ["vallás", "kultúra"], diff: "B2", syn: "", sentence: ""},
  {en: "ascetics", hu: "aszkéták", tags: ["vallás", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "tranquility", hu: "nyugalom", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "husk", hu: "héj", tags: ["tárgyak", "természet"], diff: "B1", syn: "", sentence: ""},
  {en: "wretches", hu: "szerencsétlenek", tags: ["pszichológia", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "accompany", hu: "elkísér", tags: ["utazás", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "resurrect", hu: "feltámaszt", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "alchemical", hu: "alkímiai", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "serenity", hu: "derű", tags: ["érzelmek", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "expenses", hu: "kiadások", tags: ["gazdaság", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "receipts", hu: "nyugták", tags: ["gazdaság", "mindennapi élet"], diff: "B1", syn: "", sentence: ""},
  {en: "fantastic", hu: "fantasztikus", tags: ["érzelmek", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "organisms", hu: "élőlények", tags: ["tudomány", "természet"], diff: "B2", syn: "", sentence: ""},
  {en: "association", hu: "egyesület", tags: ["politika", "társadalom"], diff: "B2", syn: "", sentence: ""},
  {en: "mausoleum", hu: "mauzóleum", tags: ["vallás", "történelem"], diff: "B2", syn: "", sentence: ""},
  {en: "mastermind", hu: "lángelme", tags: ["pszichológia", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "archbishop", hu: "érsek", tags: ["vallás", "politika"], diff: "B2", syn: "", sentence: ""},
  {en: "fled", hu: "elmenekült", tags: ["veszély", "nyomozás"], diff: "B2", syn: "", sentence: ""},
  {en: "classification", hu: "besorolás", tags: ["tudomány", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "probed", hu: "vizsgált", tags: ["tudomány", "nyomozás"], diff: "C1", syn: "", sentence: ""},
  {en: "quill", hu: "írótoll", tags: ["tárgyak", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "concealable", hu: "elrejthető", tags: ["nyomozás", "tárgyak"], diff: "C1", syn: "", sentence: ""},
  {en: "resemble", hu: "hasonlít", tags: ["pszichológia", "kommunikáció"], diff: "B1", syn: "", sentence: ""},
  {en: "fatal", hu: "végzetes", tags: ["veszély", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "counterattack", hu: "ellentámadás", tags: ["hadászat", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "combat techniques", hu: "harci technikák", tags: ["hadászat", "iskola"], diff: "C1", syn: "", sentence: ""},
  {en: "spirit guide", hu: "szellemvezető", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "full-fledged", hu: "teljes jogú", tags: ["politika", "munka"], diff: "C1", syn: "", sentence: ""},
  {en: "accounting", hu: "könyvelés", tags: ["gazdaság", "munka"], diff: "B2", syn: "", sentence: ""},
  {en: "logic", hu: "logika", tags: ["tudomány", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "relevant", hu: "releváns", tags: ["kommunikáció", "iskola"], diff: "B2", syn: "", sentence: ""},
  {en: "sleep-inducing", hu: "altató hatású", tags: ["egészség", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "brass", hu: "sárgaréz", tags: ["tárgyak", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "whistle", hu: "síp", tags: ["tárgyak", "közlekedés"], diff: "B1", syn: "", sentence: ""},
  {en: "messenger", hu: "hírnök", tags: ["kommunikáció", "történelem"], diff: "B1", syn: "", sentence: ""},
  {en: "mighty", hu: "hatalmas", tags: ["fantázia", "érzelmek"], diff: "B2", syn: "", sentence: ""},
  {en: "ulted", hu: "ulti-t használt", tags: ["fantázia", "kultúra"], diff: "C2", syn: "", sentence: ""},
  {en: "auto-attack", hu: "alaptámadás", tags: ["fantázia", "hadászat"], diff: "C1", syn: "", sentence: ""},
  {en: "spirit medium", hu: "szellemidéző", tags: ["fantázia", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "subconscious", hu: "tudatalatti", tags: ["pszichológia", "egészség"], diff: "C1", syn: "", sentence: ""},
  {en: "preexisting", hu: "már meglévő", tags: ["tudomány", "kommunikáció"], diff: "B2", syn: "", sentence: ""},
  {en: "unprotected", hu: "védtelen", tags: ["veszély", "egészség"], diff: "B2", syn: "", sentence: ""},
  {en: "interrupting", hu: "félbeszakítás", tags: ["kommunikáció", "pszichológia"], diff: "B2", syn: "", sentence: ""},
  {en: "asylum", hu: "elmegyógyintézet", tags: ["egészség", "társadalom"], diff: "C1", syn: "", sentence: ""},
  {en: "psychiatrist", hu: "pszichiáter", tags: ["egészség", "pszichológia"], diff: "C1", syn: "", sentence: ""},
  {en: "disguised", hu: "álcázott", tags: ["nyomozás", "mindennapi élet"], diff: "B2", syn: "", sentence: ""},
  {en: "chaotic", hu: "kaotikus", tags: ["pszichológia", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "interrogate", hu: "kihallgat", tags: ["nyomozás", "politika"], diff: "C1", syn: "", sentence: ""},
  {en: "defenses", hu: "védekezés", tags: ["hadászat", "veszély"], diff: "B2", syn: "", sentence: ""},
  {en: "upset", hu: "feldúlt", tags: ["érzelmek", "pszichológia"], diff: "B1", syn: "", sentence: ""},
  {en: "converge", hu: "összefut", tags: ["tudomány", "kommunikáció"], diff: "C1", syn: "", sentence: ""},
  {en: "fragments", hu: "töredékek", tags: ["tárgyak", "tudomány"], diff: "B2", syn: "", sentence: ""},
  {en: "philandering", hu: "nőcsábászat", tags: ["pszichológia", "kultúra"], diff: "C1", syn: "", sentence: ""},
  {en: "alchemists", hu: "alkimisták", tags: ["fantázia", "tudomány"], diff: "C1", syn: "", sentence: ""},
  {en: "seize", hu: "megragad", tags: ["nyomozás", "hadászat"], diff: "B2", syn: "", sentence: ""},
  {en: "immortals", hu: "halhatatlanok", tags: ["fantázia", "mitológia"], diff: "C1", syn: "", sentence: ""},
  {en: "altar", hu: "oltár", tags: ["vallás", "kultúra"], diff: "B1", syn: "", sentence: ""},
  {en: "transgression", hu: "vétség", tags: ["politika", "vallás"], diff: "C1", syn: "", sentence: ""},
  {en: "alias", hu: "álnév", tags: ["nyomozás", "kommunikáció"], diff: "B2", syn: "", sentence: ""}
];

console.log("[LexiLearn] A data.js fájl sikeresen betöltötte a teljes személyes szótárad!");