/* ══════════════════════════════════════════════════════
   LexiLearn – JLPT N3 szókincs (V13.7)
   Minden szó: kana, kanji (írásmód), romaji, hu (magyar), tags, jlpt
   A kana az azonosító: nem ütközhet a japanese_words.js / dekiru.js szavaival
   (a tests/data.test.js ellenőrzi, a romaji-kana egyezéssel együtt).
   1. adag: gyakori N3 igék, melléknevek, főnevek és határozószók.
══════════════════════════════════════════════════════ */
const N3_WORDS = [
  // ─── N3 – Igék: érzelmek, gondolkodás ─────────────
  { kana: 'あきらめる', kanji: '諦める', romaji: 'akirameru', hu: 'feladja, lemond (valamiről)', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'あきれる', kanji: '呆れる', romaji: 'akireru', hu: 'elképed, megdöbben', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'いのる', kanji: '祈る', romaji: 'inoru', hu: 'imádkozik; kíván (valakinek valamit)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'うたがう', kanji: '疑う', romaji: 'utagau', hu: 'kételkedik, gyanakszik', tags: ['igék','gondolkodás'], jlpt: 'N3' },
  { kana: 'うらやむ', kanji: '羨む', romaji: 'urayamu', hu: 'irigyel', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'おそれる', kanji: '恐れる', romaji: 'osoreru', hu: 'fél (valamitől)', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'おちつく', kanji: '落ち着く', romaji: 'ochitsuku', hu: 'megnyugszik, lecsillapodik', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'きらう', kanji: '嫌う', romaji: 'kirau', hu: 'utál, nem kedvel', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'くやむ', kanji: '悔やむ', romaji: 'kuyamu', hu: 'bán, megbán', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'なぐさめる', kanji: '慰める', romaji: 'nagusameru', hu: 'vigasztal', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'にくむ', kanji: '憎む', romaji: 'nikumu', hu: 'gyűlöl', tags: ['igék','érzelmek'], jlpt: 'N3' },
  { kana: 'はげます', kanji: '励ます', romaji: 'hagemasu', hu: 'bátorít, lelkesít', tags: ['igék','kapcsolatok'], jlpt: 'N3' },
  { kana: 'みとめる', kanji: '認める', romaji: 'mitomeru', hu: 'elismer, beismer', tags: ['igék','gondolkodás'], jlpt: 'N3' },
  { kana: 'めざす', kanji: '目指す', romaji: 'mezasu', hu: 'céloz, törekszik (valamire)', tags: ['igék','gondolkodás'], jlpt: 'N3' },
  { kana: 'ゆるす', kanji: '許す', romaji: 'yurusu', hu: 'megbocsát; megenged', tags: ['igék','kapcsolatok'], jlpt: 'N3' },
  { kana: 'わびる', kanji: '詫びる', romaji: 'wabiru', hu: 'bocsánatot kér', tags: ['igék','udvariasság'], jlpt: 'N3' },
  { kana: 'ちかう', kanji: '誓う', romaji: 'chikau', hu: 'megesküszik, fogadalmat tesz', tags: ['igék'], jlpt: 'N3' },
  { kana: 'さからう', kanji: '逆らう', romaji: 'sakarau', hu: 'ellenszegül, dacol', tags: ['igék','kapcsolatok'], jlpt: 'N3' },
  { kana: 'したがう', kanji: '従う', romaji: 'shitagau', hu: 'követ, engedelmeskedik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'まかせる', kanji: '任せる', romaji: 'makaseru', hu: 'rábíz', tags: ['igék','munka'], jlpt: 'N3' },
  { kana: 'さそう', kanji: '誘う', romaji: 'sasou', hu: 'hív, meghív (programra)', tags: ['igék','kapcsolatok'], jlpt: 'N3' },
  { kana: 'さけぶ', kanji: '叫ぶ', romaji: 'sakebu', hu: 'kiabál, kiált', tags: ['igék','kommunikáció'], jlpt: 'N3' },
  { kana: 'あらわす', kanji: '表す', romaji: 'arawasu', hu: 'kifejez, kimutat', tags: ['igék','kommunikáció'], jlpt: 'N3' },
  { kana: 'しめす', kanji: '示す', romaji: 'shimesu', hu: 'megmutat, jelez', tags: ['igék','kommunikáció'], jlpt: 'N3' },

  // ─── N3 – Igék: mozgás, változás ──────────────────
  { kana: 'あらわれる', kanji: '現れる', romaji: 'arawareru', hu: 'megjelenik, feltűnik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'うかぶ', kanji: '浮かぶ', romaji: 'ukabu', hu: 'lebeg, úszik (a felszínen); eszébe jut', tags: ['igék'], jlpt: 'N3' },
  { kana: 'しずむ', kanji: '沈む', romaji: 'shizumu', hu: 'elsüllyed; (a nap) lemegy', tags: ['igék','természet'], jlpt: 'N3' },
  { kana: 'かたむく', kanji: '傾く', romaji: 'katamuku', hu: 'megdől, hajlik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'くずれる', kanji: '崩れる', romaji: 'kuzureru', hu: 'összeomlik, leomlik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ながれる', kanji: '流れる', romaji: 'nagareru', hu: 'folyik, áramlik', tags: ['igék','természet'], jlpt: 'N3' },
  { kana: 'ながす', kanji: '流す', romaji: 'nagasu', hu: 'folyat, leöblít', tags: ['igék'], jlpt: 'N3' },
  { kana: 'あふれる', kanji: '溢れる', romaji: 'afureru', hu: 'túlcsordul, kiárad', tags: ['igék','természet'], jlpt: 'N3' },
  { kana: 'こおる', kanji: '凍る', romaji: 'kooru', hu: 'megfagy', tags: ['igék','időjárás'], jlpt: 'N3' },
  { kana: 'つもる', kanji: '積もる', romaji: 'tsumoru', hu: 'felhalmozódik (pl. hó)', tags: ['igék','időjárás'], jlpt: 'N3' },
  { kana: 'ちぢむ', kanji: '縮む', romaji: 'chijimu', hu: 'összemegy, zsugorodik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'のびる', kanji: '伸びる', romaji: 'nobiru', hu: 'nyúlik, nő', tags: ['igék'], jlpt: 'N3' },
  { kana: 'のばす', kanji: '伸ばす', romaji: 'nobasu', hu: 'megnyújt, növeszt', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ふるえる', kanji: '震える', romaji: 'furueru', hu: 'remeg, reszket', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ふりむく', kanji: '振り向く', romaji: 'furimuku', hu: 'hátrafordul', tags: ['igék'], jlpt: 'N3' },
  { kana: 'たまる', kanji: '溜まる', romaji: 'tamaru', hu: 'felgyülemlik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'たすかる', kanji: '助かる', romaji: 'tasukaru', hu: 'megmenekül; nagy segítség (nekem)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ちらかる', kanji: '散らかる', romaji: 'chirakaru', hu: 'rendetlenség lesz, szanaszét hever', tags: ['igék','mindennapi élet'], jlpt: 'N3' },
  { kana: 'ずれる', romaji: 'zureru', hu: 'elcsúszik, eltér', tags: ['igék'], jlpt: 'N3' },
  { kana: 'はずれる', kanji: '外れる', romaji: 'hazureru', hu: 'leválik; nem talál (célt)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'はなれる', kanji: '離れる', romaji: 'hanareru', hu: 'eltávolodik, elválik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'わかれる', kanji: '別れる', romaji: 'wakareru', hu: 'elválik, szakít', tags: ['igék','kapcsolatok'], jlpt: 'N3' },
  { kana: 'こえる', kanji: '越える', romaji: 'koeru', hu: 'átkel, túllép', tags: ['igék'], jlpt: 'N3' },
  { kana: 'おいつく', kanji: '追いつく', romaji: 'oitsuku', hu: 'utolér', tags: ['igék'], jlpt: 'N3' },
  { kana: 'おいかける', kanji: '追いかける', romaji: 'oikakeru', hu: 'üldöz, utána fut', tags: ['igék'], jlpt: 'N3' },
  { kana: 'かくれる', kanji: '隠れる', romaji: 'kakureru', hu: 'elbújik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'おぼれる', kanji: '溺れる', romaji: 'oboreru', hu: 'fuldoklik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'つまずく', kanji: '躓く', romaji: 'tsumazuku', hu: 'megbotlik', tags: ['igék'], jlpt: 'N3' },
  { kana: 'あまる', kanji: '余る', romaji: 'amaru', hu: 'megmarad, fölösleg van', tags: ['igék'], jlpt: 'N3' },

  // ─── N3 – Igék: cselekvés tárgyakkal ──────────────
  { kana: 'あわせる', kanji: '合わせる', romaji: 'awaseru', hu: 'összeilleszt, egyeztet', tags: ['igék'], jlpt: 'N3' },
  { kana: 'うしなう', kanji: '失う', romaji: 'ushinau', hu: 'elveszít', tags: ['igék'], jlpt: 'N3' },
  { kana: 'うばう', kanji: '奪う', romaji: 'ubau', hu: 'elrabol, elvesz (erővel)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'える', kanji: '得る', romaji: 'eru', hu: 'szerez, nyer', tags: ['igék'], jlpt: 'N3' },
  { kana: 'おぎなう', kanji: '補う', romaji: 'oginau', hu: 'pótol, kiegészít', tags: ['igék'], jlpt: 'N3' },
  { kana: 'おさえる', kanji: '押さえる', romaji: 'osaeru', hu: 'lefog, visszatart', tags: ['igék'], jlpt: 'N3' },
  { kana: 'かかえる', kanji: '抱える', romaji: 'kakaeru', hu: 'karjában tart; (gondot) cipel', tags: ['igék'], jlpt: 'N3' },
  { kana: 'かくす', kanji: '隠す', romaji: 'kakusu', hu: 'elrejt, eltitkol', tags: ['igék'], jlpt: 'N3' },
  { kana: 'かさねる', kanji: '重ねる', romaji: 'kasaneru', hu: 'egymásra rak; ismétel', tags: ['igék'], jlpt: 'N3' },
  { kana: 'かせぐ', kanji: '稼ぐ', romaji: 'kasegu', hu: 'pénzt keres', tags: ['igék','munka'], jlpt: 'N3' },
  { kana: 'きざむ', kanji: '刻む', romaji: 'kizamu', hu: 'felaprít; vés', tags: ['igék','ételek'], jlpt: 'N3' },
  { kana: 'きたえる', kanji: '鍛える', romaji: 'kitaeru', hu: 'edz, erősít', tags: ['igék','sport'], jlpt: 'N3' },
  { kana: 'くばる', kanji: '配る', romaji: 'kubaru', hu: 'kioszt, széthord', tags: ['igék'], jlpt: 'N3' },
  { kana: 'くりかえす', kanji: '繰り返す', romaji: 'kurikaesu', hu: 'megismétel', tags: ['igék'], jlpt: 'N3' },
  { kana: 'くわえる', kanji: '加える', romaji: 'kuwaeru', hu: 'hozzáad', tags: ['igék'], jlpt: 'N3' },
  { kana: 'けずる', kanji: '削る', romaji: 'kezuru', hu: 'lefarag, hegyez; csökkent', tags: ['igék'], jlpt: 'N3' },
  { kana: 'こぼす', kanji: '零す', romaji: 'kobosu', hu: 'kiönt, kiloccsant', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ささえる', kanji: '支える', romaji: 'sasaeru', hu: 'támogat, megtart', tags: ['igék'], jlpt: 'N3' },
  { kana: 'さます', kanji: '冷ます', romaji: 'samasu', hu: 'lehűt, hűlni hagy', tags: ['igék','ételek'], jlpt: 'N3' },
  { kana: 'しばる', kanji: '縛る', romaji: 'shibaru', hu: 'megköt', tags: ['igék'], jlpt: 'N3' },
  { kana: 'すます', kanji: '済ます', romaji: 'sumasu', hu: 'elintéz, befejez', tags: ['igék'], jlpt: 'N3' },
  { kana: 'そろえる', kanji: '揃える', romaji: 'soroeru', hu: 'rendez, egységesít; hiánytalanná tesz', tags: ['igék'], jlpt: 'N3' },
  { kana: 'たたむ', kanji: '畳む', romaji: 'tatamu', hu: 'összehajt', tags: ['igék','mindennapi élet'], jlpt: 'N3' },
  { kana: 'ためす', kanji: '試す', romaji: 'tamesu', hu: 'kipróbál', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ためる', kanji: '貯める', romaji: 'tameru', hu: 'gyűjt, félretesz (pénzt)', tags: ['igék','bolt'], jlpt: 'N3' },
  { kana: 'つかまえる', kanji: '捕まえる', romaji: 'tsukamaeru', hu: 'elkap, elfog', tags: ['igék'], jlpt: 'N3' },
  { kana: 'つかむ', kanji: '掴む', romaji: 'tsukamu', hu: 'megragad', tags: ['igék'], jlpt: 'N3' },
  { kana: 'つぶす', kanji: '潰す', romaji: 'tsubusu', hu: 'összenyom; (időt) agyonüt', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ととのえる', kanji: '整える', romaji: 'totonoeru', hu: 'rendbe tesz, előkészít', tags: ['igék'], jlpt: 'N3' },
  { kana: 'なぐる', kanji: '殴る', romaji: 'naguru', hu: 'megüt, megver', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ならす', kanji: '鳴らす', romaji: 'narasu', hu: 'megszólaltat, csenget', tags: ['igék'], jlpt: 'N3' },
  { kana: 'にぎる', kanji: '握る', romaji: 'nigiru', hu: 'megmarkol, megfog', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ぬらす', kanji: '濡らす', romaji: 'nurasu', hu: 'benedvesít, eláztat', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ねらう', kanji: '狙う', romaji: 'nerau', hu: 'céloz, megcéloz', tags: ['igék'], jlpt: 'N3' },
  { kana: 'はずす', kanji: '外す', romaji: 'hazusu', hu: 'levesz, kiold', tags: ['igék'], jlpt: 'N3' },
  { kana: 'はぶく', kanji: '省く', romaji: 'habuku', hu: 'kihagy; megspórol', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ふくむ', kanji: '含む', romaji: 'fukumu', hu: 'tartalmaz, magában foglal', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ふせぐ', kanji: '防ぐ', romaji: 'fusegu', hu: 'megelőz, véd (valami ellen)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'へらす', kanji: '減らす', romaji: 'herasu', hu: 'csökkent', tags: ['igék'], jlpt: 'N3' },
  { kana: 'まもる', kanji: '守る', romaji: 'mamoru', hu: 'megvéd; betart (szabályt, ígéretet)', tags: ['igék'], jlpt: 'N3' },
  { kana: 'みおくる', kanji: '見送る', romaji: 'miokuru', hu: 'kikísér; elhalaszt', tags: ['igék'], jlpt: 'N3' },
  { kana: 'もうける', kanji: '儲ける', romaji: 'moukeru', hu: 'hasznot húz, profitot szerez', tags: ['igék','munka'], jlpt: 'N3' },
  { kana: 'もどす', kanji: '戻す', romaji: 'modosu', hu: 'visszatesz, visszaállít', tags: ['igék'], jlpt: 'N3' },
  { kana: 'もやす', kanji: '燃やす', romaji: 'moyasu', hu: 'eléget', tags: ['igék'], jlpt: 'N3' },
  { kana: 'ゆずる', kanji: '譲る', romaji: 'yuzuru', hu: 'átad, átenged (pl. helyet)', tags: ['igék','udvariasság'], jlpt: 'N3' },
  { kana: 'わける', kanji: '分ける', romaji: 'wakeru', hu: 'szétoszt, elválaszt', tags: ['igék'], jlpt: 'N3' },

  // ─── N3 – Melléknevek (i) ──────────────────────────
  { kana: 'あさい', kanji: '浅い', romaji: 'asai', hu: 'sekély', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'あやしい', kanji: '怪しい', romaji: 'ayashii', hu: 'gyanús', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'あらい', kanji: '荒い', romaji: 'arai', hu: 'durva, heves', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'えらい', kanji: '偉い', romaji: 'erai', hu: 'nagyszerű, tiszteletre méltó', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'おさない', kanji: '幼い', romaji: 'osanai', hu: 'kisgyermek korú; gyerekes', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'おしい', kanji: '惜しい', romaji: 'oshii', hu: 'kár érte, sajnálatos (majdnem sikerült)', tags: ['melléknevek','érzelmek'], jlpt: 'N3' },
  { kana: 'おとなしい', kanji: '大人しい', romaji: 'otonashii', hu: 'csendes, szelíd', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'かしこい', kanji: '賢い', romaji: 'kashikoi', hu: 'okos, bölcs', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'かゆい', kanji: '痒い', romaji: 'kayui', hu: 'viszkető', tags: ['melléknevek','egészség'], jlpt: 'N3' },
  { kana: 'きつい', romaji: 'kitsui', hu: 'szűk; megerőltető', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'くやしい', kanji: '悔しい', romaji: 'kuyashii', hu: 'bosszantó, fájó (kudarc után)', tags: ['melléknevek','érzelmek'], jlpt: 'N3' },
  { kana: 'けわしい', kanji: '険しい', romaji: 'kewashii', hu: 'meredek; szigorú (arc)', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'こいしい', kanji: '恋しい', romaji: 'koishii', hu: 'hiányzik (vágyakozik utána)', tags: ['melléknevek','érzelmek'], jlpt: 'N3' },
  { kana: 'こまかい', kanji: '細かい', romaji: 'komakai', hu: 'apró; részletes', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'さわがしい', kanji: '騒がしい', romaji: 'sawagashii', hu: 'zajos, lármás', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'したしい', kanji: '親しい', romaji: 'shitashii', hu: 'bizalmas, közeli (barát)', tags: ['melléknevek','kapcsolatok'], jlpt: 'N3' },
  { kana: 'しつこい', romaji: 'shitsukoi', hu: 'tolakodó, makacs', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'ずるい', kanji: '狡い', romaji: 'zurui', hu: 'ravasz, tisztességtelen', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'するどい', kanji: '鋭い', romaji: 'surudoi', hu: 'éles', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'だるい', romaji: 'darui', hu: 'bágyadt, levert', tags: ['melléknevek','egészség'], jlpt: 'N3' },
  { kana: 'つらい', kanji: '辛い', romaji: 'tsurai', hu: 'fájdalmas, nehéz (lelkileg)', tags: ['melléknevek','érzelmek'], jlpt: 'N3' },
  { kana: 'にぶい', kanji: '鈍い', romaji: 'nibui', hu: 'tompa, lassú (felfogású)', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'はげしい', kanji: '激しい', romaji: 'hageshii', hu: 'heves, erős', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'まぶしい', kanji: '眩しい', romaji: 'mabushii', hu: 'vakító, káprázatos', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'みにくい', kanji: '醜い', romaji: 'minikui', hu: 'csúnya, rút', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'むしあつい', kanji: '蒸し暑い', romaji: 'mushiatsui', hu: 'fülledt, párás meleg', tags: ['melléknevek','időjárás'], jlpt: 'N3' },
  { kana: 'ものすごい', kanji: '物凄い', romaji: 'monosugoi', hu: 'elképesztő, iszonyatos', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'ゆるい', kanji: '緩い', romaji: 'yurui', hu: 'laza; enyhe', tags: ['melléknevek'], jlpt: 'N3' },

  // ─── N3 – Melléknevek (na) ─────────────────────────
  { kana: 'あきらか', kanji: '明らか', romaji: 'akiraka', hu: 'nyilvánvaló, világos', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'おだやか', kanji: '穏やか', romaji: 'odayaka', hu: 'nyugodt, békés', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'かって', kanji: '勝手', romaji: 'katte', hu: 'önkényes, önfejű', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'きのどく', kanji: '気の毒', romaji: 'kinodoku', hu: 'sajnálatra méltó', tags: ['melléknevek','érzelmek'], jlpt: 'N3' },
  { kana: 'さわやか', kanji: '爽やか', romaji: 'sawayaka', hu: 'üdítő, friss', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'しんけん', kanji: '真剣', romaji: 'shinken', hu: 'komoly, elszánt', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'すなお', kanji: '素直', romaji: 'sunao', hu: 'őszinte, készséges', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'せいかく', kanji: '性格・正確', romaji: 'seikaku', hu: 'jellem, személyiség (性格) / pontos (正確)', tags: ['melléknevek','emberek'], jlpt: 'N3' },
  { kana: 'てきとう', kanji: '適当', romaji: 'tekitou', hu: 'megfelelő; felületes', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'はで', kanji: '派手', romaji: 'hade', hu: 'feltűnő, rikító', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'じみ', kanji: '地味', romaji: 'jimi', hu: 'visszafogott, egyszerű', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'ふしぎ', kanji: '不思議', romaji: 'fushigi', hu: 'különös, rejtélyes', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'ぶじ', kanji: '無事', romaji: 'buji', hu: 'épségben, baj nélkül', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'みごと', kanji: '見事', romaji: 'migoto', hu: 'csodálatos, kiváló', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'めいわく', kanji: '迷惑', romaji: 'meiwaku', hu: 'kellemetlenség, zavar (másoknak)', tags: ['melléknevek','udvariasság'], jlpt: 'N3' },
  { kana: 'ゆたか', kanji: '豊か', romaji: 'yutaka', hu: 'gazdag, bőséges', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'らく', kanji: '楽', romaji: 'raku', hu: 'kényelmes, könnyű', tags: ['melléknevek'], jlpt: 'N3' },
  { kana: 'わがまま', kanji: '我儘', romaji: 'wagamama', hu: 'önző, akaratos', tags: ['melléknevek'], jlpt: 'N3' },

  // ─── N3 – Munka, gazdaság ──────────────────────────
  { kana: 'えいぎょう', kanji: '営業', romaji: 'eigyou', hu: 'értékesítés; nyitvatartás', tags: ['munka'], jlpt: 'N3' },
  { kana: 'けいえい', kanji: '経営', romaji: 'keiei', hu: 'vállalatvezetés, üzemeltetés', tags: ['munka','gazdaság'], jlpt: 'N3' },
  { kana: 'しょるい', kanji: '書類', romaji: 'shorui', hu: 'irat, dokumentum', tags: ['munka'], jlpt: 'N3' },
  { kana: 'せきにん', kanji: '責任', romaji: 'sekinin', hu: 'felelősség', tags: ['munka'], jlpt: 'N3' },
  { kana: 'たんとう', kanji: '担当', romaji: 'tantou', hu: 'felelős (valamiért), megbízott', tags: ['munka'], jlpt: 'N3' },
  { kana: 'ちい', kanji: '地位', romaji: 'chii', hu: 'pozíció, rang', tags: ['munka'], jlpt: 'N3' },
  { kana: 'ていあん', kanji: '提案', romaji: 'teian', hu: 'javaslat', tags: ['munka','kommunikáció'], jlpt: 'N3' },
  { kana: 'ほうこく', kanji: '報告', romaji: 'houkoku', hu: 'jelentés, beszámoló', tags: ['munka','kommunikáció'], jlpt: 'N3' },
  { kana: 'めんせつ', kanji: '面接', romaji: 'mensetsu', hu: 'állásinterjú', tags: ['munka'], jlpt: 'N3' },
  { kana: 'やくわり', kanji: '役割', romaji: 'yakuwari', hu: 'szerep, feladatkör', tags: ['munka'], jlpt: 'N3' },
  { kana: 'りえき', kanji: '利益', romaji: 'rieki', hu: 'haszon, nyereség', tags: ['munka','gazdaság'], jlpt: 'N3' },
  { kana: 'けいやく', kanji: '契約', romaji: 'keiyaku', hu: 'szerződés', tags: ['munka'], jlpt: 'N3' },
  { kana: 'しかく', kanji: '資格', romaji: 'shikaku', hu: 'képesítés, jogosultság', tags: ['munka'], jlpt: 'N3' },
  { kana: 'しょうしん', kanji: '昇進', romaji: 'shoushin', hu: 'előléptetés', tags: ['munka'], jlpt: 'N3' },
  { kana: 'たいしょく', kanji: '退職', romaji: 'taishoku', hu: 'kilépés (munkahelyről), nyugdíjba vonulás', tags: ['munka'], jlpt: 'N3' },
  { kana: 'ざんぎょう', kanji: '残業', romaji: 'zangyou', hu: 'túlóra', tags: ['munka'], jlpt: 'N3' },
  { kana: 'どうりょう', kanji: '同僚', romaji: 'douryou', hu: 'kolléga', tags: ['munka','emberek'], jlpt: 'N3' },
  { kana: 'じょうし', kanji: '上司', romaji: 'joushi', hu: 'felettes, főnök', tags: ['munka','emberek'], jlpt: 'N3' },
  { kana: 'ぶか', kanji: '部下', romaji: 'buka', hu: 'beosztott', tags: ['munka','emberek'], jlpt: 'N3' },
  { kana: 'とりひき', kanji: '取引', romaji: 'torihiki', hu: 'üzlet, tranzakció', tags: ['munka','gazdaság'], jlpt: 'N3' },
  { kana: 'せいひん', kanji: '製品', romaji: 'seihin', hu: 'termék', tags: ['munka','gazdaság'], jlpt: 'N3' },
  { kana: 'しなもの', kanji: '品物', romaji: 'shinamono', hu: 'áru, árucikk', tags: ['bolt'], jlpt: 'N3' },
  { kana: 'かかく', kanji: '価格', romaji: 'kakaku', hu: 'ár (hivatalos)', tags: ['bolt','gazdaság'], jlpt: 'N3' },
  { kana: 'ぜいきん', kanji: '税金', romaji: 'zeikin', hu: 'adó', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'よさん', kanji: '予算', romaji: 'yosan', hu: 'költségvetés, keret', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'しゅうにゅう', kanji: '収入', romaji: 'shuunyuu', hu: 'jövedelem, bevétel', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'ししゅつ', kanji: '支出', romaji: 'shishutsu', hu: 'kiadás', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'ぼうえき', kanji: '貿易', romaji: 'boueki', hu: 'külkereskedelem', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'ゆしゅつ', kanji: '輸出', romaji: 'yushutsu', hu: 'export, kivitel', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'ゆにゅう', kanji: '輸入', romaji: 'yunyuu', hu: 'import, behozatal', tags: ['gazdaság'], jlpt: 'N3' },
  { kana: 'きょうそう', kanji: '競争', romaji: 'kyousou', hu: 'verseny, versengés', tags: ['gazdaság'], jlpt: 'N3' },

  // ─── N3 – Társadalom, média ────────────────────────
  { kana: 'せんきょ', kanji: '選挙', romaji: 'senkyo', hu: 'választás (szavazás)', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'じけん', kanji: '事件', romaji: 'jiken', hu: 'eset, bűnügy', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'はんざい', kanji: '犯罪', romaji: 'hanzai', hu: 'bűncselekmény', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'はんにん', kanji: '犯人', romaji: 'hannin', hu: 'tettes, bűnös', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'さいばん', kanji: '裁判', romaji: 'saiban', hu: 'bírósági tárgyalás, per', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'けんり', kanji: '権利', romaji: 'kenri', hu: 'jog (jogosultság)', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'ぎむ', kanji: '義務', romaji: 'gimu', hu: 'kötelesség', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'へいわ', kanji: '平和', romaji: 'heiwa', hu: 'béke', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'こくさい', kanji: '国際', romaji: 'kokusai', hu: 'nemzetközi', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'しみん', kanji: '市民', romaji: 'shimin', hu: 'polgár, lakos', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'じんこう', kanji: '人口', romaji: 'jinkou', hu: 'népesség, lakosság', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'かんきょう', kanji: '環境', romaji: 'kankyou', hu: 'környezet', tags: ['társadalom','természet'], jlpt: 'N3' },
  { kana: 'しげん', kanji: '資源', romaji: 'shigen', hu: 'erőforrás, nyersanyag', tags: ['társadalom','gazdaság'], jlpt: 'N3' },
  { kana: 'ちょうさ', kanji: '調査', romaji: 'chousa', hu: 'vizsgálat, felmérés', tags: ['társadalom'], jlpt: 'N3' },
  { kana: 'じょうほう', kanji: '情報', romaji: 'jouhou', hu: 'információ', tags: ['kommunikáció'], jlpt: 'N3' },
  { kana: 'きじ', kanji: '記事', romaji: 'kiji', hu: 'cikk (újságban)', tags: ['kommunikáció'], jlpt: 'N3' },
  { kana: 'ひょうばん', kanji: '評判', romaji: 'hyouban', hu: 'hírnév, megítélés', tags: ['kommunikáció'], jlpt: 'N3' },

  // ─── N3 – Gondolkodás, érzelmek (főnevek) ──────────
  { kana: 'いかり', kanji: '怒り', romaji: 'ikari', hu: 'düh, harag', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'かんどう', kanji: '感動', romaji: 'kandou', hu: 'meghatódottság, megindultság', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'かんしゃ', kanji: '感謝', romaji: 'kansha', hu: 'hála, köszönet', tags: ['érzelmek','udvariasság'], jlpt: 'N3' },
  { kana: 'きたい', kanji: '期待', romaji: 'kitai', hu: 'elvárás, remény', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'こうふん', kanji: '興奮', romaji: 'koufun', hu: 'izgalom, izgatottság', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'ふあん', kanji: '不安', romaji: 'fuan', hu: 'szorongás, bizonytalanság', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'まんぞく', kanji: '満足', romaji: 'manzoku', hu: 'elégedettség', tags: ['érzelmek'], jlpt: 'N3' },
  { kana: 'かんかく', kanji: '感覚', romaji: 'kankaku', hu: 'érzék, érzet', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'きおく', kanji: '記憶', romaji: 'kioku', hu: 'emlékezet, emlék', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'いしき', kanji: '意識', romaji: 'ishiki', hu: 'tudat, tudatosság', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'かんがえかた', kanji: '考え方', romaji: 'kangaekata', hu: 'gondolkodásmód', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'ごかい', kanji: '誤解', romaji: 'gokai', hu: 'félreértés', tags: ['gondolkodás','kommunikáció'], jlpt: 'N3' },
  { kana: 'なっとく', kanji: '納得', romaji: 'nattoku', hu: 'belátás, meggyőződés', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'りかい', kanji: '理解', romaji: 'rikai', hu: 'megértés', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'はんだん', kanji: '判断', romaji: 'handan', hu: 'ítélet, döntés', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'けつろん', kanji: '結論', romaji: 'ketsuron', hu: 'következtetés', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'もくてき', kanji: '目的', romaji: 'mokuteki', hu: 'cél (szándék)', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'どりょく', kanji: '努力', romaji: 'doryoku', hu: 'erőfeszítés', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'せいこう', kanji: '成功', romaji: 'seikou', hu: 'siker', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'かのうせい', kanji: '可能性', romaji: 'kanousei', hu: 'lehetőség, esély', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'げんいん', kanji: '原因', romaji: "gen'in", hu: 'ok (kiváltó ok)', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'けっか', kanji: '結果', romaji: 'kekka', hu: 'eredmény, következmény', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'えいきょう', kanji: '影響', romaji: 'eikyou', hu: 'hatás, befolyás', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'じょうけん', kanji: '条件', romaji: 'jouken', hu: 'feltétel', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'じょうたい', kanji: '状態', romaji: 'joutai', hu: 'állapot', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'しゅだん', kanji: '手段', romaji: 'shudan', hu: 'eszköz, mód', tags: ['gondolkodás'], jlpt: 'N3' },
  { kana: 'ぎろん', kanji: '議論', romaji: 'giron', hu: 'vita, eszmecsere', tags: ['kommunikáció'], jlpt: 'N3' },

  // ─── N3 – Egészség, test ───────────────────────────
  { kana: 'けんこう', kanji: '健康', romaji: 'kenkou', hu: 'egészség', tags: ['egészség'], jlpt: 'N3' },
  { kana: 'しょうじょう', kanji: '症状', romaji: 'shoujou', hu: 'tünet', tags: ['egészség'], jlpt: 'N3' },
  { kana: 'ちりょう', kanji: '治療', romaji: 'chiryou', hu: 'kezelés, gyógyítás', tags: ['egészség'], jlpt: 'N3' },
  { kana: 'しゅじゅつ', kanji: '手術', romaji: 'shujutsu', hu: 'műtét', tags: ['egészség'], jlpt: 'N3' },
  { kana: 'ずつう', kanji: '頭痛', romaji: 'zutsuu', hu: 'fejfájás', tags: ['egészség'], jlpt: 'N3' },
  { kana: 'いき', kanji: '息', romaji: 'iki', hu: 'lélegzet', tags: ['egészség','testrészek'], jlpt: 'N3' },
  { kana: 'ほね', kanji: '骨', romaji: 'hone', hu: 'csont', tags: ['testrészek'], jlpt: 'N3' },
  { kana: 'ひふ', kanji: '皮膚', romaji: 'hifu', hu: 'bőr (emberi)', tags: ['testrészek'], jlpt: 'N3' },
  { kana: 'むね', kanji: '胸', romaji: 'mune', hu: 'mellkas; szív (érzelem)', tags: ['testrészek'], jlpt: 'N3' },
  { kana: 'こし', kanji: '腰', romaji: 'koshi', hu: 'derék, csípő', tags: ['testrészek'], jlpt: 'N3' },
  { kana: 'ひじ', kanji: '肘', romaji: 'hiji', hu: 'könyök', tags: ['testrészek'], jlpt: 'N3' },
  { kana: 'ひざ', kanji: '膝', romaji: 'hiza', hu: 'térd', tags: ['testrészek'], jlpt: 'N3' },

  // ─── N3 – Természet ────────────────────────────────
  { kana: 'こうずい', kanji: '洪水', romaji: 'kouzui', hu: 'árvíz', tags: ['természet','időjárás'], jlpt: 'N3' },
  { kana: 'かざん', kanji: '火山', romaji: 'kazan', hu: 'vulkán', tags: ['természet'], jlpt: 'N3' },
  { kana: 'なみ', kanji: '波', romaji: 'nami', hu: 'hullám', tags: ['természet'], jlpt: 'N3' },
  { kana: 'いずみ', kanji: '泉', romaji: 'izumi', hu: 'forrás (víz)', tags: ['természet'], jlpt: 'N3' },
  { kana: 'どろ', kanji: '泥', romaji: 'doro', hu: 'sár', tags: ['természet'], jlpt: 'N3' },
  { kana: 'きり', kanji: '霧', romaji: 'kiri', hu: 'köd', tags: ['természet','időjárás'], jlpt: 'N3' },
  { kana: 'かみなり', kanji: '雷', romaji: 'kaminari', hu: 'mennydörgés, villám', tags: ['természet','időjárás'], jlpt: 'N3' },
  { kana: 'ほのお', kanji: '炎', romaji: 'honoo', hu: 'láng', tags: ['természet'], jlpt: 'N3' },
  { kana: 'けむり', kanji: '煙', romaji: 'kemuri', hu: 'füst', tags: ['természet'], jlpt: 'N3' },

  // ─── N3 – Idő ──────────────────────────────────────
  { kana: 'こんご', kanji: '今後', romaji: 'kongo', hu: 'a jövőben, ezentúl', tags: ['idő'], jlpt: 'N3' },
  { kana: 'かこ', kanji: '過去', romaji: 'kako', hu: 'múlt', tags: ['idő'], jlpt: 'N3' },
  { kana: 'げんざい', kanji: '現在', romaji: 'genzai', hu: 'jelen, jelenleg', tags: ['idő'], jlpt: 'N3' },
  { kana: 'みらい', kanji: '未来', romaji: 'mirai', hu: 'jövő', tags: ['idő'], jlpt: 'N3' },
  { kana: 'とうじ', kanji: '当時', romaji: 'touji', hu: 'akkoriban', tags: ['idő'], jlpt: 'N3' },
  { kana: 'ちょくぜん', kanji: '直前', romaji: 'chokuzen', hu: 'közvetlenül előtte', tags: ['idő'], jlpt: 'N3' },
  { kana: 'きゅうじつ', kanji: '休日', romaji: 'kyuujitsu', hu: 'szabadnap, pihenőnap', tags: ['idő'], jlpt: 'N3' },

  // ─── N3 – Határozószók ─────────────────────────────
  { kana: 'あいかわらず', kanji: '相変わらず', romaji: 'aikawarazu', hu: 'mint mindig, változatlanul', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'いきなり', romaji: 'ikinari', hu: 'hirtelen, váratlanul', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'いちおう', kanji: '一応', romaji: 'ichiou', hu: 'azért, egyelőre (a biztonság kedvéért)', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'いっせいに', kanji: '一斉に', romaji: 'isseini', hu: 'egyszerre, egy időben', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'いったい', kanji: '一体', romaji: 'ittai', hu: 'egyáltalán, ugyan (kérdésben)', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'いつのまにか', kanji: 'いつの間にか', romaji: 'itsunomanika', hu: 'észrevétlenül, mire észbe kap', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'うっかり', romaji: 'ukkari', hu: 'figyelmetlenségből', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'おそらく', kanji: '恐らく', romaji: 'osoraku', hu: 'valószínűleg', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'かならずしも', kanji: '必ずしも', romaji: 'kanarazushimo', hu: 'nem feltétlenül (tagadással)', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'けっして', kanji: '決して', romaji: 'kesshite', hu: 'soha, semmiképp (tagadással)', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'さっそく', kanji: '早速', romaji: 'sassoku', hu: 'azonnal, rögtön', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'しだいに', kanji: '次第に', romaji: 'shidaini', hu: 'fokozatosan', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'すっかり', romaji: 'sukkari', hu: 'teljesen', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'せっかく', kanji: '折角', romaji: 'sekkaku', hu: 'ha már (nagy nehezen), fáradságosan', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'そっと', romaji: 'sotto', hu: 'halkan, óvatosan', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'たちまち', kanji: '忽ち', romaji: 'tachimachi', hu: 'egy pillanat alatt', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'ちゃんと', romaji: 'chanto', hu: 'rendesen, pontosan', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'つい', romaji: 'tsui', hu: 'akaratlanul, véletlenül', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'どうせ', romaji: 'douse', hu: 'úgyis, amúgy is', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'なるべく', romaji: 'narubeku', hu: 'amennyire lehet', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'ふたたび', kanji: '再び', romaji: 'futatabi', hu: 'ismét, újra', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'ほぼ', romaji: 'hobo', hu: 'majdnem, nagyjából', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'まさか', romaji: 'masaka', hu: 'csak nem!, lehetetlen', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'まったく', kanji: '全く', romaji: 'mattaku', hu: 'teljesen; egyáltalán (nem)', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'わざと', romaji: 'wazato', hu: 'szándékosan', tags: ['határozószavak'], jlpt: 'N3' },
  { kana: 'わりと', kanji: '割と', romaji: 'warito', hu: 'viszonylag, meglehetősen', tags: ['határozószavak'], jlpt: 'N3' }
];
