/* ══════════════════════════════════════════════════════
   LexiLearn – Kandzsi Adatbázis (Kanji modul)
   Minden kandzsi: kanji, meaning, onyomi, kunyomi,
                   romaji, jlpt, lesson
══════════════════════════════════════════════════════ */
const KANJI_DATA = [
  // ... (Az előző 80 db N5-ös kandzsi marad az 1-5. leckében) ...

  // ════ JLPT N4 – 6. Lecke: Jellegzetességek és Alapnevek ════
  { kanji: '口', meaning: 'száj', onyomi: 'コウ・ク', kunyomi: 'くち', romaji: 'kuchi / kou', jlpt: 'N4', lesson: 6 },
  { kanji: '田', meaning: 'rizsföld', onyomi: 'デン', kunyomi: 'た', romaji: 'ta / den', jlpt: 'N4', lesson: 6 },
  { kanji: '目', meaning: 'szem', onyomi: 'モク・ボク', kunyomi: 'め', romaji: 'me / moku', jlpt: 'N4', lesson: 6 },
  { kanji: '古', meaning: 'régi', onyomi: 'コ', kunyomi: 'ふる', romaji: 'furu / ko', jlpt: 'N4', lesson: 6 },
  { kanji: '明', meaning: 'világos / fényes', onyomi: 'メイ・ミョウ', kunyomi: 'あか', romaji: 'aka / mei', jlpt: 'N4', lesson: 6 },
  { kanji: '品', meaning: 'árucikk / minőség', onyomi: 'ヒン', kunyomi: 'しな', romaji: 'shina / hin', jlpt: 'N4', lesson: 6 },
  { kanji: '早', meaning: 'korai / gyors', onyomi: 'ソウ', kunyomi: 'はや', romaji: 'haya / sou', jlpt: 'N4', lesson: 6 },
  { kanji: '世', meaning: 'világ / korszak', onyomi: 'セイ・セ', kunyomi: 'よ', romaji: 'yo / sei', jlpt: 'N4', lesson: 6 },
  { kanji: '自', meaning: 'önmaga', onyomi: 'ジ・シ', kunyomi: 'みずか', romaji: 'mizuka / ji', jlpt: 'N4', lesson: 6 },
  { kanji: '朝', meaning: 'reggel', onyomi: 'チョウ', kunyomi: 'あさ', romaji: 'asa / chou', jlpt: 'N4', lesson: 6 },
  { kanji: '員', meaning: 'tag / alkalmazott', onyomi: 'イン', kunyomi: '', romaji: 'in', jlpt: 'N4', lesson: 6 },
  { kanji: '元', meaning: 'eredet / alap', onyomi: 'ゲン・ガン', kunyomi: 'もと', romaji: 'moto / gen', jlpt: 'N4', lesson: 6 },
  { kanji: '的', meaning: 'cél / -szerű', onyomi: 'テキ', kunyomi: 'まと', romaji: 'mato / teki', jlpt: 'N4', lesson: 6 },
  { kanji: '真', meaning: 'igazság / tiszta', onyomi: 'シン', kunyomi: 'ま', romaji: 'ma / shin', jlpt: 'N4', lesson: 6 },
  { kanji: '工', meaning: 'munka / gyártás', onyomi: 'コウ・ク', kunyomi: '', romaji: 'kou', jlpt: 'N4', lesson: 6 },
  { kanji: '有', meaning: 'létezik / birtokol', onyomi: 'ユウ・ウ', kunyomi: 'あ', romaji: 'a / yuu', jlpt: 'N4', lesson: 6 },

  // ════ JLPT N4 – 7. Lecke: Leírások és Tulajdonságok ════
  { kanji: '切', meaning: 'vág / éles', onyomi: 'セツ・サイ', kunyomi: 'き', romaji: 'ki / setsu', jlpt: 'N4', lesson: 7 },
  { kanji: '別', meaning: 'külön / elválik', onyomi: 'ベツ', kunyomi: 'わか', romaji: 'waka / betsu', jlpt: 'N4', lesson: 7 },
  { kanji: '町', meaning: 'város / negyed', onyomi: 'チョウ', kunyomi: 'まち', romaji: 'machi / chou', jlpt: 'N4', lesson: 7 },
  { kanji: '兄', meaning: 'báty', onyomi: 'ケイ・キョウ', kunyomi: 'あに', romaji: 'ani / kei', jlpt: 'N4', lesson: 7 },
  { kanji: '少', meaning: 'kevés', onyomi: 'ショウ', kunyomi: 'すく・すこ', romaji: 'suku / shou', jlpt: 'N4', lesson: 7 },
  { kanji: '多', meaning: 'sok', onyomi: 'タ', kunyomi: 'おお', romaji: 'oo / ta', jlpt: 'N4', lesson: 7 },
  { kanji: '夕', meaning: 'este', onyomi: 'セキ', kunyomi: 'ゆう', romaji: 'yuu / seki', jlpt: 'N4', lesson: 7 },
  { kanji: '魚', meaning: 'hal', onyomi: 'ギョ', kunyomi: 'うお・さかな', romaji: 'sakana / gyo', jlpt: 'N4', lesson: 7 },
  { kanji: '黒', meaning: 'fekete', onyomi: 'コク', kunyomi: 'くろ', romaji: 'kuro / koku', jlpt: 'N4', lesson: 7 },
  { kanji: '同', meaning: 'ugyanaz', onyomi: 'ドウ', kunyomi: 'おな', romaji: 'ona / dou', jlpt: 'N4', lesson: 7 },
  { kanji: '字', meaning: 'karakter / betű', onyomi: 'ジ', kunyomi: 'あざ', romaji: 'ji / aza', jlpt: 'N4', lesson: 7 },
  { kanji: '安', meaning: 'olcsó / nyugodt', onyomi: 'アン', kunyomi: 'やす', romaji: 'yasu / an', jlpt: 'N4', lesson: 7 },
  { kanji: '味', meaning: 'íz', onyomi: 'ミ', kunyomi: 'あじ', romaji: 'aji / mi', jlpt: 'N4', lesson: 7 },
  { kanji: '妹', meaning: 'húg', onyomi: 'マイ', kunyomi: 'いもうと', romaji: 'imouto / mai', jlpt: 'N4', lesson: 7 },
  { kanji: '犬', meaning: 'kutya', onyomi: 'ケン', kunyomi: 'いぬ', romaji: 'inu / ken', jlpt: 'N4', lesson: 7 },
  { kanji: '牛', meaning: 'tehén', onyomi: 'ギュウ', kunyomi: 'うし', romaji: 'ushi / gyuu', jlpt: 'N4', lesson: 7 },

  // ════ JLPT N4 – 8. Lecke: Fogalmak és Természet ════
  { kanji: '特', meaning: 'különleges', onyomi: 'トク', kunyomi: '', romaji: 'toku', jlpt: 'N4', lesson: 8 },
  { kanji: '界', meaning: 'világ / határ', onyomi: 'カイ', kunyomi: '', romaji: 'kai', jlpt: 'N4', lesson: 8 },
  { kanji: '茶', meaning: 'tea', onyomi: 'チャ・サ', kunyomi: '', romaji: 'cha / sa', jlpt: 'N4', lesson: 8 },
  { kanji: '理', meaning: 'logika / értelem', onyomi: 'リ', kunyomi: 'ことわり', romaji: 'ri / kotowari', jlpt: 'N4', lesson: 8 },
  { kanji: '主', meaning: 'úr / fő', onyomi: 'シュ', kunyomi: 'ぬし・おも', romaji: 'omo / shu', jlpt: 'N4', lesson: 8 },
  { kanji: '注', meaning: 'önt / jegyzet', onyomi: 'チュウ', kunyomi: 'そそ', romaji: 'soso / chuu', jlpt: 'N4', lesson: 8 },
  { kanji: '道', meaning: 'út', onyomi: 'ドウ', kunyomi: 'みち', romaji: 'michi / dou', jlpt: 'N4', lesson: 8 },
  { kanji: '夏', meaning: 'nyár', onyomi: 'カ', kunyomi: 'なつ', romaji: 'natsu / ka', jlpt: 'N4', lesson: 8 },
  { kanji: '運', meaning: 'szerencse / mozgat', onyomi: 'ウン', kunyomi: 'はこ', romaji: 'hako / un', jlpt: 'N4', lesson: 8 },
  { kanji: '京', meaning: 'főváros', onyomi: 'キョウ・ケイ', kunyomi: 'みやこ', romaji: 'miyako / kyou', jlpt: 'N4', lesson: 8 },
  { kanji: '週', meaning: 'hét (időtartam)', onyomi: 'シュウ', kunyomi: '', romaji: 'shuu', jlpt: 'N4', lesson: 8 },
  { kanji: '売', meaning: 'elad', onyomi: 'バイ', kunyomi: 'う', romaji: 'u / bai', jlpt: 'N4', lesson: 8 },
  { kanji: '言', meaning: 'mond / szó', onyomi: 'ゲン・ゴン', kunyomi: 'い・こと', romaji: 'i / gen', jlpt: 'N4', lesson: 8 },
  { kanji: '計', meaning: 'terv / mér', onyomi: 'ケイ', kunyomi: 'はか', romaji: 'haka / kei', jlpt: 'N4', lesson: 8 },
  { kanji: '試', meaning: 'próbál / teszt', onyomi: 'シ', kunyomi: 'こころ・ため', romaji: 'tame / shi', jlpt: 'N4', lesson: 8 },
  { kanji: '止', meaning: 'megáll', onyomi: 'シ', kunyomi: 'と', romaji: 'to / shi', jlpt: 'N4', lesson: 8 },

  // ════ JLPT N4 – 9. Lecke: Mozgás és Helyszínek ════
  { kanji: '歩', meaning: 'sétál', onyomi: 'ホ', kunyomi: 'ある・あゆ', romaji: 'aru / ho', jlpt: 'N4', lesson: 9 },
  { kanji: '正', meaning: 'helyes / igaz', onyomi: 'セイ・ショウ', kunyomi: 'ただ', romaji: 'tada / sei', jlpt: 'N4', lesson: 9 },
  { kanji: '走', meaning: 'fut', onyomi: 'ソウ', kunyomi: 'はし', romaji: 'hashi / sou', jlpt: 'N4', lesson: 9 },
  { kanji: '題', meaning: 'tárgy / cím', onyomi: 'ダイ', kunyomi: '', romaji: 'dai', jlpt: 'N4', lesson: 9 },
  { kanji: '建', meaning: 'épít', onyomi: 'ケン', kunyomi: 'た', romaji: 'ta / ken', jlpt: 'N4', lesson: 9 },
  { kanji: '姉', meaning: 'nővér', onyomi: 'シ', kunyomi: 'あね', romaji: 'ane / shi', jlpt: 'N4', lesson: 9 },
  { kanji: '転', meaning: 'gurul / fordul', onyomi: 'テン', kunyomi: 'ころ', romaji: 'koro / ten', jlpt: 'N4', lesson: 9 },
  { kanji: '冬', meaning: 'tél', onyomi: 'トウ', kunyomi: 'ふゆ', romaji: 'fuyu / tou', jlpt: 'N4', lesson: 9 },
  { kanji: '立', meaning: 'feláll', onyomi: 'リツ', kunyomi: 'た', romaji: 'ta / ritsu', jlpt: 'N4', lesson: 9 },
  { kanji: '海', meaning: 'tenger', onyomi: 'カイ', kunyomi: 'うみ', romaji: 'umi / kai', jlpt: 'N4', lesson: 9 },
  { kanji: '歌', meaning: 'dal', onyomi: 'カ', kunyomi: 'うた', romaji: 'uta / ka', jlpt: 'N4', lesson: 9 },
  { kanji: '音', meaning: 'hang', onyomi: 'オン', kunyomi: 'おと・ね', romaji: 'oto / on', jlpt: 'N4', lesson: 9 },
  { kanji: '方', meaning: 'irány / módszer', onyomi: 'ホウ', kunyomi: 'かた', romaji: 'kata / hou', jlpt: 'N4', lesson: 9 },
  { kanji: '地', meaning: 'föld / hely', onyomi: 'チ・ジ', kunyomi: '', romaji: 'chi / ji', jlpt: 'N4', lesson: 9 },
  { kanji: '風', meaning: 'szél / stílus', onyomi: 'フウ', kunyomi: 'かぜ', romaji: 'kaze / fuu', jlpt: 'N4', lesson: 9 },
  { kanji: '起', meaning: 'felkel / történik', onyomi: 'キ', kunyomi: 'お', romaji: 'o / ki', jlpt: 'N4', lesson: 9 },

  // ════ JLPT N4 – 10. Lecke: Érzés és Cselekvés ════
  { kanji: '家', meaning: 'ház / otthon', onyomi: 'カ・ケ', kunyomi: 'いえ・や', romaji: 'ie / ka', jlpt: 'N4', lesson: 10 },
  { kanji: '場', meaning: 'hely / szituáció', onyomi: 'ジョウ', kunyomi: 'ば', romaji: 'ba / jou', jlpt: 'N4', lesson: 10 },
  { kanji: '洋', meaning: 'óceán / nyugati', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N4', lesson: 10 },
  { kanji: '着', meaning: 'felvesz (ruhát) / megérkezik', onyomi: 'チャク', kunyomi: 'き・つ', romaji: 'ki / chaku', jlpt: 'N4', lesson: 10 },
  { kanji: '集', meaning: 'összegyűjt', onyomi: 'シュウ', kunyomi: 'あつ', romaji: 'atsu / shuu', jlpt: 'N4', lesson: 10 },
  { kanji: '習', meaning: 'tanul / gyakorol', onyomi: 'シュウ', kunyomi: 'なら', romaji: 'nara / shuu', jlpt: 'N4', lesson: 10 },
  { kanji: '曜', meaning: 'hét napja', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N4', lesson: 10 },
  { kanji: '店', meaning: 'bolt', onyomi: 'テン', kunyomi: 'みせ', romaji: 'mise / ten', jlpt: 'N4', lesson: 10 },
  { kanji: '心', meaning: 'szív / lélek', onyomi: 'シン', kunyomi: 'こころ', romaji: 'kokoro / shin', jlpt: 'N4', lesson: 10 },
  { kanji: '思', meaning: 'gondol', onyomi: 'シ', kunyomi: 'おも', romaji: 'omo / shi', jlpt: 'N4', lesson: 10 },
  { kanji: '意', meaning: 'szándék / jelentés', onyomi: 'イ', kunyomi: '', romaji: 'i', jlpt: 'N4', lesson: 10 },
  { kanji: '手', meaning: 'kéz', onyomi: 'シュ', kunyomi: 'て', romaji: 'te / shu', jlpt: 'N4', lesson: 10 },
  { kanji: '持', meaning: 'tart / birtokol', onyomi: 'ジ', kunyomi: 'も', romaji: 'mo / ji', jlpt: 'N4', lesson: 10 },
  { kanji: '研', meaning: 'kutat / csiszol', onyomi: 'ケン', kunyomi: 'と', romaji: 'to / ken', jlpt: 'N4', lesson: 10 },
  { kanji: '広', meaning: 'széles / tágas', onyomi: 'コウ', kunyomi: 'ひろ', romaji: 'hiro / kou', jlpt: 'N4', lesson: 10 },
  { kanji: '台', meaning: 'állvány / gép', onyomi: 'ダイ・タイ', kunyomi: '', romaji: 'dai', jlpt: 'N4', lesson: 10 },

  // ════ JLPT N4 – 11. Lecke: Munka és Élet ════
  { kanji: '始', meaning: 'kezdődik', onyomi: 'シ', kunyomi: 'はじ', romaji: 'haji / shi', jlpt: 'N4', lesson: 11 },
  { kanji: '去', meaning: 'elmúlik / elhagy', onyomi: 'キョ・コ', kunyomi: 'さ', romaji: 'sa / kyo', jlpt: 'N4', lesson: 11 },
  { kanji: '会', meaning: 'találkozik / társaság', onyomi: 'カイ', kunyomi: 'あ', romaji: 'a / kai', jlpt: 'N4', lesson: 11 },
  { kanji: '室', meaning: 'szoba', onyomi: 'シツ', kunyomi: 'むろ', romaji: 'muro / shitsu', jlpt: 'N4', lesson: 11 },
  { kanji: '公', meaning: 'nyilvános', onyomi: 'コウ', kunyomi: 'おおやけ', romaji: 'ooyake / kou', jlpt: 'N4', lesson: 11 },
  { kanji: '堂', meaning: 'terem / csarnok', onyomi: 'ドウ', kunyomi: '', romaji: 'dou', jlpt: 'N4', lesson: 11 },
  { kanji: '死', meaning: 'halál', onyomi: 'シ', kunyomi: 'し', romaji: 'shi', jlpt: 'N4', lesson: 11 },
  { kanji: '买', meaning: 'vásárol', onyomi: 'バイ', kunyomi: 'か', romaji: 'ka / bai', jlpt: 'N4', lesson: 11 },
  { kanji: '力', meaning: 'erő', onyomi: 'リョク・リキ', kunyomi: 'ちから', romaji: 'chikara / ryoku', jlpt: 'N4', lesson: 11 },
  { kanji: '待', meaning: 'vár', onyomi: 'タイ', kunyomi: 'ま', romaji: 'ma / tai', jlpt: 'N4', lesson: 11 },
  { kanji: '秋', meaning: 'ősz', onyomi: 'シュウ', kunyomi: 'あき', romaji: 'aki / shuu', jlpt: 'N4', lesson: 11 },
  { kanji: '私', meaning: 'én', onyomi: 'シ', kunyomi: 'わたし・わたくし', romaji: 'watashi / shi', jlpt: 'N4', lesson: 11 },
  { kanji: '答', meaning: 'válasz', onyomi: 'トウ', kunyomi: 'こた', romaji: 'kota / tou', jlpt: 'N4', lesson: 11 },
  { kanji: '住', meaning: 'lakik', onyomi: 'ジュウ', kunyomi: 'す', romaji: 'su / juu', jlpt: 'N4', lesson: 11 },
  { kanji: '体', meaning: 'test', onyomi: 'タイ', kunyomi: 'からだ', romaji: 'karada / tai', jlpt: 'N4', lesson: 11 },
  { kanji: '仕', meaning: 'szolgál / munka', onyomi: 'シ', kunyomi: 'つか', romaji: 'tsuka / shi', jlpt: 'N4', lesson: 11 },

  // ════ JLPT N4 – 12. Lecke: Maradékok és Összetettek (IMG_4057 alapján) ════
  { kanji: '族', meaning: 'törzs / család', onyomi: 'ゾク', kunyomi: '', romaji: 'zoku', jlpt: 'N4', lesson: 12 },
  { kanji: '知', meaning: 'tud / ismer', onyomi: 'チ', kunyomi: 'し', romaji: 'shi / chi', jlpt: 'N4', lesson: 12 },
  { kanji: '帰', meaning: 'hazatér', onyomi: 'キ', kunyomi: 'かえ', romaji: 'kae / ki', jlpt: 'N4', lesson: 12 },
  { kanji: '強', meaning: 'erős', onyomi: 'キョウ・ゴウ', kunyomi: 'つよ', romaji: 'tsuyo / kyou', jlpt: 'N4', lesson: 12 },
  { kanji: '弟', meaning: 'öccs', onyomi: 'テイ・ダイ', kunyomi: 'おとうと', romaji: 'otouto / tei', jlpt: 'N4', lesson: 12 },
  { kanji: '写', meaning: 'másol / fotóz', onyomi: 'シャ', kunyomi: 'うつ', romaji: 'utsu / sha', jlpt: 'N4', lesson: 12 },
  { kanji: '考', meaning: 'gondolkodik', onyomi: 'コウ', kunyomi: 'かんが', romaji: 'kanga / kou', jlpt: 'N4', lesson: 12 },
  { kanji: '教', meaning: 'tanít', onyomi: 'キョウ', kunyomi: 'おし', romaji: 'oshi / kyou', jlpt: 'N4', lesson: 12 },
  { kanji: '者', meaning: 'személy / valaki', onyomi: 'シャ', kunyomi: 'もの', romaji: 'mono / sha', jlpt: 'N4', lesson: 12 },
  { kanji: '足', meaning: 'láb / elegendő', onyomi: 'ソク', kunyomi: 'あし・た', romaji: 'ashi / soku', jlpt: 'N4', lesson: 12 },
  { kanji: '院', meaning: 'intézmény', onyomi: 'イン', kunyomi: '', romaji: 'in', jlpt: 'N4', lesson: 12 },
  { kanji: '空', meaning: 'ég / üres', onyomi: 'クウ', kunyomi: 'そら・あ', romaji: 'sora / kuu', jlpt: 'N4', lesson: 12 },
  { kanji: '究', meaning: 'kutat', onyomi: 'キュウ', kunyomi: 'きわ', romaji: 'kiwa / kyuu', jlpt: 'N4', lesson: 12 },
  { kanji: '終', meaning: 'vége', onyomi: 'シュウ', kunyomi: 'お', romaji: 'o / shuu', jlpt: 'N4', lesson: 12 },
  { kanji: '新', meaning: 'új', onyomi: 'シン', kunyomi: 'あたら', romaji: 'atara / shin', jlpt: 'N4', lesson: 12 },
  { kanji: '春', meaning: 'tavasz', onyomi: 'シュン', kunyomi: 'はる', romaji: 'haru / shun', jlpt: 'N4', lesson: 12 },
  { kanji: '動', meaning: 'mozog', onyomi: 'ドウ', kunyomi: 'うご', romaji: 'ugo / dou', jlpt: 'N4', lesson: 12 },
  { kanji: '病', meaning: 'betegség', onyomi: 'ビョウ', kunyomi: 'やまい', romaji: 'yamai / byou', jlpt: 'N4', lesson: 12 },
  { kanji: '勉', meaning: 'igyekszik / tanul', onyomi: 'ベン', kunyomi: 'つと', romaji: 'tsuto / ben', jlpt: 'N4', lesson: 12 },
  { kanji: '駅', meaning: 'állomás', onyomi: 'エキ', kunyomi: '', romaji: 'eki', jlpt: 'N4', lesson: 12 },
  { kanji: '送', meaning: 'küld', onyomi: 'ソウ', kunyomi: 'おく', romaji: 'oku / sou', jlpt: 'N4', lesson: 12 }
];