/* ══════════════════════════════════════════════════════
   LexiLearn – Kandzsi Adatbázis (Kanji modul)
   Minden kandzsi a beküldött képek alapján (N5, N4, N3)
══════════════════════════════════════════════════════ */
const KANJI_DATA = [
  // ════ JLPT N5 (80 db) ════
  { kanji: '一', meaning: 'egy', onyomi: 'イチ', kunyomi: 'ひと', romaji: 'ichi / hito', jlpt: 'N5', lesson: 1 },
  { kanji: '二', meaning: 'kettő', onyomi: 'ニ', kunyomi: 'ふた', romaji: 'ni / futa', jlpt: 'N5', lesson: 1 },
  { kanji: '三', meaning: 'három', onyomi: 'サン', kunyomi: 'み', romaji: 'san / mi', jlpt: 'N5', lesson: 1 },
  { kanji: '四', meaning: 'négy', onyomi: 'シ', kunyomi: 'よ・よん', romaji: 'shi / yon', jlpt: 'N5', lesson: 1 },
  { kanji: '五', meaning: 'öt', onyomi: 'ゴ', kunyomi: 'いつ', romaji: 'go / itsu', jlpt: 'N5', lesson: 1 },
  { kanji: '六', meaning: 'hat', onyomi: 'ロク', kunyomi: 'む', romaji: 'roku / mu', jlpt: 'N5', lesson: 1 },
  { kanji: '七', meaning: 'hét', onyomi: 'シチ', kunyomi: 'なな', romaji: 'shichi / nana', jlpt: 'N5', lesson: 1 },
  { kanji: '八', meaning: 'nyolc', onyomi: 'ハチ', kunyomi: 'や', romaji: 'hachi / ya', jlpt: 'N5', lesson: 1 },
  { kanji: '九', meaning: 'kilenc', onyomi: 'キュウ・ク', kunyomi: 'ここの', romaji: 'kyuu / kokono', jlpt: 'N5', lesson: 1 },
  { kanji: '十', meaning: 'tíz', onyomi: 'ジュウ', kunyomi: 'とお', romaji: 'juu / too', jlpt: 'N5', lesson: 1 },
  { kanji: '日', meaning: 'nap', onyomi: 'ニチ・ジツ', kunyomi: 'ひ・か', romaji: 'nichi / hi', jlpt: 'N5', lesson: 1 },
  { kanji: '月', meaning: 'hold / hónap', onyomi: 'ゲツ・ガツ', kunyomi: 'つき', romaji: 'getsu / tsuki', jlpt: 'N5', lesson: 1 },
  { kanji: '白', meaning: 'fehér', onyomi: 'ハク', kunyomi: 'しろ', romaji: 'haku / shiro', jlpt: 'N5', lesson: 1 },
  { kanji: '百', meaning: 'száz', onyomi: 'ヒャク', kunyomi: 'もも', romaji: 'hyaku', jlpt: 'N5', lesson: 1 },
  { kanji: '中', meaning: 'közép / belül', onyomi: 'チュウ', kunyomi: 'なか', romaji: 'chuu / naka', jlpt: 'N5', lesson: 1 },
  { kanji: '千', meaning: 'ezer', onyomi: 'セン', kunyomi: 'ち', romaji: 'sen / chi', jlpt: 'N5', lesson: 1 },
  { kanji: '上', meaning: 'fent / felett', onyomi: 'ジョウ', kunyomi: 'うえ', romaji: 'jou / ue', jlpt: 'N5', lesson: 2 },
  { kanji: '下', meaning: 'lent / alatt', onyomi: 'カ・ゲ', kunyomi: 'した', romaji: 'ka / shita', jlpt: 'N5', lesson: 2 },
  { kanji: '見', meaning: 'néz / lát', onyomi: 'ケン', kunyomi: 'み', romaji: 'ken / mi', jlpt: 'N5', lesson: 2 },
  { kanji: '万', meaning: 'tízezer', onyomi: 'マン・バン', kunyomi: '', romaji: 'man / ban', jlpt: 'N5', lesson: 2 },
  { kanji: '左', meaning: 'bal', onyomi: 'サ', kunyomi: 'ひだり', romaji: 'sa / hidari', jlpt: 'N5', lesson: 2 },
  { kanji: '右', meaning: 'jobb', onyomi: 'ウ・ユウ', kunyomi: 'みぎ', romaji: 'u / migi', jlpt: 'N5', lesson: 2 },
  { kanji: '子', meaning: 'gyerek', onyomi: 'シ', kunyomi: 'こ', romaji: 'shi / ko', jlpt: 'N5', lesson: 2 },
  { kanji: '女', meaning: 'nő', onyomi: 'ジョ', kunyomi: 'おんな', romaji: 'jo / onna', jlpt: 'N5', lesson: 2 },
  { kanji: '母', meaning: 'anya', onyomi: 'ボ', kunyomi: 'はは', romaji: 'bo / haha', jlpt: 'N5', lesson: 2 },
  { kanji: '小', meaning: 'kicsi', onyomi: 'ショウ', kunyomi: 'ちい', romaji: 'shou / chii', jlpt: 'N5', lesson: 2 },
  { kanji: '大', meaning: 'nagy', onyomi: 'ダイ・タイ', kunyomi: 'おお', romaji: 'dai / oo', jlpt: 'N5', lesson: 2 },
  { kanji: '外', meaning: 'kint / külső', onyomi: 'ガイ', kunyomi: 'そと', romaji: 'gai / soto', jlpt: 'N5', lesson: 2 },
  { kanji: '名', meaning: 'név', onyomi: 'メイ・ミョウ', kunyomi: 'な', romaji: 'mei / na', jlpt: 'N5', lesson: 2 },
  { kanji: '川', meaning: 'folyó', onyomi: 'セン', kunyomi: 'かわ', romaji: 'sen / kawa', jlpt: 'N5', lesson: 2 },
  { kanji: '水', meaning: 'víz', onyomi: 'スイ', kunyomi: 'みず', romaji: 'sui / mizu', jlpt: 'N5', lesson: 2 },
  { kanji: '土', meaning: 'föld', onyomi: 'ド・ト', kunyomi: 'つち', romaji: 'do / tsuchi', jlpt: 'N5', lesson: 2 },
  { kanji: '時', meaning: 'idő / óra', onyomi: 'ジ', kunyomi: 'とき', romaji: 'ji / toki', jlpt: 'N5', lesson: 3 },
  { kanji: '火', meaning: 'tűz', onyomi: 'カ', kunyomi: 'ひ', romaji: 'ka / hi', jlpt: 'N5', lesson: 3 },
  { kanji: '木', meaning: 'fa', onyomi: 'モク・ボク', kunyomi: 'き', romaji: 'moku / ki', jlpt: 'N5', lesson: 3 },
  { kanji: '本', meaning: 'könyv / eredet', onyomi: 'ホン', kunyomi: 'もと', romaji: 'hon / moto', jlpt: 'N5', lesson: 3 },
  { kanji: '先', meaning: 'előbb / múlt', onyomi: 'セン', kunyomi: 'さき', romaji: 'sen / saki', jlpt: 'N5', lesson: 3 },
  { kanji: '金', meaning: 'arany / pénz', onyomi: 'キン・コン', kunyomi: 'かね', romaji: 'kin / kane', jlpt: 'N5', lesson: 3 },
  { kanji: '車', meaning: 'autó / kerék', onyomi: 'シャ', kunyomi: 'くるま', romaji: 'sha / kuruma', jlpt: 'N5', lesson: 3 },
  { kanji: '前', meaning: 'előtt / elöl', onyomi: 'ゼン', kunyomi: 'まえ', romaji: 'zen / mae', jlpt: 'N5', lesson: 3 },
  { kanji: '高', meaning: 'magas / drága', onyomi: 'コウ', kunyomi: 'たか', romaji: 'kou / taka', jlpt: 'N5', lesson: 3 },
  { kanji: '学', meaning: 'tanulmány', onyomi: 'ガク', kunyomi: 'まな', romaji: 'gaku / mana', jlpt: 'N5', lesson: 3 },
  { kanji: '書', meaning: 'ír', onyomi: 'ショ', kunyomi: 'か', romaji: 'sho / ka', jlpt: 'N5', lesson: 3 },
  { kanji: '話', meaning: 'beszél / beszéd', onyomi: 'ワ', kunyomi: 'はな', romaji: 'wa / hana', jlpt: 'N5', lesson: 3 },
  { kanji: '語', meaning: 'nyelv / szó', onyomi: 'ゴ', kunyomi: 'かた', romaji: 'go / kata', jlpt: 'N5', lesson: 3 },
  { kanji: '読', meaning: 'olvas', onyomi: 'ドク', kunyomi: 'よ', romaji: 'doku / yo', jlpt: 'N5', lesson: 3 },
  { kanji: '雨', meaning: 'eső', onyomi: 'ウ', kunyomi: 'あめ', romaji: 'u / ame', jlpt: 'N5', lesson: 3 },
  { kanji: '天', meaning: 'ég / menny', onyomi: 'テン', kunyomi: 'あま', romaji: 'ten / ama', jlpt: 'N5', lesson: 3 },
  { kanji: '北', meaning: 'észak', onyomi: 'ホク', kunyomi: 'きた', romaji: 'hoku / kita', jlpt: 'N5', lesson: 4 },
  { kanji: '毎', meaning: 'minden (egyes)', onyomi: 'マイ', kunyomi: '', romaji: 'mai', jlpt: 'N5', lesson: 4 },
  { kanji: '東', meaning: 'kelet', onyomi: 'トウ', kunyomi: 'ひがし', romaji: 'tou / higashi', jlpt: 'N5', lesson: 4 },
  { kanji: '電', meaning: 'elektromosság', onyomi: 'デン', kunyomi: '', romaji: 'den', jlpt: 'N5', lesson: 4 },
  { kanji: '午', meaning: 'dél (napszak)', onyomi: 'ゴ', kunyomi: '', romaji: 'go', jlpt: 'N5', lesson: 4 },
  { kanji: '国', meaning: 'ország', onyomi: 'コク', kunyomi: 'くに', romaji: 'koku / kuni', jlpt: 'N5', lesson: 4 },
  { kanji: '友', meaning: 'barát', onyomi: 'ユウ', kunyomi: 'とも', romaji: 'yuu / tomo', jlpt: 'N5', lesson: 4 },
  { kanji: '出', meaning: 'kimegy / kiad', onyomi: 'シュツ', kunyomi: 'で・だ', romaji: 'shutsu / de', jlpt: 'N5', lesson: 4 },
  { kanji: '山', meaning: 'hegy', onyomi: 'サン', kunyomi: 'やま', romaji: 'san / yama', jlpt: 'N5', lesson: 4 },
  { kanji: '入', meaning: 'bemegy / berak', onyomi: 'ニュウ', kunyomi: 'はい・い', romaji: 'nyuu / hai', jlpt: 'N5', lesson: 4 },
  { kanji: '分', meaning: 'perc / rész', onyomi: 'ブン・フン', kunyomi: 'わ', romaji: 'bun / fun', jlpt: 'N5', lesson: 4 },
  { kanji: '男', meaning: 'férfi', onyomi: 'ダン・ナン', kunyomi: 'おとこ', romaji: 'dan / otoko', jlpt: 'N5', lesson: 4 },
  { kanji: '行', meaning: 'megy', onyomi: 'コウ・ギョウ', kunyomi: 'い', romaji: 'kou / i', jlpt: 'N5', lesson: 4 },
  { kanji: '人', meaning: 'ember', onyomi: 'ジン・ニン', kunyomi: 'ひと', romaji: 'jin / hito', jlpt: 'N5', lesson: 4 },
  { kanji: '休', meaning: 'pihen', onyomi: 'キュウ', kunyomi: 'やす', romaji: 'kyuu / yasu', jlpt: 'N5', lesson: 4 },
  { kanji: '何', meaning: 'mi / micsoda', onyomi: 'カ', kunyomi: 'なに・なん', romaji: 'ka / nani', jlpt: 'N5', lesson: 4 },
  { kanji: '年', meaning: 'év', onyomi: 'ネン', kunyomi: 'とし', romaji: 'nen / toshi', jlpt: 'N5', lesson: 5 },
  { kanji: '半', meaning: 'fél', onyomi: 'ハン', kunyomi: 'なか', romaji: 'han / naka', jlpt: 'N5', lesson: 5 },
  { kanji: '父', meaning: 'apa', onyomi: 'フ', kunyomi: 'ちち', romaji: 'fu / chichi', jlpt: 'N5', lesson: 5 },
  { kanji: '校', meaning: 'iskola', onyomi: 'コウ', kunyomi: '', romaji: 'kou', jlpt: 'N5', lesson: 5 },
  { kanji: '後', meaning: 'után / hátul', onyomi: 'ゴ・コウ', kunyomi: 'うし・あと', romaji: 'go / ato', jlpt: 'N5', lesson: 5 },
  { kanji: '食', meaning: 'eszik', onyomi: 'ショク', kunyomi: 'た', romaji: 'shoku / ta', jlpt: 'N5', lesson: 5 },
  { kanji: '生', meaning: 'élet / születés', onyomi: 'セイ・ショウ', kunyomi: 'い・う', romaji: 'sei / i', jlpt: 'N5', lesson: 5 },
  { kanji: '今', meaning: 'most', onyomi: 'コン・キン', kunyomi: 'いま', romaji: 'kon / ima', jlpt: 'N5', lesson: 5 },
  { kanji: '西', meaning: 'nyugat', onyomi: 'セイ・サイ', kunyomi: 'にし', romaji: 'sei / nishi', jlpt: 'N5', lesson: 5 },
  { kanji: '南', meaning: 'dél (irány)', onyomi: 'ナン', kunyomi: 'みなみ', romaji: 'nan / minami', jlpt: 'N5', lesson: 5 },
  { kanji: '間', meaning: 'között / időszak', onyomi: 'カン・ケン', kunyomi: 'あいだ', romaji: 'kan / aida', jlpt: 'N5', lesson: 5 },
  { kanji: '聞', meaning: 'hall / kérdez', onyomi: 'ブン・モン', kunyomi: 'き', romaji: 'bun / ki', jlpt: 'N5', lesson: 5 },
  { kanji: '円', meaning: 'jen / kör', onyomi: 'エン', kunyomi: 'まる', romaji: 'en / maru', jlpt: 'N5', lesson: 5 },
  { kanji: '来', meaning: 'jön', onyomi: 'ライ', kunyomi: 'く', romaji: 'rai / ku', jlpt: 'N5', lesson: 5 },
  { kanji: '気', meaning: 'szellem / energia', onyomi: 'キ・ケ', kunyomi: '', romaji: 'ki / ke', jlpt: 'N5', lesson: 5 },
  { kanji: '長', meaning: 'hosszú / vezető', onyomi: 'チョウ', kunyomi: 'なが', romaji: 'chou / naga', jlpt: 'N5', lesson: 5 },

  // ════ JLPT N4 (167 db) ════
  { kanji: '口', meaning: 'száj', onyomi: 'コウ・ク', kunyomi: 'くち', romaji: 'kuchi / kou', jlpt: 'N4', lesson: 6 },
  { kanji: '田', meaning: 'rizsföld', onyomi: 'デン', kunyomi: 'た', romaji: 'ta / den', jlpt: 'N4', lesson: 6 },
  { kanji: '目', meaning: 'szem', onyomi: 'モク・ボク', kunyomi: 'め', romaji: 'me / moku', jlpt: 'N4', lesson: 6 },
  { kanji: '古', meaning: 'régi', onyomi: 'コ', kunyomi: 'ふる', romaji: 'furu / ko', jlpt: 'N4', lesson: 6 },
  { kanji: '明', meaning: 'világos / fényes', onyomi: 'メイ・ミョウ', kunyomi: 'あか', romaji: 'aka / mei', jlpt: 'N4', lesson: 6 },
  { kanji: '品', meaning: 'árucikk / minőség', onyomi: 'ヒン', kunyomi: 'しな', romaji: 'shina / hin', jlpt: 'N4', lesson: 6 },
  { kanji: '早', meaning: 'korai / gyors', onyomi: 'ソウ', kunyomi: 'はや', romaji: 'haya / sou', jlpt: 'N4', lesson: 6 },
  { kanji: '世', meaning: 'világ / korszak', onyomi: 'セイ・セ', kunyomi: 'よ', romaji: 'yo / sei', jlpt: 'N4', lesson: 6 },
  { kanji: '自', meaning: 'önmaga', onyomi: 'ジ・シ', kunyomi: 'みずか', romaji: 'mizuka / ji', jlpt: 'N4', lesson: 6 },
  { kanji: '朝', meaning: 'reggel', onyomi: 'チョウ', kunyomi: 'あさ', romaji: 'asa / chou', jlpt: 'N4', lesson: 6 },
  { kanji: '員', meaning: 'tag / alkalmazott', onyomi: 'イン', kunyomi: '', romaji: 'in', jlpt: 'N4', lesson: 6 },
  { kanji: '元', meaning: 'eredet / alap', onyomi: 'ゲン・ガン', kunyomi: 'もと', romaji: 'moto / gen', jlpt: 'N4', lesson: 6 },
  { kanji: '的', meaning: 'cél / -szerű', onyomi: 'テキ', kunyomi: 'まと', romaji: 'mato / teki', jlpt: 'N4', lesson: 6 },
  { kanji: '真', meaning: 'igazság / tiszta', onyomi: 'シン', kunyomi: 'ま', romaji: 'ma / shin', jlpt: 'N4', lesson: 6 },
  { kanji: '工', meaning: 'munka / gyártás', onyomi: 'コウ・ク', kunyomi: '', romaji: 'kou', jlpt: 'N4', lesson: 6 },
  { kanji: '有', meaning: 'létezik / birtokol', onyomi: 'ユウ・ウ', kunyomi: 'あ', romaji: 'a / yuu', jlpt: 'N4', lesson: 6 },
  { kanji: '切', meaning: 'vág / éles', onyomi: 'セツ・サイ', kunyomi: 'き', romaji: 'ki / setsu', jlpt: 'N4', lesson: 7 },
  { kanji: '別', meaning: 'külön / elválik', onyomi: 'ベツ', kunyomi: 'わか', romaji: 'waka / betsu', jlpt: 'N4', lesson: 7 },
  { kanji: '町', meaning: 'város / negyed', onyomi: 'チョウ', kunyomi: 'まち', romaji: 'machi / chou', jlpt: 'N4', lesson: 7 },
  { kanji: '兄', meaning: 'báty', onyomi: 'ケイ・キョウ', kunyomi: 'あに', romaji: 'ani / kei', jlpt: 'N4', lesson: 7 },
  { kanji: '少', meaning: 'kevés', onyomi: 'ショウ', kunyomi: 'すく・すこ', romaji: 'suku / shou', jlpt: 'N4', lesson: 7 },
  { kanji: '多', meaning: 'sok', onyomi: 'タ', kunyomi: 'おお', romaji: 'oo / ta', jlpt: 'N4', lesson: 7 },
  { kanji: '夕', meaning: 'este', onyomi: 'セキ', kunyomi: 'ゆう', romaji: 'yuu / seki', jlpt: 'N4', lesson: 7 },
  { kanji: '魚', meaning: 'hal', onyomi: 'ギョ', kunyomi: 'うお・さかな', romaji: 'sakana / gyo', jlpt: 'N4', lesson: 7 },
  { kanji: '黒', meaning: 'fekete', onyomi: 'コク', kunyomi: 'くろ', romaji: 'kuro / koku', jlpt: 'N4', lesson: 7 },
  { kanji: '同', meaning: 'ugyanaz', onyomi: 'ドウ', kunyomi: 'おな', romaji: 'ona / dou', jlpt: 'N4', lesson: 7 },
  { kanji: '字', meaning: 'karakter / betű', onyomi: 'ジ', kunyomi: 'あざ', romaji: 'ji / aza', jlpt: 'N4', lesson: 7 },
  { kanji: '安', meaning: 'olcsó / nyugodt', onyomi: 'アン', kunyomi: 'やす', romaji: 'yasu / an', jlpt: 'N4', lesson: 7 },
  { kanji: '味', meaning: 'íz', onyomi: 'ミ', kunyomi: 'あじ', romaji: 'aji / mi', jlpt: 'N4', lesson: 7 },
  { kanji: '妹', meaning: 'húg', onyomi: 'マイ', kunyomi: 'いもうと', romaji: 'imouto / mai', jlpt: 'N4', lesson: 7 },
  { kanji: '犬', meaning: 'kutya', onyomi: 'ケン', kunyomi: 'いぬ', romaji: 'inu / ken', jlpt: 'N4', lesson: 7 },
  { kanji: '牛', meaning: 'tehén', onyomi: 'ギュウ', kunyomi: 'うし', romaji: 'ushi / gyuu', jlpt: 'N4', lesson: 7 },
  { kanji: '特', meaning: 'különleges', onyomi: 'トク', kunyomi: '', romaji: 'toku', jlpt: 'N4', lesson: 8 },
  { kanji: '界', meaning: 'világ / határ', onyomi: 'カイ', kunyomi: '', romaji: 'kai', jlpt: 'N4', lesson: 8 },
  { kanji: '茶', meaning: 'tea', onyomi: 'チャ・サ', kunyomi: '', romaji: 'cha / sa', jlpt: 'N4', lesson: 8 },
  { kanji: '理', meaning: 'logika / értelem', onyomi: 'リ', kunyomi: 'ことわり', romaji: 'ri / kotowari', jlpt: 'N4', lesson: 8 },
  { kanji: '主', meaning: 'úr / fő', onyomi: 'シュ', kunyomi: 'ぬし・おも', romaji: 'omo / shu', jlpt: 'N4', lesson: 8 },
  { kanji: '注', meaning: 'önt / jegyzet', onyomi: 'チュウ', kunyomi: 'そそ', romaji: 'soso / chuu', jlpt: 'N4', lesson: 8 },
  { kanji: '道', meaning: 'út', onyomi: 'ドウ', kunyomi: 'みち', romaji: 'michi / dou', jlpt: 'N4', lesson: 8 },
  { kanji: '夏', meaning: 'nyár', onyomi: 'カ', kunyomi: 'なつ', romaji: 'natsu / ka', jlpt: 'N4', lesson: 8 },
  { kanji: '運', meaning: 'szerencse / mozgat', onyomi: 'ウン', kunyomi: 'はこ', romaji: 'hako / un', jlpt: 'N4', lesson: 8 },
  { kanji: '京', meaning: 'főváros', onyomi: 'キョウ・ケイ', kunyomi: 'みやこ', romaji: 'miyako / kyou', jlpt: 'N4', lesson: 8 },
  { kanji: '週', meaning: 'hét (időtartam)', onyomi: 'シュウ', kunyomi: '', romaji: 'shuu', jlpt: 'N4', lesson: 8 },
  { kanji: '売', meaning: 'elad', onyomi: 'バイ', kunyomi: 'う', romaji: 'u / bai', jlpt: 'N4', lesson: 8 },
  { kanji: '言', meaning: 'mond / szó', onyomi: 'ゲン・ゴン', kunyomi: 'い・こと', romaji: 'i / gen', jlpt: 'N4', lesson: 8 },
  { kanji: '計', meaning: 'terv / mér', onyomi: 'ケイ', kunyomi: 'はか', romaji: 'haka / kei', jlpt: 'N4', lesson: 8 },
  { kanji: '試', meaning: 'próbál / teszt', onyomi: 'シ', kunyomi: 'こころ・ため', romaji: 'tame / shi', jlpt: 'N4', lesson: 8 },
  { kanji: '止', meaning: 'megáll', onyomi: 'シ', kunyomi: 'と', romaji: 'to / shi', jlpt: 'N4', lesson: 8 },
  { kanji: '歩', meaning: 'sétál', onyomi: 'ホ', kunyomi: 'ある・あゆ', romaji: 'aru / ho', jlpt: 'N4', lesson: 9 },
  { kanji: '正', meaning: 'helyes / igaz', onyomi: 'セイ・ショウ', kunyomi: 'ただ', romaji: 'tada / sei', jlpt: 'N4', lesson: 9 },
  { kanji: '走', meaning: 'fut', onyomi: 'ソウ', kunyomi: 'はし', romaji: 'hashi / sou', jlpt: 'N4', lesson: 9 },
  { kanji: '題', meaning: 'tárgy / cím', onyomi: 'ダイ', kunyomi: '', romaji: 'dai', jlpt: 'N4', lesson: 9 },
  { kanji: '建', meaning: 'épít', onyomi: 'ケン', kunyomi: 'た', romaji: 'ta / ken', jlpt: 'N4', lesson: 9 },
  { kanji: '姉', meaning: 'nővér', onyomi: 'シ', kunyomi: 'あね', romaji: 'ane / shi', jlpt: 'N4', lesson: 9 },
  { kanji: '転', meaning: 'gurul / fordul', onyomi: 'テン', kunyomi: 'ころ', romaji: 'koro / ten', jlpt: 'N4', lesson: 9 },
  { kanji: '冬', meaning: 'tél', onyomi: 'トウ', kunyomi: 'ふゆ', romaji: 'fuyu / tou', jlpt: 'N4', lesson: 9 },
  { kanji: '立', meaning: 'feláll', onyomi: 'リツ', kunyomi: 'た', romaji: 'ta / ritsu', jlpt: 'N4', lesson: 9 },
  { kanji: '海', meaning: 'tenger', onyomi: 'カイ', kunyomi: 'うみ', romaji: 'umi / kai', jlpt: 'N4', lesson: 9 },
  { kanji: '歌', meaning: 'dal', onyomi: 'カ', kunyomi: 'うた', romaji: 'uta / ka', jlpt: 'N4', lesson: 9 },
  { kanji: '音', meaning: 'hang', onyomi: 'オン', kunyomi: 'おと・ね', romaji: 'oto / on', jlpt: 'N4', lesson: 9 },
  { kanji: '方', meaning: 'irány / módszer', onyomi: 'ホウ', kunyomi: 'かた', romaji: 'kata / hou', jlpt: 'N4', lesson: 9 },
  { kanji: '地', meaning: 'föld / hely', onyomi: 'チ・ジ', kunyomi: '', romaji: 'chi / ji', jlpt: 'N4', lesson: 9 },
  { kanji: '風', meaning: 'szél / stílus', onyomi: 'フウ', kunyomi: 'かぜ', romaji: 'kaze / fuu', jlpt: 'N4', lesson: 9 },
  { kanji: '起', meaning: 'felkel / történik', onyomi: 'キ', kunyomi: 'お', romaji: 'o / ki', jlpt: 'N4', lesson: 9 },
  { kanji: '家', meaning: 'ház / otthon', onyomi: 'カ・ケ', kunyomi: 'いえ・や', romaji: 'ie / ka', jlpt: 'N4', lesson: 10 },
  { kanji: '場', meaning: 'hely / szituáció', onyomi: 'ジョウ', kunyomi: 'ば', romaji: 'ba / jou', jlpt: 'N4', lesson: 10 },
  { kanji: '洋', meaning: 'óceán / nyugati', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N4', lesson: 10 },
  { kanji: '着', meaning: 'felvesz (ruhát) / megérkezik', onyomi: 'チャク', kunyomi: 'き・つ', romaji: 'ki / chaku', jlpt: 'N4', lesson: 10 },
  { kanji: '集', meaning: 'összegyűjt', onyomi: 'シュウ', kunyomi: 'あつ', romaji: 'atsu / shuu', jlpt: 'N4', lesson: 10 },
  { kanji: '習', meaning: 'tanul / gyakorol', onyomi: 'シュウ', kunyomi: 'なら', romaji: 'nara / shuu', jlpt: 'N4', lesson: 10 },
  { kanji: '曜', meaning: 'hét napja', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N4', lesson: 10 },
  { kanji: '店', meaning: 'bolt', onyomi: 'テン', kunyomi: 'みせ', romaji: 'mise / ten', jlpt: 'N4', lesson: 10 },
  { kanji: '心', meaning: 'szív / lélek', onyomi: 'シン', kunyomi: 'こころ', romaji: 'kokoro / shin', jlpt: 'N4', lesson: 10 },
  { kanji: '思', meaning: 'gondol', onyomi: 'シ', kunyomi: 'おも', romaji: 'omo / shi', jlpt: 'N4', lesson: 10 },
  { kanji: '意', meaning: 'szándék / jelentés', onyomi: 'イ', kunyomi: '', romaji: 'i', jlpt: 'N4', lesson: 10 },
  { kanji: '手', meaning: 'kéz', onyomi: 'シュ', kunyomi: 'て', romaji: 'te / shu', jlpt: 'N4', lesson: 10 },
  { kanji: '持', meaning: 'tart / birtokol', onyomi: 'ジ', kunyomi: 'も', romaji: 'mo / ji', jlpt: 'N4', lesson: 10 },
  { kanji: '研', meaning: 'kutat / csiszol', onyomi: 'ケン', kunyomi: 'と', romaji: 'to / ken', jlpt: 'N4', lesson: 10 },
  { kanji: '広', meaning: 'széles / tágas', onyomi: 'コウ', kunyomi: 'ひろ', romaji: 'hiro / kou', jlpt: 'N4', lesson: 10 },
  { kanji: '台', meaning: 'állvány / gép', onyomi: 'ダイ・タイ', kunyomi: '', romaji: 'dai', jlpt: 'N4', lesson: 10 },
  { kanji: '始', meaning: 'kezdődik', onyomi: 'シ', kunyomi: 'はじ', romaji: 'haji / shi', jlpt: 'N4', lesson: 11 },
  { kanji: '去', meaning: 'elmúlik / elhagy', onyomi: 'キョ・コ', kunyomi: 'さ', romaji: 'sa / kyo', jlpt: 'N4', lesson: 11 },
  { kanji: '会', meaning: 'találkozik / társaság', onyomi: 'カイ', kunyomi: 'あ', romaji: 'a / kai', jlpt: 'N4', lesson: 11 },
  { kanji: '室', meaning: 'szoba', onyomi: 'シツ', kunyomi: 'むろ', romaji: 'muro / shitsu', jlpt: 'N4', lesson: 11 },
  { kanji: '公', meaning: 'nyilvános', onyomi: 'コウ', kunyomi: 'おおやけ', romaji: 'ooyake / kou', jlpt: 'N4', lesson: 11 },
  { kanji: '堂', meaning: 'terem / csarnok', onyomi: 'ドウ', kunyomi: '', romaji: 'dou', jlpt: 'N4', lesson: 11 },
  { kanji: '死', meaning: 'halál', onyomi: 'シ', kunyomi: 'し', romaji: 'shi', jlpt: 'N4', lesson: 11 },
  { kanji: '買', meaning: 'vásárol', onyomi: 'バイ', kunyomi: 'か', romaji: 'ka / bai', jlpt: 'N4', lesson: 11 },
  { kanji: '力', meaning: 'erő', onyomi: 'リョク・リキ', kunyomi: 'ちから', romaji: 'chikara / ryoku', jlpt: 'N4', lesson: 11 },
  { kanji: '待', meaning: 'vár', onyomi: 'タイ', kunyomi: 'ま', romaji: 'ma / tai', jlpt: 'N4', lesson: 11 },
  { kanji: '秋', meaning: 'ősz', onyomi: 'シュウ', kunyomi: 'あき', romaji: 'aki / shuu', jlpt: 'N4', lesson: 11 },
  { kanji: '私', meaning: 'én', onyomi: 'シ', kunyomi: 'わたし・わたくし', romaji: 'watashi / shi', jlpt: 'N4', lesson: 11 },
  { kanji: '答', meaning: 'válasz', onyomi: 'トウ', kunyomi: 'こた', romaji: 'kota / tou', jlpt: 'N4', lesson: 11 },
  { kanji: '住', meaning: 'lakik', onyomi: 'ジュウ', kunyomi: 'す', romaji: 'su / juu', jlpt: 'N4', lesson: 11 },
  { kanji: '体', meaning: 'test', onyomi: 'タイ', kunyomi: 'からだ', romaji: 'karada / tai', jlpt: 'N4', lesson: 11 },
  { kanji: '仕', meaning: 'szolgál / munka', onyomi: 'シ', kunyomi: 'つか', romaji: 'tsuka / shi', jlpt: 'N4', lesson: 11 },
  { kanji: '使', meaning: 'használ', onyomi: 'シ', kunyomi: 'つか', romaji: 'tsuka / shi', jlpt: 'N4', lesson: 12 },
  { kanji: '代', meaning: 'korszak / helyett', onyomi: 'ダイ・タイ', kunyomi: 'か', romaji: 'ka / dai', jlpt: 'N4', lesson: 12 },
  { kanji: '貸', meaning: 'kölcsönad', onyomi: 'タイ', kunyomi: 'か', romaji: 'ka / tai', jlpt: 'N4', lesson: 12 },
  { kanji: '花', meaning: 'virág', onyomi: 'カ', kunyomi: 'はな', romaji: 'hana / ka', jlpt: 'N4', lesson: 12 },
  { kanji: '肉', meaning: 'hús', onyomi: 'ニク', kunyomi: '', romaji: 'niku', jlpt: 'N4', lesson: 12 },
  { kanji: '以', meaning: 'által / -tól', onyomi: 'イ', kunyomi: '', romaji: 'i', jlpt: 'N4', lesson: 12 },
  { kanji: '夜', meaning: 'éjszaka', onyomi: 'ヤ', kunyomi: 'よる・よ', romaji: 'yoru / ya', jlpt: 'N4', lesson: 12 },
  { kanji: '旅', meaning: 'utazás', onyomi: 'リョ', kunyomi: 'たび', romaji: 'tabi / ryo', jlpt: 'N4', lesson: 12 },
  { kanji: '物', meaning: 'dolog / tárgy', onyomi: 'ブツ・モツ', kunyomi: 'もの', romaji: 'mono / butsu', jlpt: 'N4', lesson: 12 },
  { kanji: '屋', meaning: 'bolt / tető', onyomi: 'オク', kunyomi: 'や', romaji: 'ya / oku', jlpt: 'N4', lesson: 12 },
  { kanji: '昼', meaning: 'dél / nappal', onyomi: 'チュウ', kunyomi: 'ひる', romaji: 'hiru / chuu', jlpt: 'N4', lesson: 12 },
  { kanji: '社', meaning: 'társaság / szentély', onyomi: 'シャ', kunyomi: 'やしろ', romaji: 'yashiro / sha', jlpt: 'N4', lesson: 12 },
  { kanji: '近', meaning: 'közeli', onyomi: 'キン', kunyomi: 'ちか', romaji: 'chika / kin', jlpt: 'N4', lesson: 12 },
  { kanji: '質', meaning: 'minőség / anyag', onyomi: 'シツ・シチ', kunyomi: '', romaji: 'shitsu', jlpt: 'N4', lesson: 12 },
  { kanji: '作', meaning: 'készít', onyomi: 'サク・サ', kunyomi: 'つく', romaji: 'tsuku / saku', jlpt: 'N4', lesson: 12 },
  { kanji: '急', meaning: 'sürgős / siet', onyomi: 'キュウ', kunyomi: 'いそ', romaji: 'iso / kyuu', jlpt: 'N4', lesson: 12 },
  { kanji: '事', meaning: 'dolog (absztrakt)', onyomi: 'ジ・ズ', kunyomi: 'こと', romaji: 'koto / ji', jlpt: 'N4', lesson: 12 },
  { kanji: '画', meaning: 'kép / vonás', onyomi: 'ガ・カク', kunyomi: '', romaji: 'ga / kaku', jlpt: 'N4', lesson: 12 },
  { kanji: '料', meaning: 'díj / anyag', onyomi: 'リョウ', kunyomi: '', romaji: 'ryou', jlpt: 'N4', lesson: 12 },
  { kanji: '図', meaning: 'rajz / terv', onyomi: 'ズ・ト', kunyomi: 'はか', romaji: 'haka / zu', jlpt: 'N4', lesson: 12 },
  { kanji: '用', meaning: 'használat / dolga van', onyomi: 'ヨウ', kunyomi: 'もち', romaji: 'mochi / you', jlpt: 'N4', lesson: 12 },
  { kanji: '借', meaning: 'kölcsönkér', onyomi: 'シャク', kunyomi: 'か', romaji: 'ka / shaku', jlpt: 'N4', lesson: 12 },
  { kanji: '度', meaning: 'fok / alkalom', onyomi: 'ド・ト', kunyomi: 'たび', romaji: 'tabi / do', jlpt: 'N4', lesson: 12 },
  { kanji: '不', meaning: 'nem (tagadás)', onyomi: 'フ・ブ', kunyomi: '', romaji: 'fu / bu', jlpt: 'N4', lesson: 12 },
  { kanji: '族', meaning: 'törzs / család', onyomi: 'ゾク', kunyomi: '', romaji: 'zoku', jlpt: 'N4', lesson: 13 },
  { kanji: '知', meaning: 'tud / ismer', onyomi: 'チ', kunyomi: 'し', romaji: 'shi / chi', jlpt: 'N4', lesson: 13 },
  { kanji: '帰', meaning: 'hazatér', onyomi: 'キ', kunyomi: 'かえ', romaji: 'kae / ki', jlpt: 'N4', lesson: 13 },
  { kanji: '強', meaning: 'erős', onyomi: 'キョウ・ゴウ', kunyomi: 'つよ', romaji: 'tsuyo / kyou', jlpt: 'N4', lesson: 13 },
  { kanji: '弟', meaning: 'öccs', onyomi: 'テイ・ダイ', kunyomi: 'おとうと', romaji: 'otouto / tei', jlpt: 'N4', lesson: 13 },
  { kanji: '写', meaning: 'másol / fotóz', onyomi: 'シャ', kunyomi: 'うつ', romaji: 'utsu / sha', jlpt: 'N4', lesson: 13 },
  { kanji: '考', meaning: 'gondolkodik', onyomi: 'コウ', kunyomi: 'かんが', romaji: 'kanga / kou', jlpt: 'N4', lesson: 13 },
  { kanji: '教', meaning: 'tanít', onyomi: 'キョウ', kunyomi: 'おし', romaji: 'oshi / kyou', jlpt: 'N4', lesson: 13 },
  { kanji: '者', meaning: 'személy / valaki', onyomi: 'シャ', kunyomi: 'もの', romaji: 'mono / sha', jlpt: 'N4', lesson: 13 },
  { kanji: '足', meaning: 'láb / elegendő', onyomi: 'ソク', kunyomi: 'あし・た', romaji: 'ashi / soku', jlpt: 'N4', lesson: 13 },
  { kanji: '院', meaning: 'intézmény', onyomi: 'イン', kunyomi: '', romaji: 'in', jlpt: 'N4', lesson: 13 },
  { kanji: '空', meaning: 'ég / üres', onyomi: 'クウ', kunyomi: 'そら・あ', romaji: 'sora / kuu', jlpt: 'N4', lesson: 13 },
  { kanji: '究', meaning: 'kutat', onyomi: 'キュウ', kunyomi: 'きわ', romaji: 'kiwa / kyuu', jlpt: 'N4', lesson: 13 },
  { kanji: '終', meaning: 'vége', onyomi: 'シュウ', kunyomi: 'お', romaji: 'o / shuu', jlpt: 'N4', lesson: 13 },
  { kanji: '服', meaning: 'ruha', onyomi: 'フク', kunyomi: '', romaji: 'fuku', jlpt: 'N4', lesson: 13 },
  { kanji: '通', meaning: 'áthalad / ingázik', onyomi: 'ツウ', kunyomi: 'とお・かよ', romaji: 'too / tsuu', jlpt: 'N4', lesson: 13 },
  { kanji: '銀', meaning: 'ezüst', onyomi: 'ギン', kunyomi: '', romaji: 'gin', jlpt: 'N4', lesson: 13 },
  { kanji: '飯', meaning: 'főtt rijs / étel', onyomi: 'ハン', kunyomi: 'めし', romaji: 'meshi / han', jlpt: 'N4', lesson: 13 },
  { kanji: '飲', meaning: 'iszik', onyomi: 'イン', kunyomi: 'の', romaji: 'no / in', jlpt: 'N4', lesson: 13 },
  { kanji: '館', meaning: 'épület / csarnok', onyomi: 'カン', kunyomi: 'やかた', romaji: 'yakata / kan', jlpt: 'N4', lesson: 13 },
  { kanji: '新', meaning: 'új', onyomi: 'シン', kunyomi: 'あたら', romaji: 'atara / shin', jlpt: 'N4', lesson: 13 },
  { kanji: '親', meaning: 'szülő / közeli', onyomi: 'シン', kunyomi: 'おや・した', romaji: 'oya / shin', jlpt: 'N4', lesson: 13 },
  { kanji: '青', meaning: 'kék', onyomi: 'セイ・ショウ', kunyomi: 'あお', romaji: 'ao / sei', jlpt: 'N4', lesson: 13 },
  { kanji: '春', meaning: 'tavasz', onyomi: 'シュン', kunyomi: 'はる', romaji: 'haru / shun', jlpt: 'N4', lesson: 13 },
  { kanji: '漢', meaning: 'kínai', onyomi: 'カン', kunyomi: '', romaji: 'kan', jlpt: 'N4', lesson: 13 },
  { kanji: '野', meaning: 'mező', onyomi: 'ヤ', kunyomi: 'の', romaji: 'no / ya', jlpt: 'N4', lesson: 13 },
  { kanji: '問', meaning: 'kérdez / probléma', onyomi: 'モン', kunyomi: 'と', romaji: 'to / mon', jlpt: 'N4', lesson: 13 },
  { kanji: '開', meaning: 'nyit', onyomi: 'カイ', kunyomi: 'ひら・あ', romaji: 'hira / kai', jlpt: 'N4', lesson: 13 },
  { kanji: '重', meaning: 'nehéz / súlyos', onyomi: 'ジュウ・チョウ', kunyomi: 'おも・かさ', romaji: 'omo / juu', jlpt: 'N4', lesson: 13 },
  { kanji: '動', meaning: 'mozog', onyomi: 'ドウ', kunyomi: 'うご', romaji: 'ugo / dou', jlpt: 'N4', lesson: 13 },
  { kanji: '病', meaning: 'betegség', onyomi: 'ビョウ', kunyomi: 'やまい', romaji: 'yamai / byou', jlpt: 'N4', lesson: 13 },
  { kanji: '医', meaning: 'orvos / orvostudomány', onyomi: 'イ', kunyomi: '', romaji: 'i', jlpt: 'N4', lesson: 13 },
  { kanji: '発', meaning: 'indul / kibocsát', onyomi: 'ハツ・ホツ', kunyomi: '', romaji: 'hatsu', jlpt: 'N4', lesson: 13 },
  { kanji: '文', meaning: 'szöveg / irodalom', onyomi: 'ブン・モン', kunyomi: 'ふみ', romaji: 'fumi / bun', jlpt: 'N4', lesson: 13 },
  { kanji: '楽', meaning: 'kényelmes / zene', onyomi: 'ガク・ラク', kunyomi: 'たの', romaji: 'tano / raku', jlpt: 'N4', lesson: 13 },
  { kanji: '英', meaning: 'angol / kiváló', onyomi: 'エイ', kunyomi: '', romaji: 'ei', jlpt: 'N4', lesson: 13 },
  { kanji: '映', meaning: 'visszatükröz / vetít', onyomi: 'エイ', kunyomi: 'うつ', romaji: 'utsu / ei', jlpt: 'N4', lesson: 13 },
  { kanji: '赤', meaning: 'piros', onyomi: 'セキ・シャク', kunyomi: 'あか', romaji: 'aka / seki', jlpt: 'N4', lesson: 13 },
  { kanji: '色', meaning: 'szín', onyomi: 'ショク・シキ', kunyomi: 'いろ', romaji: 'iro / shoku', jlpt: 'N4', lesson: 13 },
  { kanji: '業', meaning: 'üzlet / hivatás', onyomi: 'ギョウ・ゴウ', kunyomi: 'わざ', romaji: 'waza / gyou', jlpt: 'N4', lesson: 13 },
  { kanji: '悪', meaning: 'rossz', onyomi: 'アク・オ', kunyomi: 'わる', romaji: 'waru / aku', jlpt: 'N4', lesson: 13 },
  { kanji: '紙', meaning: 'papír', onyomi: 'シ', kunyomi: 'かみ', romaji: 'kami / shi', jlpt: 'N4', lesson: 13 },
  { kanji: '鳥', meaning: 'madár', onyomi: 'チョウ', kunyomi: 'とり', romaji: 'tori / chou', jlpt: 'N4', lesson: 13 },
  { kanji: '勉', meaning: 'igyekszik / tanul', onyomi: 'ベン', kunyomi: 'つと', romaji: 'tsuto / ben', jlpt: 'N4', lesson: 13 },
  { kanji: '験', meaning: 'teszt / vizsga', onyomi: 'ケン・ゲン', kunyomi: '', romaji: 'ken', jlpt: 'N4', lesson: 13 },
  { kanji: '駅', meaning: 'állomás', onyomi: 'エキ', kunyomi: '', romaji: 'eki', jlpt: 'N4', lesson: 13 },
  { kanji: '送', meaning: 'küld', onyomi: 'ソウ', kunyomi: 'おく', romaji: 'oku / sou', jlpt: 'N4', lesson: 13 },

  // ════ JLPT N3 (378 db - A képeken lévő összes elem) ════
  { kanji: '負', meaning: 'veszít / vereség', onyomi: 'フ', kunyomi: 'ま・お', romaji: 'ma / fu', jlpt: 'N3', lesson: 14 },
  { kanji: '首', meaning: 'nyak / vezető', onyomi: 'シュ', kunyomi: 'くび', romaji: 'kubi / shu', jlpt: 'N3', lesson: 14 },
  { kanji: '直', meaning: 'egyenes / javít', onyomi: 'チョク・ジキ', kunyomi: 'なお・ただ', romaji: 'nao / choku', jlpt: 'N3', lesson: 14 },
  { kanji: '具', meaning: 'eszköz / összetevő', onyomi: 'グ', kunyomi: 'そな', romaji: 'gu', jlpt: 'N3', lesson: 14 },
  { kanji: '可', meaning: 'lehetséges / -ható', onyomi: 'カ', kunyomi: 'べ', romaji: 'ka', jlpt: 'N3', lesson: 14 },
  { kanji: '頂', meaning: 'csúcs / kap (szerényen)', onyomi: 'チョウ', kunyomi: 'いただ', romaji: 'itada / chou', jlpt: 'N3', lesson: 14 },
  { kanji: '好', meaning: 'kedvel / kedvező', onyomi: 'コウ', kunyomi: 'す・よ', romaji: 'su / kou', jlpt: 'N3', lesson: 14 },
  { kanji: '石', meaning: 'kő', onyomi: 'セキ・シャク', kunyomi: 'いし', romaji: 'ishi / seki', jlpt: 'N3', lesson: 14 },
  { kanji: '光', meaning: 'fény', onyomi: 'コウ', kunyomi: 'ひかり・ひか', romaji: 'hikari / kou', jlpt: 'N3', lesson: 14 },
  { kanji: '太', meaning: 'vastag / kövér', onyomi: 'タイ・タ', kunyomi: 'ふと', romaji: 'futo / tai', jlpt: 'N3', lesson: 14 },
  { kanji: '原', meaning: 'mező / eredet', onyomi: 'ゲン', kunyomi: 'はら', romaji: 'hara / gen', jlpt: 'N3', lesson: 14 },
  { kanji: '願', meaning: 'kér / kívánság', onyomi: 'ガン', kunyomi: 'ねが', romaji: 'nega / gan', jlpt: 'N3', lesson: 14 },
  { kanji: '泳', meaning: 'úszik', onyomi: 'エイ', kunyomi: 'およ', romaji: 'oyo / ei', jlpt: 'N3', lesson: 14 },
  { kanji: '活', meaning: 'élénk / élet', onyomi: 'カツ', kunyomi: 'い', romaji: 'katsu', jlpt: 'N3', lesson: 14 },
  { kanji: '消', meaning: 'eltűnik / elolt', onyomi: 'ショウ', kunyomi: 'き・け', romaji: 'ki / shou', jlpt: 'N3', lesson: 14 },
  { kanji: '点', meaning: 'pont', onyomi: 'テン', kunyomi: 'つ', romaji: 'ten', jlpt: 'N3', lesson: 14 },
  { kanji: '向', meaning: 'felé fordul / irány', onyomi: 'コウ', kunyomi: 'む', romaji: 'mu / kou', jlpt: 'N3', lesson: 14 },
  { kanji: '守', meaning: 'véd / megőriz', onyomi: 'シュ・ス', kunyomi: 'まも', romaji: 'mamo / shu', jlpt: 'N3', lesson: 14 },
  { kanji: '完', meaning: 'befejez / teljes', onyomi: 'カン', kunyomi: '', romaji: 'kan', jlpt: 'N3', lesson: 14 },
  { kanji: '寄', meaning: 'megáll / közeledik', onyomi: 'キ', kunyomi: 'よ', romaji: 'yo / ki', jlpt: 'N3', lesson: 14 },
  { kanji: '富', meaning: 'gazdagság', onyomi: 'フ・フウ', kunyomi: 'と・とみ', romaji: 'tomi / fu', jlpt: 'N3', lesson: 14 },
  { kanji: '相', meaning: 'kölcsönös / társ', onyomi: 'ソウ・ショウ', kunyomi: 'あい', romaji: 'ai / sou', jlpt: 'N3', lesson: 14 },
  { kanji: '未', meaning: 'még nem', onyomi: 'ミ', kunyomi: 'いま', romaji: 'mi', jlpt: 'N3', lesson: 14 },
  { kanji: '末', meaning: 'vég', onyomi: 'マツ・バツ', kunyomi: 'すえ', romaji: 'sue / matsu', jlpt: 'N3', lesson: 14 },
  { kanji: '若', meaning: 'fiatal', onyomi: 'ジャク', kunyomi: 'わか', romaji: 'waka / jaku', jlpt: 'N3', lesson: 14 },
  { kanji: '草', meaning: 'fű', onyomi: 'ソウ', kunyomi: 'くさ', romaji: 'kusa / sou', jlpt: 'N3', lesson: 14 },
  { kanji: '苦', meaning: 'keserű / szenvedés', onyomi: 'ク', kunyomi: 'くる・にが', romaji: 'kuru / ku', jlpt: 'N3', lesson: 14 },
  { kanji: '葉', meaning: 'levél', onyomi: 'ヨウ', kunyomi: 'は', romaji: 'ha / you', jlpt: 'N3', lesson: 14 },
  { kanji: '暮', meaning: 'megél / sötétedik', onyomi: 'ボ', kunyomi: 'く', romaji: 'ku / bo', jlpt: 'N3', lesson: 14 },
  { kanji: '状', meaning: 'állapot / levél forma', onyomi: 'ジョウ', kunyomi: '', romaji: 'jou', jlpt: 'N3', lesson: 14 },
  { kanji: '然', meaning: 'úgy / természetes', onyomi: 'ゼン・ネン', kunyomi: 'しか', romaji: 'zen', jlpt: 'N3', lesson: 14 },
  { kanji: '猫', meaning: 'macska', onyomi: 'ビョウ', kunyomi: 'ねこ', romaji: 'neko / byou', jlpt: 'N3', lesson: 14 },
  { kanji: '告', meaning: 'jelent / közöl', onyomi: 'コク', kunyomi: 'つ', romaji: 'tsu / koku', jlpt: 'N3', lesson: 14 },
  { kanji: '洗', meaning: 'mos', onyomi: 'セン', kunyomi: 'あら', romaji: 'ara / sen', jlpt: 'N3', lesson: 14 },
  { kanji: '合', meaning: 'illeszkedik / egyesít', onyomi: 'ゴウ・ガッ', kunyomi: 'あ', romaji: 'a / gou', jlpt: 'N3', lesson: 14 },
  { kanji: '王', meaning: 'király', onyomi: 'オウ', kunyomi: '', romaji: 'ou', jlpt: 'N3', lesson: 14 },
  { kanji: '現', meaning: 'megjelenik / jelenlegi', onyomi: 'ゲン', kunyomi: 'あらわ・いま', romaji: 'gen', jlpt: 'N3', lesson: 14 },
  { kanji: '全', meaning: 'egész / teljes', onyomi: 'ゼン', kunyomi: 'まった', romaji: 'zen', jlpt: 'N3', lesson: 14 },
  { kanji: '逃', meaning: 'elmenekül', onyomi: 'トウ', kunyomi: 'に・のが', romaji: 'ni / tou', jlpt: 'N3', lesson: 14 },
  { kanji: '連', meaning: 'összeköt / kísér', onyomi: 'レン', kunyomi: 'つ', romaji: 'tsu / ren', jlpt: 'N3', lesson: 14 },
  { kanji: '格', meaning: 'stílus / rang', onyomi: 'カク', kunyomi: '', romaji: 'kaku', jlpt: 'N3', lesson: 15 },
  { kanji: '客', meaning: 'vendég / ügyfél', onyomi: 'キャク・カク', kunyomi: '', romaji: 'kyaku', jlpt: 'N3', lesson: 15 },
  { kanji: '処', meaning: 'hely / kezelés', onyomi: 'ショ', kunyomi: 'ところ', romaji: 'sho', jlpt: 'N3', lesson: 15 },
  { kanji: '落', meaning: 'leesik / leejt', onyomi: 'ラク', kunyomi: 'お', romaji: 'ochiru / raku', jlpt: 'N3', lesson: 15 },
  { kanji: '夢', meaning: 'álom', onyomi: 'ム', kunyomi: 'ゆめ', romaji: 'yume / mu', jlpt: 'N3', lesson: 15 },
  { kanji: '景', meaning: 'látvány / táj', onyomi: 'ケイ', kunyomi: '', romaji: 'kei', jlpt: 'N3', lesson: 15 },
  { kanji: '覚', meaning: 'emlékszik / ébred', onyomi: 'カク', kunyomi: 'おぼ・さ', romaji: 'oboeru / kaku', jlpt: 'N3', lesson: 15 },
  { kanji: '敗', meaning: 'vereség / kudarc', onyomi: 'ハイ', kunyomi: 'やぶ', romaji: 'yabureru / hai', jlpt: 'N3', lesson: 15 },
  { kanji: '警', meaning: 'figyelmeztet / rendőrség', onyomi: 'ケイ', kunyomi: '', romaji: 'kei', jlpt: 'N3', lesson: 15 },
  { kanji: '調', meaning: 'vizsgál / hangnem', onyomi: 'チョウ', kunyomi: 'しら', romaji: 'shiraberu / chou', jlpt: 'N3', lesson: 15 },
  { kanji: '談', meaning: 'beszélgetés / tárgyalás', onyomi: 'ダン', kunyomi: '', romaji: 'dan', jlpt: 'N3', lesson: 15 },
  { kanji: '式', meaning: 'ceremónia / stílus', onyomi: 'シキ', kunyomi: '', romaji: 'shiki', jlpt: 'N3', lesson: 15 },
  { kanji: '成', meaning: 'válik valamivé', onyomi: 'セイ・ジョウ', kunyomi: 'な', romaji: 'naru / sei', jlpt: 'N3', lesson: 15 },
  { kanji: '政', meaning: 'politika / kormányzás', onyomi: 'セイ・ショウ', kunyomi: 'まつりごと', romaji: 'sei', jlpt: 'N3', lesson: 15 },
  { kanji: '定', meaning: 'rögzít / eldönt', onyomi: 'テイ・ジョウ', kunyomi: 'さだ', romaji: 'sada / tei', jlpt: 'N3', lesson: 15 },
  { kanji: '越', meaning: 'átlép / túllép', onyomi: 'エツ', kunyomi: 'こ', romaji: 'koeru / etsu', jlpt: 'N3', lesson: 15 },
  { kanji: '遠', meaning: 'messzi / távoli', onyomi: 'エン', kunyomi: 'とお', romaji: 'tooi / en', jlpt: 'N3', lesson: 15 },
  { kanji: '初', meaning: 'első / kezdet', onyomi: 'ショ', kunyomi: 'はじ・はつ', romaji: 'hajime / sho', jlpt: 'N3', lesson: 15 },
  { kanji: '市', meaning: 'város / piac', onyomi: 'シ', kunyomi: 'いち', romaji: 'shi / ichi', jlpt: 'N3', lesson: 15 },
  { kanji: '制', meaning: 'rendszer / szabályozás', onyomi: 'セイ', kunyomi: '', romaji: 'sei', jlpt: 'N3', lesson: 15 },
  { kanji: '商', meaning: 'kereskedelem', onyomi: 'ショウ', kunyomi: 'あきな', romaji: 'shou', jlpt: 'N3', lesson: 15 },
  { kanji: '適', meaning: 'megfelelő / alkalmas', onyomi: 'テキ', kunyomi: '', romaji: 'teki', jlpt: 'N3', lesson: 15 },
  { kanji: '背', meaning: 'hát / magasság', onyomi: 'ハイ', kunyomi: 'せ・せい', romaji: 'se / hai', jlpt: 'N3', lesson: 15 },
  { kanji: '皆', meaning: 'mindenki', onyomi: 'カイ', kunyomi: 'みな', romaji: 'mina', jlpt: 'N3', lesson: 15 },
  { kanji: '腹', meaning: 'has', onyomi: 'フク', kunyomi: 'はら', romaji: 'hara / fuku', jlpt: 'N3', lesson: 15 },
  { kanji: '欠', meaning: 'hiányzik / ásít', onyomi: 'ケツ', kunyomi: 'か', romaji: 'kakeru / ketsu', jlpt: 'N3', lesson: 15 },
  { kanji: '吹', meaning: 'fúj (szél)', onyomi: 'スイ', kunyomi: 'ふ', romaji: 'fuku / sui', jlpt: 'N3', lesson: 15 },
  { kanji: '次', meaning: 'következő', onyomi: 'ジ・シ', kunyomi: 'つぎ', romaji: 'tsugi / ji', jlpt: 'N3', lesson: 15 },
  { kanji: '資', meaning: 'forrás / tőke', onyomi: 'シ', kunyomi: '', romaji: 'shi', jlpt: 'N3', lesson: 15 },
  { kanji: '暗', meaning: 'sötét', onyomi: 'アン', kunyomi: 'くら', romaji: 'kurai / an', jlpt: 'N3', lesson: 15 },
  { kanji: '識', meaning: 'ismeret / tudás', onyomi: 'シキ', kunyomi: '', romaji: 'shiki', jlpt: 'N3', lesson: 15 },
  { kanji: '亡', meaning: 'meghal / elhunyt', onyomi: 'ボウ・モウ', kunyomi: 'な', romaji: 'nakunaru / bou', jlpt: 'N3', lesson: 15 },
  { kanji: '望', meaning: 'remény / elvárás', onyomi: 'ボウ・モウ', kunyomi: 'のぞ', romaji: 'nozomu / bou', jlpt: 'N3', lesson: 16 },
  { kanji: '訪', meaning: 'meglátogat', onyomi: 'ホウ', kunyomi: 'たず・おとず', romaji: 'tazuneru / hou', jlpt: 'N3', lesson: 16 },
  { kanji: '放', meaning: 'elenged / sugároz', onyomi: 'ホウ', kunyomi: 'はな', romaji: 'hanasu / hou', jlpt: 'N3', lesson: 16 },
  { kanji: '説', meaning: 'elmélet / magyarázat', onyomi: 'セツ', kunyomi: 'と', romaji: 'setsu', jlpt: 'N3', lesson: 16 },
  { kanji: '増', meaning: 'növekszik / hozzáad', onyomi: 'ゾウ', kunyomi: 'ふ・ま', romaji: 'fueru / zou', jlpt: 'N3', lesson: 16 },
  { kanji: '歳', meaning: 'életkor / évek', onyomi: 'サイ・セイ', kunyomi: 'とし', romaji: 'sai', jlpt: 'N3', lesson: 16 },
  { kanji: '記', meaning: 'feljegyez', onyomi: 'キ', kunyomi: 'しる', romaji: 'shirusu / ki', jlpt: 'N3', lesson: 16 },
  { kanji: '美', meaning: 'gyönyörű', onyomi: 'ビ', kunyomi: 'うつく', romaji: 'utsukushii / bi', jlpt: 'N3', lesson: 16 },
  { kanji: '達', meaning: 'elér (célt) / többes szám', onyomi: 'タツ', kunyomi: 'たち', romaji: 'tatsu / tachi', jlpt: 'N3', lesson: 16 },
  { kanji: '差', meaning: 'különbség / mutat', onyomi: 'サ', kunyomi: 'さ', romaji: 'sa', jlpt: 'N3', lesson: 16 },
  { kanji: '進', meaning: 'halad / előrejut', onyomi: 'シン', kunyomi: 'すす', romaji: 'susumu / shin', jlpt: 'N3', lesson: 16 },
  { kanji: '雑', meaning: 'vegyes / apróság', onyomi: 'ザツ・ゾウ', kunyomi: '', romaji: 'zatsu', jlpt: 'N3', lesson: 16 },
  { kanji: '确', meaning: 'biztos / szilárd', onyomi: 'カク', kunyomi: 'たし', romaji: 'tashika / kaku', jlpt: 'N3', lesson: 16 },
  { kanji: '許', meaning: 'megenged', onyomi: 'キョ', kunyomi: 'ゆる', romaji: 'yurusu / kyo', jlpt: 'N3', lesson: 16 },
  { kanji: '権', meaning: 'jog / hatalom', onyomi: 'ケン・ゴン', kunyomi: '', romaji: 'ken', jlpt: 'N3', lesson: 16 },
  { kanji: '観', meaning: 'néz / szemlélet', onyomi: 'カン', kunyomi: 'み', romaji: 'kan', jlpt: 'N3', lesson: 16 },
  { kanji: '困', meaning: 'bajban van', onyomi: 'コン', kunyomi: 'こま', romaji: 'komaru / kon', jlpt: 'N3', lesson: 16 },
  { kanji: '因', meaning: 'ok / alapul', onyomi: 'イン', kunyomi: 'よ', romaji: 'in', jlpt: 'N3', lesson: 16 },
  { kanji: '園', meaning: 'kert / park', onyomi: 'エン', kunyomi: 'その', romaji: 'sono / en', jlpt: 'N3', lesson: 16 },
  { kanji: '回', meaning: 'forog / alkalom', onyomi: 'カイ', kunyomi: 'まわ', romaji: 'mawaru / kai', jlpt: 'N3', lesson: 16 },
  { kanji: '庭', meaning: 'udvar / kert', onyomi: 'テイ', kunyomi: 'にわ', romaji: 'niwa / tei', jlpt: 'N3', lesson: 16 },
  { kanji: '忘', meaning: 'elfelejt', onyomi: 'ボウ', kunyomi: 'わす', romaji: 'wasureru / bou', jlpt: 'N3', lesson: 16 },
  { kanji: '認', meaning: 'elismer / jóváhagy', onyomi: 'ニン', kunyomi: 'みと', romaji: 'mitomeru / nin', jlpt: 'N3', lesson: 16 },
  { kanji: '想', meaning: 'gondolat / képzelet', onyomi: 'ソウ・ソ', kunyomi: '', romaji: 'sou', jlpt: 'N3', lesson: 16 },
  { kanji: '息', meaning: 'lélegzet', onyomi: 'ソク', kunyomi: 'いき', romaji: 'iki / soku', jlpt: 'N3', lesson: 16 },
  { kanji: '恐', meaning: 'félelem', onyomi: 'キョウ', kunyomi: 'おそ', romaji: 'osore / kyou', jlpt: 'N3', lesson: 16 },
  { kanji: '感', meaning: 'érzés / benyomás', onyomi: 'カン', kunyomi: '', romaji: 'kan', jlpt: 'N3', lesson: 16 },
  { kanji: '忙', meaning: 'elfoglalt', onyomi: 'ボウ', kunyomi: 'いそが', romaji: 'isogashii / bou', jlpt: 'N3', lesson: 16 },
  { kanji: '怖', meaning: 'félelmetes / fél', onyomi: 'フ', kunyomi: 'こわ', romaji: 'kowai / fu', jlpt: 'N3', lesson: 16 },
  { kanji: '慣', meaning: 'megszokik', onyomi: 'カン', kunyomi: 'な', romaji: 'naru / kan', jlpt: 'N3', lesson: 16 },
  { kanji: '必', meaning: 'szükségszerű / biztosan', onyomi: 'ヒツ', kunyomi: 'かなら', romaji: 'kanarazu / hitsu', jlpt: 'N3', lesson: 16 },
  { kanji: '議', meaning: 'vita / tanácskozás', onyomi: 'ギ', kunyomi: '', romaji: 'gi', jlpt: 'N3', lesson: 16 },
  { kanji: '抱', meaning: 'ölel / tart', onyomi: 'ホウ', kunyomi: 'だ・いだ', romaji: 'daku / hou', jlpt: 'N3', lesson: 16 },
  { kanji: '招', meaning: 'meghív', onyomi: 'ショウ', kunyomi: 'まね', romaji: 'maneku / shou', jlpt: 'N3', lesson: 16 },
  { kanji: '打', meaning: 'üt / gépel', onyomi: 'ダ', kunyomi: 'う', romaji: 'utsu / da', jlpt: 'N3', lesson: 16 },
  { kanji: '指', meaning: 'ujj / mutat', onyomi: 'シ', kunyomi: 'ゆび・さ', romaji: 'yubi / shi', jlpt: 'N3', lesson: 16 },
  { kanji: '掛', meaning: 'felakaszt / rátűz', onyomi: 'カイ', kunyomi: 'か', romaji: 'kakeru', jlpt: 'N3', lesson: 16 },
  { kanji: '才', meaning: 'tehetség / életkor', onyomi: 'サイ', kunyomi: '', romaji: 'sai', jlpt: 'N3', lesson: 16 },
  { kanji: '財', meaning: 'vagyon / pénzügy', onyomi: 'ザイ・サイ', kunyomi: '', romaji: 'zai', jlpt: 'N3', lesson: 16 },
  { kanji: '存', meaning: 'létezik', onyomi: 'ソン・ゾン', kunyomi: '', romaji: 'zon', jlpt: 'N3', lesson: 16 },
  { kanji: '在', meaning: 'létezik / vhol tartózkodik', onyomi: 'ザイ', kunyomi: 'あ', romaji: 'zai', jlpt: 'N3', lesson: 17 },
  { kanji: '吸', meaning: 'szív / belélegez', onyomi: 'キュウ', kunyomi: 'す', romaji: 'su / kyuu', jlpt: 'N3', lesson: 17 },
  { kanji: '更', meaning: 'megújít / késő éjjel', onyomi: 'コウ', kunyomi: 'さら・ふ', romaji: 'sara / kou', jlpt: 'N3', lesson: 17 },
  { kanji: '怒', meaning: 'mérges', onyomi: 'ド', kunyomi: 'いか・おこ', romaji: 'oko / do', jlpt: 'N3', lesson: 17 },
  { kanji: '抜', meaning: 'kihúz / kivon', onyomi: 'バツ', kunyomi: 'ぬ', romaji: 'nuku / batsu', jlpt: 'N3', lesson: 17 },
  { kanji: '投', meaning: 'dob', onyomi: 'トウ', kunyomi: 'な', romaji: 'na / tou', jlpt: 'N3', lesson: 17 },
  { kanji: '支', meaning: 'támogat / ágazat', onyomi: 'シ', kunyomi: 'ささ', romaji: 'sasa / shi', jlpt: 'N3', lesson: 17 },
  { kanji: '反', meaning: 'ellenkezik / ellentét', onyomi: 'ハン・ホン', kunyomi: 'そ', romaji: 'han', jlpt: 'N3', lesson: 17 },
  { kanji: '返', meaning: 'visszatér / visszaad', onyomi: 'ヘン', kunyomi: 'かえ', romaji: 'kae / hen', jlpt: 'N3', lesson: 17 },
  { kanji: '浮', meaning: 'lebeg / úszik', onyomi: 'フ', kunyomi: 'う', romaji: 'uku / fu', jlpt: 'N3', lesson: 17 },
  { kanji: '受', meaning: 'kap / elfogad', onyomi: 'ジュ', kunyomi: 'う', romaji: 'ukeru / ju', jlpt: 'N3', lesson: 17 },
  { kanji: '愛', meaning: 'szeretet / szerelem', onyomi: 'アイ', kunyomi: '', romaji: 'ai', jlpt: 'N3', lesson: 17 },
  { kanji: '払', meaning: 'fizet / söpör', onyomi: 'フツ', kunyomi: 'はら', romaji: 'harau / hutsu', jlpt: 'N3', lesson: 17 },
  { kanji: '治', meaning: 'gyógyít / uralkodik', onyomi: 'ジ・チ', kunyomi: 'なお・おさ', romaji: 'naoru / ji', jlpt: 'N3', lesson: 17 },
  { kanji: '窓', meaning: 'ablak', onyomi: 'ソウ', kunyomi: 'まど', romaji: 'mado / sou', jlpt: 'N3', lesson: 17 },
  { kanji: '法', meaning: 'törvény / módszer', onyomi: 'ホウ', kunyomi: '', romaji: 'hou', jlpt: 'N3', lesson: 17 },
  { kanji: '到', meaning: 'megérkezik', onyomi: 'トウ', kunyomi: 'いた', romaji: 'tou', jlpt: 'N3', lesson: 17 },
  { kanji: '互', meaning: 'kölcsönös', onyomi: 'ゴ', kunyomi: 'たが', romaji: 'tagai / go', jlpt: 'N3', lesson: 17 },
  { kanji: '育', meaning: 'nevel / növekszik', onyomi: 'イク', kunyomi: 'そだ', romaji: 'sodatsu / iku', jlpt: 'N3', lesson: 17 },
  { kanji: '流', meaning: 'folyik / áramlat', onyomi: 'リュウ', kunyomi: 'なが', romaji: 'nagaru / ryuu', jlpt: 'N3', lesson: 17 },
  { kanji: '込', meaning: 'zsúfolt / belekerül', onyomi: '', kunyomi: 'こ', romaji: 'komu', jlpt: 'N3', lesson: 17 },
  { kanji: '貧', meaning: 'szegény', onyomi: 'ヒン', kunyomi: 'まず', romaji: 'mazushii / hin', jlpt: 'N3', lesson: 17 },
  { kanji: '容', meaning: 'tartalom / forma', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N3', lesson: 17 },
  { kanji: '欲', meaning: 'vágyik valamire', onyomi: 'ヨク', kunyomi: 'ほ', romaji: 'hoshii / yoku', jlpt: 'N3', lesson: 17 },
  { kanji: '常', meaning: 'szokásos / állandó', onyomi: 'ジョウ', kunyomi: 'つね', romaji: 'tsune / jou', jlpt: 'N3', lesson: 17 },
  { kanji: '破', meaning: 'eltör / elszakad', onyomi: 'ハ', kunyomi: 'やぶ', romaji: 'yaburu / ha', jlpt: 'N3', lesson: 17 },
  { kanji: '残', meaning: 'marad / hátrahagy', onyomi: 'ザン', kunyomi: 'のこ', romaji: 'nokoru / zan', jlpt: 'N3', lesson: 17 },
  { kanji: '列', meaning: 'sor / oszlop', onyomi: 'レツ', kunyomi: '', romaji: 'retsu', jlpt: 'N3', lesson: 17 },
  { kanji: '耳', meaning: 'fül', onyomi: 'ジ', kunyomi: 'みみ', romaji: 'mimi / ji', jlpt: 'N3', lesson: 17 },
  { kanji: '取', meaning: 'elvesz / szerez', onyomi: 'シュ', kunyomi: 'と', romaji: 'toru / shu', jlpt: 'N3', lesson: 17 },
  { kanji: '最', meaning: 'leginkább / leg-', onyomi: 'サイ', kunyomi: 'もっと', romaji: 'motto / sai', jlpt: 'N3', lesson: 17 },
  { kanji: '恥', meaning: 'szégyen', onyomi: 'チ', kunyomi: 'は', romaji: 'haji / chi', jlpt: 'N3', lesson: 17 },
  { kanji: '職', meaning: 'munka / állás', onyomi: 'ショク', kunyomi: '', romaji: 'shoku', jlpt: 'N3', lesson: 18 },
  { kanji: '置', meaning: 'elhelyez / rak', onyomi: 'チ', kunyomi: 'お', romaji: 'oku / chi', jlpt: 'N3', lesson: 18 },
  { kanji: '夫', meaning: 'férj / férfi', onyomi: 'フ・フウ', kunyomi: 'おっと', romaji: 'otto / fu', jlpt: 'N3', lesson: 18 },
  { kanji: '規', meaning: 'szabály / norma', onyomi: 'キ', kunyomi: '', romaji: 'ki', jlpt: 'N3', lesson: 18 },
  { kanji: '賛', meaning: 'egyetért / dicsér', onyomi: 'サン', kunyomi: '', romaji: 'san', jlpt: 'N3', lesson: 18 },
  { kanji: '失', meaning: 'elveszít / hiba', onyomi: 'シツ', kunyomi: 'うしな', romaji: 'ushinau / shitsu', jlpt: 'N3', lesson: 18 },
  { kanji: '労', meaning: 'munka / fáradozás', onyomi: 'ロウ', kunyomi: '', romaji: 'rou', jlpt: 'N3', lesson: 18 },
  { kanji: '努', meaning: 'igyekszik', onyomi: 'ド', kunyomi: 'つと', romaji: 'tsutomeru / do', jlpt: 'N3', lesson: 18 },
  { kanji: '加', meaning: 'hozzáad / növel', onyomi: 'カ', kunyomi: 'くわ', romaji: 'kuwa / ka', jlpt: 'N3', lesson: 18 },
  { kanji: '得', meaning: 'szerez / nyer', onyomi: 'トク', kunyomi: 'え', romaji: 'e / toku', jlpt: 'N3', lesson: 18 },
  { kanji: '徒', meaning: 'tanítvány / gyalog', onyomi: 'ト', kunyomi: '', romaji: 'to', jlpt: 'N3', lesson: 18 },
  { kanji: '彼', meaning: 'ő (férfi) / az', onyomi: 'ヒ', kunyomi: 'かれ', romaji: 'kare / hi', jlpt: 'N3', lesson: 18 },
  { kanji: '役', meaning: 'szerep / kötelesség', onyomi: 'ヤク・エキ', kunyomi: '', romaji: 'yaku', jlpt: 'N3', lesson: 18 },
  { kanji: '程', meaning: 'mérték / fok', onyomi: 'テイ', kunyomi: 'ほど', romaji: 'hodo / tei', jlpt: 'N3', lesson: 18 },
  { kanji: '和', meaning: 'béke / japán stílus', onyomi: 'ワ・オ', kunyomi: 'やわ', romaji: 'wa', jlpt: 'N3', lesson: 18 },
  { kanji: '利', meaning: 'haszon / előny', onyomi: 'リ', kunyomi: 'き', romaji: 'ri', jlpt: 'N3', lesson: 18 },
  { kanji: '米', meaning: 'rizs / Amerika', onyomi: 'ベイ・マイ', kunyomi: 'こめ', romaji: 'kome / bei', jlpt: 'N3', lesson: 18 },
  { kanji: '迷', meaning: 'eltéved / habozik', onyomi: 'メイ', kunyomi: 'まよ', romaji: 'mayo / mei', jlpt: 'N3', lesson: 18 },
  { kanji: '数', meaning: 'szám / mennyiség', onyomi: 'スウ', kunyomi: 'かず・かぞ', romaji: 'kazu / suu', jlpt: 'N3', lesson: 18 },
  { kanji: '類', meaning: 'fajta / típus', onyomi: 'ルイ', kunyomi: 'たぐ', romaji: 'rui', jlpt: 'N3', lesson: 18 },
  { kanji: '様', meaning: 'mód / Úr, Asszony', onyomi: 'ヨウ', kunyomi: 'さま', romaji: 'sama / you', jlpt: 'N3', lesson: 18 },
  { kanji: '求', meaning: 'kér / igényel', onyomi: 'キュウ', kunyomi: 'もと', romaji: 'moto / kyuu', jlpt: 'N3', lesson: 18 },
  { kanji: '球', meaning: 'gömb / labda', onyomi: 'キュウ', kunyomi: 'たま', romaji: 'tama / kyuu', jlpt: 'N3', lesson: 18 },
  { kanji: '笑', meaning: 'nevet / mosolyog', onyomi: 'ショウ', kunyomi: 'わら・え', romaji: 'wara / shou', jlpt: 'N3', lesson: 18 },
  { kanji: '箱', meaning: 'doboz', onyomi: 'ソウ', kunyomi: 'はこ', romaji: 'hako', jlpt: 'N3', lesson: 18 },
  { kanji: '等', meaning: 'stb. / egyenlő', onyomi: 'トウ', kunyomi: 'ひと', romaji: 'tou', jlpt: 'N3', lesson: 18 },
  { kanji: '位', meaning: 'rang / pozíció', onyomi: 'イ', kunyomi: 'くらい', romaji: 'kurai / i', jlpt: 'N3', lesson: 18 },
  { kanji: '件', meaning: 'ügy / eset', onyomi: 'ケン', kunyomi: '', romaji: 'ken', jlpt: 'N3', lesson: 18 },
  { kanji: '他', meaning: 'más / egyéb', onyomi: 'タ', kunyomi: 'ほか', romaji: 'hoka / ta', jlpt: 'N3', lesson: 18 },
  { kanji: '伝', meaning: 'közvetít / üzen', onyomi: 'デン', kunyomi: 'つた', romaji: 'tsuta / den', jlpt: 'N3', lesson: 18 },
  { kanji: '信', meaning: 'hisz / bizalom', onyomi: 'シン', kunyomi: '', romaji: 'shin', jlpt: 'N3', lesson: 18 },
  { kanji: '例', meaning: 'példa', onyomi: 'レイ', kunyomi: 'たと', romaji: 'tato / rei', jlpt: 'N3', lesson: 18 },
  { kanji: '側', meaning: 'oldal / mellett', onyomi: 'ソク', kunyomi: 'かわ', romaji: 'kawa / soku', jlpt: 'N3', lesson: 19 },
  { kanji: '値', meaning: 'érték / ár', onyomi: 'チ', kunyomi: 'あたい・ね', romaji: 'ne / chi', jlpt: 'N3', lesson: 19 },
  { kanji: '倒', meaning: 'összedől / ledönt', onyomi: 'トウ', kunyomi: 'たお', romaji: 'tao / tou', jlpt: 'N3', lesson: 19 },
  { kanji: '便', meaning: 'kényelem / posta', onyomi: 'ベン・ビン', kunyomi: 'たより', romaji: 'ben', jlpt: 'N3', lesson: 19 },
  { kanji: '優', meaning: 'kiváló / kedves', onyomi: 'ユウ', kunyomi: 'やさ・すぐ', romaji: 'yasa / yuu', jlpt: 'N3', lesson: 19 },
  { kanji: '宿', meaning: 'szállás / fogadó', onyomi: 'シュク', kunyomi: 'やど', romaji: 'yado / shuku', jlpt: 'N3', lesson: 19 },
  { kanji: '付', meaning: 'csatol / rátűz', onyomi: 'フ', kunyomi: 'つ', romaji: 'tsu / fu', jlpt: 'N3', lesson: 19 },
  { kanji: '任', meaning: 'rábíz / felelősség', onyomi: 'ニン', kunyomi: 'まか', romaji: 'maka / nin', jlpt: 'N3', lesson: 19 },
  { kanji: '化', meaning: 'változik / -izál', onyomi: 'カ・ケ', kunyomi: 'ば', romaji: 'ba / ka', jlpt: 'N3', lesson: 19 },
  { kanji: '内', meaning: 'belül / közepe', onyomi: 'ナイ・ダイ', kunyomi: 'うち', romaji: 'uchi / nai', jlpt: 'N3', lesson: 19 },
  { kanji: '座', meaning: 'ülés / hely', onyomi: 'ザ', kunyomi: 'すわ', romaji: 'suwa / za', jlpt: 'N3', lesson: 19 },
  { kanji: '似', meaning: 'hasonlít', onyomi: 'ジ', kunyomi: 'に', romaji: 'ni / ji', jlpt: 'N3', lesson: 19 },
  { kanji: '遊', meaning: 'játszik', onyomi: 'ユウ', kunyomi: 'あそ', romaji: 'aso / yuu', jlpt: 'N3', lesson: 19 },
  { kanji: '易', meaning: 'könnyű / egyszerű', onyomi: 'エキ・イ', kunyomi: 'やさ', romaji: 'yasa / eki', jlpt: 'N3', lesson: 19 },
  { kanji: '居', meaning: 'vhol tartózkodik / van', onyomi: 'キョ', kunyomi: 'い', romaji: 'i / kyo', jlpt: 'N3', lesson: 19 },
  { kanji: '局', meaning: 'hivatal / iroda', onyomi: 'キョク', kunyomi: '', romaji: 'kyoku', jlpt: 'N3', lesson: 19 },
  { kanji: '遅', meaning: 'késik / lassú', onyomi: 'チ', kunyomi: 'おく・おそ', romaji: 'oso / chi', jlpt: 'N3', lesson: 19 },
  { kanji: '戻', meaning: 'visszatér', onyomi: 'レイ', kunyomi: 'もど', romaji: 'modo / rei', jlpt: 'N3', lesson: 19 },
  { kanji: '示', meaning: 'mutat / jelez', onyomi: 'ジ・シ', kunyomi: 'しめ', romaji: 'shime / ji', jlpt: 'N3', lesson: 19 },
  { kanji: '礼', meaning: 'etikett / köszönet', onyomi: 'レイ・ライ', kunyomi: '', romaji: 'rei', jlpt: 'N3', lesson: 19 },
  { kanji: '福', meaning: 'szerencse / áldás', onyomi: 'フク', kunyomi: '', romaji: 'fuku', jlpt: 'N3', lesson: 19 },
  { kanji: '察', meaning: 'megfigyel / sejt', onyomi: 'サツ', kunyomi: '', romaji: 'satsu', jlpt: 'N3', lesson: 19 },
  { kanji: '由', meaning: 'ok / indok', onyomi: 'ユ・ユウ', kunyomi: 'よし', romaji: 'yoshi / yu', jlpt: 'N3', lesson: 19 },
  { kanji: '押', meaning: 'nyom / tol', onyomi: 'オウ', kunyomi: 'お', romaji: 'o / ou', jlpt: 'N3', lesson: 19 },
  { kanji: '申', meaning: 'mond (alázatos)', onyomi: 'シン', kunyomi: 'もう', romaji: 'mou / shin', jlpt: 'N3', lesson: 19 },
  { kanji: '神', meaning: 'isten', onyomi: 'シン・ジン', kunyomi: 'かみ', romaji: 'kami / shin', jlpt: 'N3', lesson: 19 },
  { kanji: '果', meaning: 'gyümölcs / eredmény', onyomi: 'カ', kunyomi: 'は', romaji: 'ha / ka', jlpt: 'N3', lesson: 19 },
  { kanji: '所', meaning: 'hely', onyomi: 'ショ', kunyomi: 'ところ', romaji: 'tokoro / sho', jlpt: 'N3', lesson: 19 },
  { kanji: '折', meaning: 'hajt / eltör', onyomi: 'セツ', kunyomi: 'お', romaji: 'o / setsu', jlpt: 'N3', lesson: 19 },
  { kanji: '断', meaning: 'visszautasít / levág', onyomi: 'ダン', kunyomi: 'ことわ・た', romaji: 'kotowa / dan', jlpt: 'N3', lesson: 19 },
  { kanji: '昨', meaning: 'tegnap / múlt', onyomi: 'サク', kunyomi: '', romaji: 'saku', jlpt: 'N3', lesson: 19 },
  { kanji: '雪', meaning: 'hó', onyomi: 'セツ', kunyomi: 'ゆき', romaji: 'yuki / setsu', jlpt: 'N3', lesson: 19 },
  { kanji: '寝', meaning: 'alszik / lefekszik', onyomi: 'シン', kunyomi: 'ね', romaji: 'ne / shin', jlpt: 'N3', lesson: 19 },
  { kanji: '婦', meaning: 'asszony / nő', onyomi: 'フ', kunyomi: '', romaji: 'fu', jlpt: 'N3', lesson: 19 },
  { kanji: '当', meaning: 'talál / megfelelő', onyomi: 'トウ', kunyomi: 'あ', romaji: 'a / tou', jlpt: 'N3', lesson: 19 },
  { kanji: '争', meaning: 'küzd / vitatkozik', onyomi: 'ソウ', kunyomi: 'あらそ', romaji: 'araso / sou', jlpt: 'N3', lesson: 19 },
  { kanji: '君', meaning: 'te / úr', onyomi: 'クン', kunyomi: 'きみ', romaji: 'kimi / kun', jlpt: 'N3', lesson: 19 },
  { kanji: '両', meaning: 'mindkettő', onyomi: 'リョウ', kunyomi: '', romaji: 'ryou', jlpt: 'N3', lesson: 19 },
  { kanji: '満', meaning: 'tele / elégedett', onyomi: 'マン', kunyomi: 'み', romaji: 'mi / man', jlpt: 'N3', lesson: 19 },
  { kanji: '歯', meaning: 'fog', onyomi: 'シ', kunyomi: 'は', romaji: 'ha / shi', jlpt: 'N3', lesson: 19 },
  { kanji: '曲', meaning: 'görbe / zeneszám', onyomi: 'キョク', kunyomi: 'ま', romaji: 'ma / kyoku', jlpt: 'N3', lesson: 20 },
  { kanji: '科', meaning: 'részleg / tantárgy', onyomi: 'カ', kunyomi: '', romaji: 'ka', jlpt: 'N3', lesson: 20 },
  { kanji: '備', meaning: 'készül / felszerel', onyomi: 'ビ', kunyomi: 'そな', romaji: 'sona / bi', jlpt: 'N3', lesson: 20 },
  { kanji: '昔', meaning: 'régen', onyomi: 'セキ・シャク', kunyomi: 'むかし', romaji: 'mukashi / seki', jlpt: 'N3', lesson: 20 },
  { kanji: '散', meaning: 'szór / szétszór', onyomi: 'サン', kunyomi: 'ち', romaji: 'chi / san', jlpt: 'N3', lesson: 20 },
  { kanji: '席', meaning: 'ülés / hely', onyomi: 'セキ', kunyomi: '', romaji: 'seki', jlpt: 'N3', lesson: 20 },
  { kanji: '渡', meaning: 'átkel / átad', onyomi: 'ト', kunyomi: 'わた', romaji: 'wata / to', jlpt: 'N3', lesson: 20 },
  { kanji: '判', meaning: 'megítél / pecsét', onyomi: 'ハン・バン', kunyomi: '', romaji: 'han', jlpt: 'N3', lesson: 20 },
  { kanji: '勝', meaning: 'győz / nyer', onyomi: 'ショウ', kunyomi: 'か', romaji: 'ka / shou', jlpt: 'N3', lesson: 20 },
  { kanji: '否', meaning: 'tagad / nem', onyomi: 'ヒ', kunyomi: 'いな', romaji: 'ina / hi', jlpt: 'N3', lesson: 20 },
  { kanji: '杯', meaning: 'pohár / csésze (számláló)', onyomi: 'ハイ', kunyomi: 'さかずき', romaji: 'sakazuki / hai', jlpt: 'N3', lesson: 20 },
  { kanji: '務', meaning: 'feladat / kötelesség', onyomi: 'ム', kunyomi: 'つと', romaji: 'tsuto / mu', jlpt: 'N3', lesson: 20 },
  { kanji: '引', meaning: 'húz', onyomi: 'イン', kunyomi: 'ひ', romaji: 'hi / in', jlpt: 'N3', lesson: 20 },
  { kanji: '費', meaning: 'költség', onyomi: 'ヒ', kunyomi: 'つい', romaji: 'tsui / hi', jlpt: 'N3', lesson: 20 },
  { kanji: '号', meaning: 'szám (sorszám)', onyomi: 'ゴウ', kunyomi: '', romaji: 'gou', jlpt: 'N3', lesson: 20 },
  { kanji: '与', meaning: 'ad / nyújt', onyomi: 'ヨ', kunyomi: 'あた', romaji: 'ata / yo', jlpt: 'N3', lesson: 20 },
  { kanji: '身', meaning: 'test / státusz', onyomi: 'シン', kunyomi: 'み', romaji: 'mi / shin', jlpt: 'N3', lesson: 20 },
  { kanji: '老', meaning: 'öreg', onyomi: 'ロウ', kunyomi: 'お', romaji: 'o / rou', jlpt: 'N3', lesson: 20 },
  { kanji: '追', meaning: 'üldöz / követ', onyomi: 'ツイ', kunyomi: 'お', romaji: 'o / tsui', jlpt: 'N3', lesson: 20 },
  { kanji: '師', meaning: 'tanár / mester', onyomi: 'シ', kunyomi: '', romaji: 'shi', jlpt: 'N3', lesson: 20 },
  { kanji: '官', meaning: 'hivatalnok / kormány', onyomi: 'カン', kunyomi: '', romaji: 'kan', jlpt: 'N3', lesson: 20 },
  { kanji: '交', meaning: 'kicserél / keveredik', onyomi: 'コウ', kunyomi: 'まじ', romaji: 'maji / kou', jlpt: 'N3', lesson: 20 },
  { kanji: '路', meaning: 'út / utca', onyomi: 'ロ', kunyomi: 'じ', romaji: 'ji / ro', jlpt: 'N3', lesson: 20 },
  { kanji: '過', meaning: 'túlzásba visz / elmúlik', onyomi: 'カ', kunyomi: 'す', romaji: 'su / ka', jlpt: 'N3', lesson: 20 },
  { kanji: '阪', meaning: 'lejtő (Oszaka)', onyomi: 'ハン', kunyomi: 'さか', romaji: 'saka / han', jlpt: 'N3', lesson: 21 },
  { kanji: '際', meaning: 'alkalom / szél', onyomi: 'サイ', kunyomi: 'きわ', romaji: 'kiwa / sai', jlpt: 'N3', lesson: 21 },
  { kanji: '陽', meaning: 'napfény / pozitív', onyomi: 'ヨウ', kunyomi: '', romaji: 'you', jlpt: 'N3', lesson: 21 },
  { kanji: '降', meaning: 'leszáll / esik (hó, eső)', onyomi: 'コウ', kunyomi: 'お・ふ', romaji: 'furu / kou', jlpt: 'N3', lesson: 21 },
  { kanji: '突', meaning: 'hirtelen / szúr', onyomi: 'トツ', kunyomi: 'つ', romaji: 'tsu / totsu', jlpt: 'N3', lesson: 21 },
  { kanji: '探', meaning: 'keres / kutat', onyomi: 'タン', kunyomi: 'さが', romaji: 'saga / tan', jlpt: 'N3', lesson: 21 },
  { kanji: '深', meaning: 'mély', onyomi: 'シン', kunyomi: 'ふか', romaji: 'fuka / shin', jlpt: 'N3', lesson: 21 },
  { kanji: '緒', meaning: 'szál / kezdet', onyomi: 'ショ・ジョ', kunyomi: 'お', romaji: 'o / sho', jlpt: 'N3', lesson: 21 },
  { kanji: '続', meaning: 'folytatódik', onyomi: 'ゾク', kunyomi: 'つづ', romaji: 'tsuzu / zoku', jlpt: 'N3', lesson: 21 },
  { kanji: '絵', meaning: 'kép / festmény', onyomi: 'カイ・エ', kunyomi: '', romaji: 'e / kai', jlpt: 'N3', lesson: 21 },
  { kanji: '給', meaning: 'fizetés / ellátás', onyomi: 'キュウ', kunyomi: 'たま', romaji: 'kyuu', jlpt: 'N3', lesson: 21 },
  { kanji: '経', meaning: 'keresztülmegy / vonal', onyomi: 'ケイ・キョウ', kunyomi: 'へ', romaji: 'kei / he', jlpt: 'N3', lesson: 21 },
  { kanji: '約', meaning: 'ígéret / körülbelül', onyomi: 'ヤク', kunyomi: '', romaji: 'yaku', jlpt: 'N3', lesson: 21 },
  { kanji: '幾', meaning: 'hány / mennyi', onyomi: 'キ', kunyomi: 'いく', romaji: 'iku / ki', jlpt: 'N3', lesson: 21 },
  { kanji: '機', meaning: 'gép / alkalom', onyomi: 'キ', kunyomi: 'はた', romaji: 'ki', jlpt: 'N3', lesson: 21 },
  { kanji: '係', meaning: 'felelős / kapcsolat', onyomi: 'ケイ', kunyomi: 'かか', romaji: 'kakari / kei', jlpt: 'N3', lesson: 21 },
  { kanji: '御', meaning: 'tiszteleti előtag', onyomi: 'ギョ・ゴ', kunyomi: 'おん', romaji: 'go / o', jlpt: 'N3', lesson: 21 },
  { kanji: '命', meaning: 'élet / végzet', onyomi: 'メイ・ミョウ', kunyomi: 'いのち', romaji: 'inochi / mei', jlpt: 'N3', lesson: 21 },
  { kanji: '冷', meaning: 'hideg (tapintásra)', onyomi: 'レイ', kunyomi: 'つめ・ひ・さ', romaji: 'tsume / rei', jlpt: 'N3', lesson: 21 },
  { kanji: '疑', meaning: 'gyanú / kétség', onyomi: 'ギ', kunyomi: 'うたが', romaji: 'utagau / gi', jlpt: 'N3', lesson: 21 },
  { kanji: '犯', meaning: 'bűntény / elkövet', onyomi: 'ハン', kunyomi: 'おか', romaji: 'okasu / han', jlpt: 'N3', lesson: 21 },
  { kanji: '危', meaning: 'veszélyes', onyomi: 'キ', kunyomi: 'あぶ・あや', romaji: 'abunai / ki', jlpt: 'N3', lesson: 21 },
  { kanji: '留', meaning: 'rögzít / marad', onyomi: 'リュウ・ル', kunyomi: 'と・とど', romaji: 'tomaru / ryuu', jlpt: 'N3', lesson: 21 },
  { kanji: '酒', meaning: 'szake / alkohol', onyomi: 'シュ', kunyomi: 'さけ・さか', romaji: 'sake / shu', jlpt: 'N3', lesson: 21 },
  { kanji: '配', meaning: 'kioszt / szétoszt', onyomi: 'ハイ', kunyomi: 'くば', romaji: 'kubaru / hai', jlpt: 'N3', lesson: 22 },
  { kanji: '頭', meaning: 'fej', onyomi: 'トウ・ズ', kunyomi: 'あたま・かしら', romaji: 'atama / tou', jlpt: 'N3', lesson: 22 },
  { kanji: '喜', meaning: 'örül', onyomi: 'キ', kunyomi: 'よろこ', romaji: 'yorokobu / ki', jlpt: 'N3', lesson: 22 },
  { kanji: '盗', meaning: 'lop', onyomi: 'トウ', kunyomi: 'ぬす', romaji: 'nusumu / tou', jlpt: 'N3', lesson: 22 },
  { kanji: '退', meaning: 'visszavonul', onyomi: 'タイ', kunyomi: 'しりぞ・ど', romaji: 'shirizoku / tai', jlpt: 'N3', lesson: 22 },
  { kanji: '限', meaning: 'korlát / limit', onyomi: 'ゲン', kunyomi: 'かぎ', romaji: 'kagiru / gen', jlpt: 'N3', lesson: 22 },
  { kanji: '良', meaning: 'jó', onyomi: 'リョウ', kunyomi: 'よ', romaji: 'yoi / ryou', jlpt: 'N3', lesson: 22 },
  { kanji: '娘', meaning: 'lánya / fiatal nő', onyomi: '', kunyomi: 'むすめ', romaji: 'musume', jlpt: 'N3', lesson: 22 },
  { kanji: '平', meaning: 'sík / lapos / béke', onyomi: 'ヘイ・ビョウ', kunyomi: 'たいら・ひら', romaji: 'taira / hei', jlpt: 'N3', lesson: 22 },
  { kanji: '呼', meaning: 'hív / szólít', onyomi: 'コ', kunyomi: 'よ', romaji: 'yobu / ko', jlpt: 'N3', lesson: 22 },
  { kanji: '殺', meaning: 'öl / gyilkol', onyomi: 'サツ・サイ', kunyomi: 'ころ', romaji: 'korosu / satsu', jlpt: 'N3', lesson: 22 },
  { kanji: '辞', meaning: 'lemond / szó / szótár', onyomi: 'ジ', kunyomi: 'や', romaji: 'yameru / ji', jlpt: 'N3', lesson: 22 },
  { kanji: '幸', meaning: 'boldogság / szerencse', onyomi: 'コウ', kunyomi: 'さいわ・しあわ', romaji: 'shiawase / kou', jlpt: 'N3', lesson: 22 },
  { kanji: '報', meaning: 'jelent / jutalmaz', onyomi: 'ホウ', kunyomi: 'むく', romaji: 'hou', jlpt: 'N3', lesson: 22 },
  { kanji: '収', meaning: 'beszed / raktároz', onyomi: 'シュウ', kunyomi: 'おさ', romaji: 'osameru / shuu', jlpt: 'N3', lesson: 22 },
  { kanji: '熱', meaning: 'forró / láz', onyomi: 'ネツ', kunyomi: 'あつ', romaji: 'atsui / netsu', jlpt: 'N3', lesson: 22 },
  { kanji: '刻', meaning: 'vés / időpont', onyomi: 'コク', kunyomi: 'きざ', romaji: 'kizamu / koku', jlpt: 'N3', lesson: 22 },
  { kanji: '術', meaning: 'művészet / technika', onyomi: 'ジュツ', kunyomi: 'すべ', romaji: 'jutsu', jlpt: 'N3', lesson: 22 },
  { kanji: '寒', meaning: 'hideg (időjárás)', onyomi: 'カン', kunyomi: 'さむ', romaji: 'samui / kan', jlpt: 'N3', lesson: 22 },
  { kanji: '精', meaning: 'energia / finomít', onyomi: 'セイ・ショウ', kunyomi: '', romaji: 'sei', jlpt: 'N3', lesson: 22 },
  { kanji: '情', meaning: 'érzés / körülmény', onyomi: 'ジョウ・セイ', kunyomi: 'なさ', romaji: 'nasake / jou', jlpt: 'N3', lesson: 22 },
  { kanji: '晴', meaning: 'kitisztul (idő)', onyomi: 'セイ', kunyomi: 'は', romaji: 'hareru / sei', jlpt: 'N3', lesson: 22 },
  { kanji: '静', meaning: 'csendes', onyomi: 'セイ・ジョウ', kunyomi: 'しず', romaji: 'shizuka / sei', jlpt: 'N3', lesson: 22 },
  { kanji: '責', meaning: 'felelősség / hibáztat', onyomi: 'セキ', kunyomi: 'せめ', romaji: 'semeru / seki', jlpt: 'N3', lesson: 22 },
  { kanji: '積', meaning: 'felhalmoz', onyomi: 'セキ', kunyomi: 'つ', romaji: 'tsumu / seki', jlpt: 'N3', lesson: 23 },
  { kanji: '表', meaning: 'felület / mutat', onyomi: 'ヒョウ', kunyomi: 'おもて・あらわ', romaji: 'omote / hyou', jlpt: 'N3', lesson: 23 },
  { kanji: '害', meaning: 'kár / ártalom', onyomi: 'ガイ', kunyomi: '', romaji: 'gai', jlpt: 'N3', lesson: 23 },
  { kanji: '割', meaning: 'oszt / eloszt / arány', onyomi: 'カツ', kunyomi: 'わ', romaji: 'waru / katsu', jlpt: 'N3', lesson: 23 },
  { kanji: '性', meaning: 'nem / természet', onyomi: 'セイ・ショウ', kunyomi: '', romaji: 'sei', jlpt: 'N3', lesson: 23 },
  { kanji: '産', meaning: 'szül / termel', onyomi: 'サン', kunyomi: 'う', romaji: 'umu / san', jlpt: 'N3', lesson: 23 },
  { kanji: '実', meaning: 'valóság / gyümölcs', onyomi: 'ジツ', kunyomi: 'み・みの', romaji: 'mi / jitsu', jlpt: 'N3', lesson: 23 },
  { kanji: '勤', meaning: 'szolgál / dolgozik', onyomi: 'キン・ゴン', kunyomi: 'つと', romaji: 'tsutomeru / kin', jlpt: 'N3', lesson: 23 },
  { kanji: '難', meaning: 'nehéz / baj', onyomi: 'ナン', kunyomi: 'むずか', romaji: 'nan / muzukashii', jlpt: 'N3', lesson: 23 },
  { kanji: '乗', meaning: 'felszáll / utazik', onyomi: 'ジョウ', kunyomi: 'の', romaji: 'jou / noru', jlpt: 'N3', lesson: 23 },
  { kanji: '念', meaning: 'gondolat / vágy', onyomi: 'ネン', kunyomi: '', romaji: 'nen', jlpt: 'N3', lesson: 23 },
  { kanji: '予', meaning: 'előre', onyomi: 'ヨ', kunyomi: 'あらかじ', romaji: 'yo', jlpt: 'N3', lesson: 23 },
  { kanji: '要', meaning: 'szükséges', onyomi: 'ヨウ', kunyomi: 'い', romaji: 'you / iru', jlpt: 'N3', lesson: 23 },
  { kanji: '煙', meaning: 'füst', onyomi: 'エン', kunyomi: 'けむり', romaji: 'en / kemuri', jlpt: 'N3', lesson: 23 },
  { kanji: '閉', meaning: 'bezár', onyomi: 'ヘイ', kunyomi: 'と・し', romaji: 'hei / tojiru', jlpt: 'N3', lesson: 23 },
  { kanji: '非', meaning: 'nem / hiba / igazságtalanság', onyomi: 'ヒ', kunyomi: 'あら', romaji: 'hi', jlpt: 'N3', lesson: 23 },
  { kanji: '悲', meaning: 'szomorú', onyomi: 'ヒ', kunyomi: 'かな', romaji: 'hi / kanashii', jlpt: 'N3', lesson: 23 },
  { kanji: '罪', meaning: 'bűn', onyomi: 'ザイ', kunyomi: 'つみ', romaji: 'zai / tsumi', jlpt: 'N3', lesson: 23 },
  { kanji: '候', meaning: 'időjárás / évszak', onyomi: 'コウ', kunyomi: 'そうろう', romaji: 'kou', jlpt: 'N3', lesson: 23 },
  { kanji: '決', meaning: 'eldönt', onyomi: 'ケツ', kunyomi: 'き', romaji: 'ketsu / kimeru', jlpt: 'N3', lesson: 23 },
  { kanji: '偉', meaning: 'nagyszerű / hatalmas', onyomi: 'イ', kunyomi: 'えら', romaji: 'i / erai', jlpt: 'N3', lesson: 23 },
  { kanji: '違', meaning: 'különbözik / tévedés', onyomi: 'イ', kunyomi: 'ちが', romaji: 'i / chigau', jlpt: 'N3', lesson: 23 },
  { kanji: '余', meaning: 'maradék / több mint', onyomi: 'ヨ', kunyomi: 'あま', romaji: 'yo / amaru', jlpt: 'N3', lesson: 23 },
  { kanji: '除', meaning: 'eltávolít / kivétel', onyomi: 'ジョ・ジ', kunyomi: 'のぞ', romaji: 'jo / nozoku', jlpt: 'N3', lesson: 23 },
  { kanji: '途', meaning: 'út / folyamat', onyomi: 'ト', kunyomi: 'みち', romaji: 'to', jlpt: 'N3', lesson: 24 },
  { kanji: '束', meaning: 'köteg / csokor', onyomi: 'ソク', kunyomi: 'たば', romaji: 'soku / taba', jlpt: 'N3', lesson: 24 },
  { kanji: '頼', meaning: 'kér / megbíz', onyomi: 'ライ', kunyomi: 'たの・たよ', romaji: 'rai / tanomu', jlpt: 'N3', lesson: 24 },
  { kanji: '速', meaning: 'gyors', onyomi: 'ソク', kunyomi: 'はや', romaji: 'soku / hayai', jlpt: 'N3', lesson: 24 },
  { kanji: '険', meaning: 'meredek / veszélyes', onyomi: 'ケン', kunyomi: 'けわ', romaji: 'ken / kewashii', jlpt: 'N3', lesson: 24 },
  { kanji: '働', meaning: 'dolgozik', onyomi: 'ドウ', kunyomi: 'はたら', romaji: 'dou / hataraku', jlpt: 'N3', lesson: 24 },
  { kanji: '種', meaning: 'mag / fajta', onyomi: 'シュ', kunyomi: 'たね', romaji: 'shu / tane', jlpt: 'N3', lesson: 24 },
  { kanji: '疲', meaning: 'elfárad', onyomi: 'ヒ', kunyomi: 'つか', romaji: 'hi / tsukareru', jlpt: 'N3', lesson: 24 },
  { kanji: '痛', meaning: 'fájdalom', onyomi: 'ツウ', kunyomi: 'いた', romaji: 'tsuu / itai', jlpt: 'N3', lesson: 24 },
  { kanji: '迎', meaning: 'üdvözöl / fogad', onyomi: 'ゲイ', kunyomi: 'むか', romaji: 'gei / mukaeru', jlpt: 'N3', lesson: 24 },
  { kanji: '登', meaning: 'mászik / felemelkedik', onyomi: 'トウ・ト', kunyomi: 'のぼ', romaji: 'tou / noboru', jlpt: 'N3', lesson: 24 },
  { kanji: '形', meaning: 'alak / forma', onyomi: 'ケイ・ギョウ', kunyomi: 'かたち', romaji: 'kei / katachi', jlpt: 'N3', lesson: 24 },
  { kanji: '顔', meaning: 'arc', onyomi: 'ガン', kunyomi: 'かお', romaji: 'gan / kao', jlpt: 'N3', lesson: 24 },
  { kanji: '参', meaning: 'részt vesz / jön-megy (alázatos)', onyomi: 'サン', kunyomi: 'まい', romaji: 'san / mairu', jlpt: 'N3', lesson: 24 },
  { kanji: '対', meaning: 'szemben / ellentét / pár', onyomi: 'タイ・ツイ', kunyomi: '', romaji: 'tai', jlpt: 'N3', lesson: 24 },
  { kanji: '済', meaning: 'befejezett / rendezett', onyomi: 'サイ', kunyomi: 'す', romaji: 'sai / sumu', jlpt: 'N3', lesson: 24 },
  { kanji: '薬', meaning: 'gyógyszer', onyomi: 'ヤク', kunyomi: 'くすり', romaji: 'yaku / kusuri', jlpt: 'N3', lesson: 24 },
  { kanji: '変', meaning: 'változik / fura', onyomi: 'ヘン', kunyomi: 'か', romaji: 'hen / kawaru', jlpt: 'N3', lesson: 24 },
  { kanji: '横', meaning: 'oldalsó / vízszintes', onyomi: 'オウ', kunyomi: 'よこ', romaji: 'ou / yoko', jlpt: 'N3', lesson: 24 },
  { kanji: '絶', meaning: 'megszűnik / abszolút', onyomi: 'ゼツ', kunyomi: 'た', romaji: 'zetsu / tatsu', jlpt: 'N3', lesson: 24 },
  { kanji: '期', meaning: 'időszak / várakozás', onyomi: 'キ・ゴ', kunyomi: '', romaji: 'ki', jlpt: 'N3', lesson: 24 },
  { kanji: '舞', meaning: 'tánc', onyomi: 'ブ', kunyomi: 'ま', romaji: 'bu / mau', jlpt: 'N3', lesson: 24 },
  { kanji: '組', meaning: 'csoport / összeállít', onyomi: 'ソ', kunyomi: 'くみ・く', romaji: 'so / kumi', jlpt: 'N3', lesson: 24 },
  { kanji: '祖', meaning: 'ős / nagyszülő', onyomi: 'ソ', kunyomi: '', romaji: 'so', jlpt: 'N3', lesson: 24 },
  { kanji: '助', meaning: 'segít / ment', onyomi: 'ジョ', kunyomi: 'たす', romaji: 'jo / tasukeru', jlpt: 'N3', lesson: 25 },
  { kanji: '共', meaning: 'együtt / közös', onyomi: 'キョウ', kunyomi: 'とも', romaji: 'kyou / tomo', jlpt: 'N3', lesson: 25 },
  { kanji: '供', meaning: 'felajánl / kísérő', onyomi: 'キョウ・ク', kunyomi: 'そな・とも', romaji: 'kyou / tomo', jlpt: 'N3', lesson: 25 },
  { kanji: '港', meaning: 'kikötő', onyomi: 'コウ', kunyomi: 'みなと', romaji: 'kou / minato', jlpt: 'N3', lesson: 25 },
  { kanji: '選', meaning: 'választ', onyomi: 'セン', kunyomi: 'えら', romaji: 'sen / erabu', jlpt: 'N3', lesson: 25 },
  { kanji: '解', meaning: 'megold / felold', onyomi: 'カイ・ゲ', kunyomi: 'と', romaji: 'kai / toku', jlpt: 'N3', lesson: 25 },
  { kanji: '構', meaning: 'szerkezet / törődik', onyomi: 'コウ', kunyomi: 'かま', romaji: 'kou / kamaeru', jlpt: 'N3', lesson: 25 },
  { kanji: '論', meaning: 'elmélet / vita', onyomi: 'ロン', kunyomi: '', romaji: 'ron', jlpt: 'N3', lesson: 25 },
  { kanji: '婚', meaning: 'házasság', onyomi: 'コン', kunyomi: '', romaji: 'kon', jlpt: 'N3', lesson: 25 },
  { kanji: '民', meaning: 'nép / állampolgár', onyomi: 'ミン', kunyomi: 'たみ', romaji: 'min / tami', jlpt: 'N3', lesson: 25 },
  { kanji: '眠', meaning: 'alszik', onyomi: 'ミン', kunyomi: 'ねむ', romaji: 'min / nemuru', jlpt: 'N3', lesson: 25 },
  { kanji: '捕', meaning: 'elkap / elfog', onyomi: 'ホ', kunyomi: 'と・つか', romaji: 'ho / toraeru', jlpt: 'N3', lesson: 25 },
  { kanji: '部', meaning: 'rész / osztály / klub', onyomi: 'ブ', kunyomi: '', romaji: 'bu', jlpt: 'N3', lesson: 25 },
  { kanji: '都', meaning: 'főváros / metropolisz', onyomi: 'ト・ツ', kunyomi: 'みやこ', romaji: 'to / miyako', jlpt: 'N3', lesson: 25 },
  { kanji: '段', meaning: 'lépcső / szint / fok', onyomi: 'ダン', kunyomi: '', romaji: 'dan', jlpt: 'N3', lesson: 25 },
  { kanji: '船', meaning: 'hajó', onyomi: 'セン', kunyomi: 'ふね', romaji: 'sen / fune', jlpt: 'N3', lesson: 25 },
  { kanji: '飛', meaning: 'repül', onyomi: 'ヒ', kunyomi: 'と', romaji: 'hi / tobu', jlpt: 'N3', lesson: 25 },
  { kanji: '妻', meaning: 'feleség', onyomi: 'サイ', kunyomi: 'つま', romaji: 'sai / tsuma', jlpt: 'N3', lesson: 25 },
  { kanji: '面', meaning: 'arc / felület / maszk', onyomi: 'メン', kunyomi: 'おも', romaji: 'men', jlpt: 'N3', lesson: 25 },
  { kanji: '靴', meaning: 'cipő', onyomi: 'カ', kunyomi: 'くつ', romaji: 'kutsu', jlpt: 'N3', lesson: 25 },
  { kanji: '声', meaning: 'hang (élőlény)', onyomi: 'セイ・ショウ', kunyomi: 'こえ', romaji: 'koe / sei', jlpt: 'N3', lesson: 25 },
  { kanji: '誤', meaning: 'hiba / tévedés', onyomi: 'ゴ', kunyomi: 'あやま', romaji: 'go / ayamaru', jlpt: 'N3', lesson: 25 },
  { kanji: '番', meaning: 'szám / sorrend / őrség', onyomi: 'バン', kunyomi: '', romaji: 'ban', jlpt: 'N3', lesson: 25 },
  { kanji: '宅', meaning: 'ház / otthon', onyomi: 'タク', kunyomi: '', romaji: 'taku', jlpt: 'N3', lesson: 25 },
  { kanji: '髪', meaning: 'haj', onyomi: 'ハツ', kunyomi: 'かみ', romaji: 'kami / hatsu', jlpt: 'N3', lesson: 25 },
  { kanji: '単', meaning: 'egyszerű / egyedüli', onyomi: 'タン', kunyomi: '', romaji: 'tan', jlpt: 'N3', lesson: 25 },
  { kanji: '戦', meaning: 'háború / harc', onyomi: 'セン', kunyomi: 'たたか', romaji: 'sen / tatakau', jlpt: 'N3', lesson: 25 },
  { kanji: '鳴', meaning: 'szól / csiripel / morog', onyomi: 'メイ', kunyomi: 'な', romaji: 'naru / mei', jlpt: 'N3', lesson: 25 },
  { kanji: '偶', meaning: 'véletlen / bábu', onyomi: 'グウ', kunyomi: '', romaji: 'guu', jlpt: 'N3', lesson: 25 },
  { kanji: '晩', meaning: 'este', onyomi: 'バン', kunyomi: '', romaji: 'ban', jlpt: 'N3', lesson: 25 },
  { kanji: '馬', meaning: 'ló', onyomi: 'バ', kunyomi: 'うま', romaji: 'uma / ba', jlpt: 'N3', lesson: 25 },
  { kanji: '能', meaning: 'képesség / tehetség', onyomi: 'ノウ', kunyomi: '', romaji: 'nou', jlpt: 'N3', lesson: 25 },
  { kanji: '演', meaning: 'előad / játszik', onyomi: 'エン', kunyomi: '', romaji: 'en', jlpt: 'N3', lesson: 25 },
  { kanji: '関', meaning: 'kapcsolat / gát / érint', onyomi: 'カン', kunyomi: 'せき', romaji: 'kan / seki', jlpt: 'N3', lesson: 25 }
];